export type FluentOverrideValue =
  | {
      f2Token: string;
      rawValue?: never;
    }
  | {
      f2Token?: never;
      rawValue: string;
    };

// Null is used when a token should have variant inline fallbacks (variant v9 fallbacks for a single token)
export type FluentOverrides = Record<string, FluentOverrideValue | null>;

export const fluentOverrides: FluentOverrides = {
  ctrlFocusOuterStroke: {
    f2Token: 'colorTransparentStroke',
  },
  ctrlLinkForegroundBrandRest: { f2Token: 'colorBrandForegroundLink' },
  textStyleDefaultRegularFontfamily: { f2Token: 'fontFamilyBase' },
  textGlobalBody3Fontsize: { f2Token: 'fontSizeBase300' },
  textStyleDefaultRegularWeight: { f2Token: 'fontWeightRegular' },
  strokewidthDefault: { f2Token: 'strokeWidthThin' },
  ctrlFocusInnerStrokewidth: { f2Token: 'strokeWidthThin' },
  ctrlLinkForegroundBrandHover: { f2Token: 'colorBrandForegroundLinkHover' },
  ctrlLinkForegroundBrandPressed: { f2Token: 'colorBrandForegroundLinkPressed' },
  ctrlLinkForegroundNeutralRest: { f2Token: 'colorNeutralForeground2' },
  ctrlLinkForegroundNeutralPressed: { f2Token: 'colorNeutralForeground2Pressed' },
  ctrlLinkForegroundNeutralHover: { f2Token: 'colorNeutralForeground2Hover' },
  foregroundCtrlNeutralPrimaryDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  backgroundCtrlNeutralRest: { f2Token: 'colorNeutralBackground1' },
  foregroundCtrlNeutralPrimaryRest: { f2Token: 'colorNeutralForeground1' },
  strokeCtrlOnneutralRest: { f2Token: 'colorNeutralStroke1' },
  backgroundCtrlNeutralHover: { f2Token: 'colorNeutralBackground1Hover' },
  strokeCtrlOnneutralHover: { f2Token: 'colorNeutralStroke1Hover' },
  foregroundCtrlNeutralPrimaryHover: { f2Token: 'colorNeutralForeground1Hover' },
  backgroundCtrlNeutralPressed: { f2Token: 'colorNeutralBackground1Pressed' },
  strokeCtrlOnneutralPressed: { f2Token: 'colorNeutralStroke1Pressed' },
  foregroundCtrlNeutralPrimaryPressed: { f2Token: 'colorNeutralForeground1Pressed' },
  textRampItembodyFontsize: { f2Token: 'fontSizeBase300' },
  textCtrlButtonWeightDefault: { f2Token: 'fontWeightSemibold' },
  textRampItembodyLineheight: { f2Token: 'lineHeightBase300' },
  ctrlFocusInnerStroke: { f2Token: 'colorStrokeFocus2' },
  ctrlFocusOuterStrokewidth: { f2Token: 'strokeWidthThick' },
  cornerCtrlRest: { f2Token: 'borderRadiusMedium' },
  strokeLayer: { f2Token: 'colorTransparentStroke' },
  backgroundCtrlBrandRest: { f2Token: 'colorBrandBackground' },
  backgroundCtrlBrandHover: { f2Token: 'colorBrandBackgroundHover' },
  foregroundCtrlOnbrandRest: { f2Token: 'colorNeutralForegroundOnBrand' },
  foregroundCtrlOnbrandHover: { f2Token: 'colorNeutralForegroundOnBrand' },
  foregroundCtrlOnbrandPressed: { f2Token: 'colorNeutralForegroundOnBrand' },
  backgroundCtrlSubtleRest: { f2Token: 'colorSubtleBackground' },
  foregroundCtrlOnsubtleRest: { f2Token: 'colorNeutralForeground2' },
  backgroundCtrlSubtleHover: { f2Token: 'colorSubtleBackgroundHover' },
  backgroundCtrlSubtlePressed: { f2Token: 'colorSubtleBackgroundPressed' },
  foregroundCtrlOnsubtleHover: { f2Token: 'colorNeutralForeground2Hover' },
  foregroundCtrlOnsubtlePressed: { f2Token: 'colorNeutralForeground2Pressed' },
  foregroundCtrlIconOnsubtlePressed: { f2Token: 'colorNeutralForeground2BrandPressed' },
  foregroundCtrlIconOnsubtleHover: { f2Token: 'colorNeutralForeground2BrandHover' },
  strokeCtrlOnactivebrandRest: { f2Token: 'colorNeutralForegroundOnBrand' },
  strokeCtrlOnactivebrandHover: { f2Token: 'colorStrokeFocus2' },
  cornerCircular: { f2Token: 'borderRadiusCircular' },
  paddingCtrlLgHorizontalDefault: { f2Token: 'spacingHorizontalL' },
  paddingCtrlSmHorizontalDefault: { f2Token: 'spacingHorizontalS' },
  cornerCtrlSmRest: { f2Token: 'borderRadiusMedium' }, // Button uses borderRadiusMedium in all sizes
  cornerCtrlLgRest: { f2Token: 'borderRadiusMedium' }, // Button uses borderRadiusMedium in all sizes
  paddingCtrlSmHorizontalIcononly: { rawValue: '1px' },
  paddingCtrlHorizontalIcononly: { rawValue: '5px' },
  paddingCtrlLgHorizontalIcononly: { rawValue: '7px' },
  sizeCtrlSmIcon: { rawValue: '20px' },
  sizeCtrlIcon: { rawValue: '20px' },
  sizeCtrlLgIcon: { rawValue: '24px' },
  backgroundCtrlNeutralDisabled: { f2Token: 'colorNeutralBackgroundDisabled' },
  foregroundCtrlIconOnneutralDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  foregroundCtrlNeutralSecondaryDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  textRampLgItembodyFontsize: { f2Token: 'fontSizeBase400' },
  cornerZero: { f2Token: 'borderRadiusNone' },
  textRampSmItembodyFontsize: { f2Token: 'fontSizeBase200' },
  textRampLgItembodyLineheight: { f2Token: 'lineHeightBase400' },
  textRampSmItembodyLineheight: { f2Token: 'lineHeightBase200' },
  strokeCtrlOnneutralDisabled: { f2Token: 'colorNeutralStrokeDisabled' },
  strokeCtrlOnbrandDisabled: { rawValue: 'transparent' },
  strokewidthCtrlOutlineRest: { f2Token: 'strokeWidthThin' },
  strokewidthCtrlOutlineHover: { f2Token: 'strokeWidthThin' },
  strokewidthCtrlOutlinePressed: { f2Token: 'strokeWidthThin' },
  backgroundCtrlOutlineRest: { f2Token: 'colorTransparentBackground' },
  backgroundCtrlOutlineHover: { f2Token: 'colorTransparentBackground' },
  backgroundCtrlOutlinePressed: { f2Token: 'colorTransparentBackground' },
  strokeCtrlOnbrandRest: { rawValue: 'transparent' },
  strokeCtrlOnbrandHover: { rawValue: 'transparent' },
  strokeCtrlOnbrandPressed: { rawValue: 'transparent' },
  foregroundCtrlOntransparentRest: { f2Token: 'colorNeutralForeground2' },
  foregroundCtrlOntransparentHover: { f2Token: 'colorNeutralForeground2BrandHover' },
  foregroundCtrlOntransparentPressed: { f2Token: 'colorNeutralForeground2BrandPressed' },
  foregroundCtrlOntransparentDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  backgroundCtrlBrandPressed: { f2Token: 'colorBrandBackgroundPressed' },
  paddingCtrlTextbottom: { rawValue: '5px' },
  paddingCtrlTexttop: { rawValue: '5px' },
  paddingCtrlHorizontalDefault: { f2Token: 'spacingHorizontalM' },
  paddingCtrlTextside: { rawValue: '0px' }, // For now, text padding is not applied (use default);
  gapInsideCtrlSmDefault: { f2Token: 'spacingHorizontalXS' },
  gapInsideCtrlDefault: { f2Token: 'spacingHorizontalSNudge' },
  gapInsideCtrlLgDefault: { f2Token: 'spacingHorizontalSNudge' },
  backgroundCtrlSubtleDisabled: { f2Token: 'colorTransparentBackground' },
  sizeCtrlDefault: { rawValue: '96px' },
  sizeCtrlSmDefault: { rawValue: '64px' },
  sizeCtrlLgDefault: { rawValue: '96px' },
  strokeCtrlOnoutlineDisabled: { f2Token: 'colorNeutralStrokeDisabled' },
  foregroundCtrlIconOnsubtleDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  foregroundCtrlIconOnsubtleRest: { f2Token: 'colorNeutralForeground2' },
  foregroundCtrlOnoutlineDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  foregroundCtrlOnoutlineHover: { f2Token: 'colorNeutralForeground1Hover' },
  foregroundCtrlOnoutlinePressed: { f2Token: 'colorNeutralForeground1Pressed' },
  foregroundCtrlOnoutlineRest: { f2Token: 'colorNeutralForeground1' },
  foregroundCtrlOnsubtleDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  strokeCtrlOnsubtleRest: { rawValue: 'transparent' },
  strokeCtrlOnsubtleHover: { rawValue: 'transparent' },
  strokeCtrlOnsubtlePressed: { rawValue: 'transparent' },
  strokeCtrlOnsubtleDisabled: { rawValue: 'transparent' },
  strokeCtrlOnoutlineRest: { f2Token: 'colorNeutralStroke1' },
  strokeCtrlOnoutlineHover: { f2Token: 'colorNeutralStroke1' },
  strokeCtrlOnoutlinePressed: { f2Token: 'colorNeutralStroke1' },
  strokeCtrlDividerOnbrand: { f2Token: 'colorNeutralStrokeOnBrand' },
  strokeCtrlDividerOnsubtle: { rawValue: 'transparent' },
  strokeCtrlDividerOnoutline: { f2Token: 'colorNeutralStroke1' },
  strokewidthCtrlOutlineSelected: { f2Token: 'strokeWidthThicker' },
  foregroundCtrlNeutralSecondaryRest: { f2Token: 'colorNeutralForeground2' },
  foregroundCtrlNeutralSecondaryHover: { f2Token: 'colorNeutralForeground2Hover' },
  foregroundCtrlNeutralSecondaryPressed: { f2Token: 'colorNeutralForeground2Pressed' },
};
