import './version';
export {
  // These should be removed and only be exported from Autofill
  // Once the pickers folder is moved. This should be very temporary
  Autofill as FabricAutofill,
  IAutofillProps as FabricAutofillProps,
  IAutofill as IFabricAutofill,
  IAutofillState as IFabricAutofillState,
  // Deprecated, will be removed in 8
  // BaseAutoFill,
  // IPersonaWithMenu,
  // IPeoplePickerItemWithMenuProps,
  // IBaseAutoFillProps,
  // IBaseAutoFill,
  BasePeoplePicker,
  BasePicker,
  BasePickerListBelow,
  CompactPeoplePickerBase,
  ListPeoplePickerBase,
  NormalPeoplePickerBase,
  PeoplePickerItemBase,
  PeoplePickerItemSuggestionBase,
  TagItemBase,
  TagItemSuggestionBase,
  TagPickerBase,
  SuggestionActionType,
  Suggestions,
  SuggestionsController,
  SuggestionsItem,
  IBasePickerState,
  IBasePickerStyleProps,
  IBasePickerStyles,
  IBasePickerSuggestionsProps,
  IPeoplePickerItemSelectedProps,
  IPeoplePickerItemSelectedStyleProps,
  IPeoplePickerItemSelectedStyles,
  IPeoplePickerItemSelectedSubComponentStyles,
  IPeoplePickerItemSharedProps,
  IPeoplePickerItemSuggestionProps,
  IPeoplePickerItemSuggestionStyleProps,
  IPeoplePickerItemSuggestionStyles,
  ISuggestionsItemStyleProps,
  ISuggestionsItemStyles,
  ISuggestionsState,
  ISuggestionsStyleProps,
  ISuggestionsStyles,
  ISuggestionsSubComponentStyles,
  ITagItemStyleProps,
  ITagItemStyles,
  ITagItemSuggestionProps,
  ITagItemSuggestionStyleProps,
  ITagItemSuggestionStyles,
  PeoplePickerItemSuggestion,
  TagItemSuggestion,
  ValidationState,
  IPickerAriaIds,
  createGenericItem,
  CompactPeoplePicker,
  TagItem,
  TagPicker,
  IInputProps,
  IPeoplePickerProps,
  IPickerItem,
  IPickerItemProps,
  IBasePicker,
  IBasePickerProps,
  IGenericItem,
  ISuggestionItemProps,
  ISuggestionModel,
  ISuggestions,
  ISuggestionsItem,
  ISuggestionsProps,
  ITag,
  ITagItemProps,
  ITagPickerProps,
  PeoplePickerItem,
  ListPeoplePicker,
  MemberListPeoplePicker,
  NormalPeoplePicker,
} from '@fluentui/react/lib/Pickers';
