import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

import { series } from 'just-scripts';

import { apiExtractor } from './api-extractor';
import { getTsPathAliasesConfigUsedOnlyForDx } from './utils';

export function generateApi() {
  console.log('cwd', cwd);
  return series(generateTypeDeclarations, apiExtractor, readTempFile);
}

function generateTypeDeclarations() {
  const { isUsingPathAliasesForDx, tsConfigFileForCompilation } = getTsPathAliasesConfigUsedOnlyForDx();
  const cmd = [
    'tsc',
    `-p ./${tsConfigFileForCompilation}`,
    '--emitDeclarationOnly',
    isUsingPathAliasesForDx ? '--baseUrl .' : null,
  ]
    .filter(Boolean)
    .join(' ');

  return execSync(cmd, { stdio: 'inherit' });
}

function readTempFile() {
  console.log('READING TEMP FILE GENERATED BY API EXTRACTOR FOR COMPARISON');
  const cwd = process.cwd();
  const tempFile = path.join(cwd, 'temp', 'react-theme.api.md');
  const tempFileContent = fs.readFileSync(tempFile, 'utf8');
  console.log('temp file', tempFileContent);
}
