// eslint-disable-next-line no-restricted-imports
import { tokens } from '@fluentui/tokens';

export const ctrlFabBackgroundRest = `var(${ctrlFabBackgroundRestRaw}, ${tokens.colorNeutralBackground1})`;
export const ctrlFabBackgroundHover = `var(${ctrlFabBackgroundHoverRaw}, ${tokens.colorNeutralBackground1Hover})`;
export const ctrlFabBackgroundPressed = `var(${ctrlFabBackgroundPressedRaw}, ${tokens.colorNeutralBackground1Pressed})`;
export const ctrlFabBackgroundDisabled = `var(${ctrlFabBackgroundDisabledRaw}, ${tokens.colorNeutralBackgroundDisabled})`;
export const ctrlFabCornerRest = `var(${ctrlFabCornerRestRaw}, var(${cornerCircularRaw}, ${circularRaw}))`;
export const ctrlFabShadowRestKeyX = `var(${ctrlFabShadowRestKeyXRaw})`;
export const ctrlFabShadowRestKeyY = `var(${ctrlFabShadowRestKeyYRaw})`;
export const ctrlFabShadowRestKeyBlur = `var(${ctrlFabShadowRestKeyBlurRaw})`;
export const ctrlFabShadowRestKeyColor = `var(${ctrlFabShadowRestKeyColorRaw})`;
export const ctrlFabShadowRestAmbientX = `var(${ctrlFabShadowRestAmbientXRaw})`;
export const ctrlFabShadowRestAmbientY = `var(${ctrlFabShadowRestAmbientYRaw})`;
export const ctrlFabShadowRestAmbientBlur = `var(${ctrlFabShadowRestAmbientBlurRaw})`;
export const ctrlFabShadowRestAmbientColor = `var(${ctrlFabShadowRestAmbientColorRaw})`;
export const ctrlFabShadowHoverKeyX = `var(${ctrlFabShadowHoverKeyXRaw}, ${shadowFlyoutKeyXRaw})`;
export const ctrlFabShadowHoverKeyY = `var(${ctrlFabShadowHoverKeyYRaw}, ${shadowFlyoutKeyYRaw})`;
export const ctrlFabShadowHoverKeyBlur = `var(${ctrlFabShadowHoverKeyBlurRaw}, ${shadowFlyoutKeyBlurRaw})`;
export const ctrlFabShadowHoverKeyColor = `var(${ctrlFabShadowHoverKeyColorRaw}, ${shadowFlyoutKeyColorRaw})`;
export const ctrlFabShadowPressedKeyX = `var(${ctrlFabShadowPressedKeyXRaw})`;
export const ctrlFabShadowPressedKeyY = `var(${ctrlFabShadowPressedKeyYRaw})`;
export const ctrlFabShadowPressedKeyBlur = `var(${ctrlFabShadowPressedKeyBlurRaw})`;
export const ctrlFabShadowPressedKeyColor = `var(${ctrlFabShadowPressedKeyColorRaw})`;
export const ctrlFabShadowDisabledKeyX = `var(${ctrlFabShadowDisabledKeyXRaw}, ${ctrlFabShadowPressedKeyXRaw})`;
export const ctrlFabShadowDisabledKeyY = `var(${ctrlFabShadowDisabledKeyYRaw}, ${ctrlFabShadowPressedKeyYRaw})`;
export const ctrlFabShadowDisabledKeyBlur = `var(${ctrlFabShadowDisabledKeyBlurRaw}, ${ctrlFabShadowPressedKeyBlurRaw})`;
export const ctrlFabShadowDisabledKeyColor = `var(${ctrlFabShadowDisabledKeyColorRaw}, ${ctrlFabShadowPressedKeyColorRaw})`;
export const ctrlFabCornerHover = `var(${ctrlFabCornerHoverRaw}, var(${cornerCircularRaw}, ${circularRaw}))`;
export const ctrlFabCornerPressed = `var(${ctrlFabCornerPressedRaw}, var(${cornerCircularRaw}, ${circularRaw}))`;
