import { DEFINITION_LOOKUP_TABLE, RULE_CLASSNAME_INDEX, RTL_PREFIX } from '@fluentui/make-styles';

export function print(val: string) {
  const regexParts: string[] = [];
  const regex = lookupRegex();
  let result: RegExpExecArray | null = null;
  while ((result = regex.exec(val))) {
    const [name] = result;
    const [definitions] = DEFINITION_LOOKUP_TABLE[name];
    /**
     * Collects all classNames present in a definition and adds it as part of a regular expression
     * @example
     * rules = ["r?f16th3vw", "r?frdkuqy0", "r?fat0sn40", "r?fjseox00"]
     */
    const rules = Object.keys(definitions).map(key => `${definitions[key][RULE_CLASSNAME_INDEX]}`);
    regexParts.push(name, ...rules);
  }
  return JSON.stringify(val.replace(new RegExp(`${RTL_PREFIX}?(${regexParts.join('|')})`, 'g'), '').trim());
}

export function test(val: unknown) {
  if (typeof val === 'string') {
    return lookupRegex().test(val);
  }
  return false;
}

/**
 * lookupRegex returns all classNames definitions
 * that were generated by make-styles in a single regex declaration
 * @example
 * const useStyles = makeStyles({display: { display: 'none' } });
 *
 * lookupRegex() // /(__1qdh4ig)/g
 *
 */
function lookupRegex() {
  return new RegExp(`${Object.keys(DEFINITION_LOOKUP_TABLE).join('|')}`, 'g');
}
