export {
  AnimationDirection,
  Calendar,
  DateRangeType,
  DayOfWeek,
  FirstWeekOfYear,
  defaultCalendarNavigationIcons,
  defaultCalendarStrings,
  // eslint-disable-next-line etc/no-deprecated
  defaultDayPickerStrings,
} from '@fluentui/react/lib/Calendar';
export type {
  ICalendar,
  ICalendarDay,
  ICalendarDayGrid,
  ICalendarDayGridProps,
  ICalendarDayGridStyleProps,
  ICalendarDayGridStyles,
  ICalendarDayProps,
  ICalendarDayStyleProps,
  ICalendarDayStyles,
  // eslint-disable-next-line etc/no-deprecated
  ICalendarFormatDateCallbacks,
  // eslint-disable-next-line etc/no-deprecated
  ICalendarIconStrings,
  ICalendarMonth,
  ICalendarMonthProps,
  ICalendarMonthStyleProps,
  ICalendarMonthStyles,
  ICalendarNavigationIcons,
  ICalendarPickerStyleProps,
  ICalendarPickerStyles,
  ICalendarProps,
  ICalendarStrings,
  ICalendarStyleProps,
  ICalendarStyles,
  ICalendarYear,
  ICalendarYearHeaderProps,
  ICalendarYearProps,
  ICalendarYearRange,
  ICalendarYearRangeToString,
  ICalendarYearStrings,
  ICalendarYearStyleProps,
  ICalendarYearStyles,
  IDateFormatting,
} from '@fluentui/react/lib/Calendar';
