parameters:
  - name: checkForModifiedFiles
    type: boolean
    default: true

steps:
  - script: |
      yarn check:modified-files
    condition: ${{ parameters.checkForModifiedFiles }}
    displayName: 'check: modified files'
