steps:
  - template: tools.yml

  - task: Bash@3
    inputs:
      filePath: yarn-ci.sh
    displayName: yarn

  - script: |
      yarn bundle --no-cache $(sinceArg)
    displayName: bundle

  ## This runs regardless of scope, the app will adapt to the scope as well
  - script: |
      yarn workspace @uifabric/pr-deploy-site generate:site
    displayName: generate PR Deploy Site

  - task: AzureUpload@2
    displayName: Upload PR deploy site
    inputs:
      azureSubscription: $(azureSubscription)
      BlobPrefix: $(deployBasePath)
      ContainerName: '$web'
      SourcePath: 'apps/pr-deploy-site/dist'
      storage: $(azureStorage)

  - task: GithubPRStatus@0
    displayName: 'Update PR deploy site github status'
    inputs:
      githubOwner: microsoft
      githubRepo: fluentui
      githubContext: 'Pull request demo site'
      githubDescription: 'Click "Details" to go to the deployed demo site for this pull request'
      # This MUST have a trailing slash, or the links to PR deploy site assets won't work
      githubTargetLink: $(deployUrl)/

  - template: cleanup.yml
