parameters:
  - name: version
    type: string
    default: 8

steps:
  - task: AzureCLI@2
    displayName: 'Copy website drop to Azure'
    inputs:
      azureSubscription: 'Azure - fabricweb storage - NEW'
      scriptType: 'bash'
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload-batch \
        --destination 'fabric-website' \
        --source $(System.DefaultWorkingDirectory)/apps/public-docsite/dist \
        --account-name fabricweb \
        --destination-path v$(version)/$(Build.BuildNumber)/ \
        --auth-mode login \
        --overwrite

  - task: AzureFileCopy@6
    displayName: 'Update dogfood manifest in Azure blob'
    inputs:
      SourcePath: '$(System.DefaultWorkingDirectory)/site-manifests/v$(version)-df.js'
      azureSubscription: 'Azure - fabricweb storage - NEW'
      Destination: AzureBlob
      storage: fabricweb
      ContainerName: 'fabric-website'
      BlobPrefix: manifests/

  # - task: AzureFileCopy@6
  #   displayName: 'Update prod manifest in Azure blob'
  #   inputs:
  #     SourcePath: '$(System.DefaultWorkingDirectory)/site-manifests/v$(version)-prod.js'
  #     azureSubscription: 'Azure - fabricweb storage - NEW'
  #     Destination: AzureBlob
  #     storage: fabricweb
  #     ContainerName: 'fabric-website'
  #     BlobPrefix: manifests/
