# Install tools and dependencies and set shared configuration
parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

steps:
  - task: UseNode@1
    displayName: Install Node.js
    retryCountOnTaskFailure: 1
    inputs:
      # 👉 NOTE:
      # - we can use only versions that ship with container, otherwise we will run into nodejs installation issues.
      # - as 1es bumps those versions within container automatically we need to use `<major>.x` to not run into issues once they bump the versions.
      # - `checkLatest: true` is required because some dependencies (e.g. @microsoft/fast-build) require node >=22.18.0,
      #   while the 1ES container may still ship an older 22.x (e.g. 22.14.0). This forces the task to install the latest 22.x.
      # https://github.com/actions/runner-images/blob/ubuntu20/20230924.1/images/linux/Ubuntu2004-Readme.md#nodejs
      version: 22.x
      checkLatest: true

  - script: |
      echo "nodejs:" && node -v
      echo "yarn:" && yarn -v
      echo "npm:" && npm -v
    displayName: Print Node.js and package manager versions

  # Log all the environment variables since it can be useful for debugging.
  # (This happens automatically for the built-in agents, but not for custom agents.)
  - script: |
      printenv | sort
      echo number of CPUs "$(getconf _NPROCESSORS_ONLN)"
      set -x
      git --no-pager config list
      npm config list
      yarn config --no-defaults
    displayName: Log environment

  - script: |
      git config user.name "OGX bot"
      git config user.email "257645319+office-ogx-auth-helper[bot]@users.noreply.github.com"
    displayName: Configure git user (used by beachball)

  # Do NOT run `corepack enable` - it's not needed since yarn is checked into the repo, and
  # it causes a network request attempting to download yarn, which is not allowed.

  - script: yarn install --immutable
    displayName: yarn install
