import * as React from 'react';
import Screener from 'screener-storybook/src/screener';
import { storiesOf } from '@storybook/react';
import { TextField } from '@fluentui/react';
import { within, userEvent } from '@storybook/testing-library';

storiesOf('TextField', module)
  .addDecorator(story => (
    <Screener
      steps={new Screener.Steps()
        .snapshot('default')
        .click('.ms-TextField-field')
        .snapshot('click')
        .end()}
    >
      {story()}
    </Screener>
  ))
  .add('Placeholder 1	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 2	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 3	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 4	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 5	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 6	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 7	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 8	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 9	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 10	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 11	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 12	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 13	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 14	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 15	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 16	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 17	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 18	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 19	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 20	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 21	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 22	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 23	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 24	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 25	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 26	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 27	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 28	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 29	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 30	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 31	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 32	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 33	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 34	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 35	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 36	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 37	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 38	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 39	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 40	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 41	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 42	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 43	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 44	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 45	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 46	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 47	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 48	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 49	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 50	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 51	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 52	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 53	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 54	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 55	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 56	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 57	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 58	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 59	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 60	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 61	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 62	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 63	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 64	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 65	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 66	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 67	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 68	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 69	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 70	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 71	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 72	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 73	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 74	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 75	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 76	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 77	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 78	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 79	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 80	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 81	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 82	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 83	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 84	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 85	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 86	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 87	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 88	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 89	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 90	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 91	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 92	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 93	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 94	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 95	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 96	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 97	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 98	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 99	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 100	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 101	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 102	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 103	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 104	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 105	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 106	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 107	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 108	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 109	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 110	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 111	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 112	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 113	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 114	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 115	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 116	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 117	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 118	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 119	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 120	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 121	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 122	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 123	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 124	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 125	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 126	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 127	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 128	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 129	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 130	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 131	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 132	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 133	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 134	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 135	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 136	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 137	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 138	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 139	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 140	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 141	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 142	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 143	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 144	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 145	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 146	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 147	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 148	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 149	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 150	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 151	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 152	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 153	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 154	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 155	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 156	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 157	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 158	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 159	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 160	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 161	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 162	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 163	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 164	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 165	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 166	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 167	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 168	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 169	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 170	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 171	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 172	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 173	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 174	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 175	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 176	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 177	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 178	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 179	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 180	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 181	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 182	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 183	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 184	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 185	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 186	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 187	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 188	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 189	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 190	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 191	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 192	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 193	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 194	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 195	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 196	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 197	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 198	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 199	', () => <TextField label="Standard" placeholder="Placeholder" />)
  .add('Placeholder 200	', () => <TextField label="Standard" placeholder="Placeholder" />);

// export default {
//   component: TextField,
// };

// const TextFieldTemplate = () => <TextField label="Standard" placeholder="Placeholder" />;

// export const TextFieldPlaceholder1 = {
//   render: TextFieldTemplate,
// };

// export const TextFieldPlaceholderClicked1 = {
//   render: TextFieldTemplate,
//   play: async ({ canvasElement }) => {
//     const canvas = within(canvasElement);
//     const input = canvas.getByRole('input');
//     await userEvent.click(input);
//   },
// };
