// tslint:disable-next-line:max-line-length
export const positiveChangeState = `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTEiIGhlaWdodD0iOSIgdmlld0JveD0iMCAwIDExIDkiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik0wIDlMNS4yIDBMMTAuNCA5SDBaIiBmaWxsPSIjNkJCNzAwIi8+Cjwvc3ZnPgo=`;
