approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - ericthompson
  - Jahnp
  - battletoilet
  - wdo3650
  - mikewheaton
  - dzearing
  - cliffkoh
  - aditima
  - yiminwu
  name: pullapprove
  required: 1
