enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d
# Add exceptions to npmMinimalAgeGate here (they should have feed quarantine exceptions)
npmPreapprovedPackages:
  - beachball
  - p-graph

yarnPath: .yarn/releases/yarn-4.17.1.cjs
