# Yarn will delete the comments on automatic file updates.
# Please bring them back!

# Scripts are disabled for all packages.
# To enable, add the package to dependenciesMeta in package.json.
enableScripts: false

nodeLinker: node-modules

# Only install packages >= 7 days old to match internal quarantine policy.
npmMinimalAgeGate: 7d

# Packages listed here must:
# 1. Be on the quarantine-exempt list for the internal feed
# 2. Only depend on < 7d old versions of other quarantine-exempt packages
npmPreapprovedPackages:
  - '@microsoft/esrp-npm-release'
  - beachball
  - p-graph

plugins:
  - checksum: 8d8252c376e41a67ca509b2778f3fb92164aa91828459ae8a6aa0e13f1b6f9843586d0983ba9a200f6d813d37efc171474c8dbc85b0dff01df56c0d476c238ce
    path: .yarn/plugins/@rnx-kit/yarn-plugin-ignore.cjs
    spec: 'https://raw.githubusercontent.com/microsoft/rnx-kit/main/incubator/yarn-plugin-ignore/dist/yarn-plugin-ignore.cjs'

yarnPath: .yarn/releases/yarn-4.18.0.cjs
