# Yarn will delete the comments on automatic file updates.
# Please bring them back!

# Scripts are disabled for all packages.
# To enable, add the package to dependenciesMeta in package.json.
enableScripts: false

nodeLinker: node-modules

# Only install packages >= 7 days old to match internal quarantine policy.
npmMinimalAgeGate: 7d

# Packages listed here must:
# 1. Be on the quarantine-exempt list for the internal feed
# 2. Only depend on < 7d old versions of other quarantine-exempt packages
npmPreapprovedPackages:
  - '@microsoft/esrp-npm-release'
  - beachball
  - p-graph

yarnPath: .yarn/releases/yarn-4.17.1.cjs
