pr: none
trigger: none

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: true

# Customize build number to include tools experimental prefix
# Example: tools_experimental_20201022.1
name: "tools_experimental_${{ iif(parameters.dryRun, 'dryrun_', '') }}$(Date:yyyyMMdd)$(Rev:.r)"

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: experimental
    label: tools experimental
    beachballConfig: scripts/beachball/src/release-tools.config.js
    nxScope: -p 'tag:tools,!tag:npm:private,!tag:v8' --exclude 'apps/**'
    # Bumps all tools packages to x.x.x-experimental.<feature>.<date>-<hash> version.
    # x.x.x is each package's own current version.
    bumpUnofficialVersionsScript: |
      DATE=$(date +"%Y%m%d")
      HASH=$(git rev-parse --short HEAD)
      VERSION_SUFFIX="experimental.$(experimentalFeatureName).${DATE}-${HASH}"

      echo "Version suffix: ${VERSION_SUFFIX}"

      yarn nx g @fluentui/workspace-plugin:version-bump --all --scope tools --versionSuffix "${VERSION_SUFFIX}"
    dryRun: ${{ parameters.dryRun }}
