pr: none
trigger: none

# Example: v9_20201022.1
name: "v9_${{ iif(parameters.dryRun, 'dryrun_', '') }}$(Date:yyyyMMdd)$(Rev:.r)"

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - template: /.devops/templates/variables/variables.yml@self
  # Used in the beachball config to trigger logging packages which need prerelease tags
  - name: RELEASE_VNEXT_OFFICIAL
    value: 'true'
    readonly: true

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: official
    label: react-components
    beachballConfig: scripts/beachball/src/release-vNext.config.js
    nxScope: -p tag:vNext --exclude 'tag:tools,tag:type:stories,apps/**'
    dryRun: ${{ parameters.dryRun }}
