pr: none
trigger: none

# Customize build number to include major version
# Example: v8_20201022.1
name: 'v8_$(Date:yyyyMMdd)$(Rev:.r)'

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - group: 'Github and NPM secrets'
  - template: .devops/templates/variables.yml
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows # We need windows because compliance task only run on windows.
    stages:
      - stage: main
        jobs:
          - job: Release
            pool:
              name: '1ES-Host-Ubuntu'
              image: '1ES-PT-Ubuntu-20.04'
              os: linux
            timeoutInMinutes: 90
            workspace:
              clean: all
            templateContext:
              outputParentDirectory: $(System.DefaultWorkingDirectory)
              outputs:
                - output: pipelineArtifact
                  targetPath: $(System.DefaultWorkingDirectory)/homepage
                  artifactName: homepage.htm
                  displayName: homepage.htm
                - output: pipelineArtifact
                  targetPath: $(System.DefaultWorkingDirectory)/site-manifests
                  artifactName: fabric-website-manifests
                  displayName: fabric-website-manifests
                - output: pipelineArtifact
                  targetPath: $(System.DefaultWorkingDirectory)/apps/public-docsite/dist
                  artifactName: fabric-website
                  displayName: fabric-website

            steps:
              - template: .devops/templates/tools.yml@self
                parameters:
                  dryRun: ${{ parameters.dryRun }}

              - script: |
                  yarn generate-version-files
                displayName: Generate version files

              - script: |
                  FLUENT_PROD_BUILD=true yarn nx run-many -t build -p tag:v8 --exclude tag:vNext,tag:tools,ssr-tests,vr-tests,perf-test --nxBail
                displayName: build

              - script: |
                  FLUENT_PROD_BUILD=true yarn nx run-many -t test -p tag:v8 --exclude tag:vNext,tag:tools,ssr-tests,vr-tests,perf-test --nxBail
                displayName: test

              - script: |
                  FLUENT_PROD_BUILD=true yarn nx run-many -t lint -p tag:v8 --exclude tag:vNext,tag:tools,ssr-tests,vr-tests,perf-test --nxBail
                displayName: lint

              - script: |
                  FLUENT_PROD_BUILD=true yarn nx run-many -t bundle -p tag:v8 --exclude tag:vNext,tag:tools,ssr-tests,vr-tests,perf-test --nxBail
                displayName: bundle

              - script: |
                  FLUENT_PROD_BUILD=true yarn nx run-many -t verify-packaging -p tag:v8 --exclude tag:vNext,tag:tools,ssr-tests,vr-tests,perf-test --nxBail
                displayName: verify packaged assets

              - template: .devops/templates/run-with-token.yml@self
                parameters:
                  steps:
                    - script: |
                        yarn beachball publish --config scripts/beachball/src/release-v8.config.js --message 'release: applying package updates - react v8'
                        git reset --hard origin/master
                      condition: and(succeeded(), not(${{ parameters.dryRun }}))
                      env:
                        BEACHBALL_GIT_TOKEN: $(createToken.GITHUB_APP_TOKEN)
                        BEACHBALL_NPM_TOKEN: $(npmToken)
                      displayName: Publish changes and bump versions

                    # create-site-manifests is a script defined in @fluentui/public-docsite-setup.
                    # It generates manifest files used to load the current version on developer.microsoft.com/fluentui.
                    - script: |
                        yarn create-site-manifests ./packages/react
                      displayName: 'Generate website manifests'

                    # Generate the homepage.htm file used to load developer.microsoft.com/fluentui. Note that the
                    # generated file must be manually checked in to an internal repo, it's just generated as a build
                    # artifact for convenience and tracking.
                    - script: |
                        node ./packages/public-docsite-setup/scripts/generateHomepage ./homepage
                      displayName: 'Generate homepage.htm'

                    # Since v8 updates should be very rare, it's probably not necessary to update the website.
                    # If this is re-enabled, the Azure service connection will need to be re-created.
                    # - ${{ if eq(parameters.dryRun, false) }}:
                    #     - template: .devops/templates/publish-website.yml@self

                    # Run this near the end because it's more likely to fail than the artifact upload tasks, and its
                    # failure doesn't need to block anything else
                    - script: |
                        node -r ./scripts/ts-node/src/register ./scripts/update-release-notes/src/index.ts --apply --debug
                      condition: not(${{ parameters.dryRun }})
                      displayName: 'Update github release notes'
                      env:
                        TOKEN: $(createToken.GITHUB_APP_TOKEN)
