pr: none
trigger: none

# Customize build number to include package prefix
# Example: headless_20201022.1
name: 'headless_$(Date:yyyyMMdd)$(Rev:.r)'

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: official
    label: react-headless
    beachballConfig: scripts/beachball/src/release-headless.config.js
    nxScope: -p 'tag:react-headless,!tag:npm:private,!tag:type:stories' --exclude 'apps/**'
    dryRun: ${{ parameters.dryRun }}
