# ‼️ Due to lack of recent runs, an ADO pipeline was NOT created for this file in the August 2026 project move,
# but the file is preserved for reference.

pr: none
trigger: none

name: 'v8 hotfix ${{ parameters.targetNpmVersion }} ($(Rev:r))'

parameters:
  - name: targetNpmVersion
    displayName: Publish this version to npm
    type: string
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: skipComponentGovernanceDetection
    value: true
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows # We need windows because compliance task only run on windows.
    settings:
      networkIsolationPolicy: AzureActiveDirectory,AzureKeyVault,AzureStorage,GitHub
    stages:
      - stage: build
        jobs:
          - job: build
            displayName: Build and pack
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux
            workspace:
              clean: all
            variables:
              - name: pkgArtifactPath
                value: $(Build.StagingDirectory)/packed
                readonly: true
            templateContext:
              outputParentDirectory: $(Build.StagingDirectory)
              outputs:
                - output: pipelineArtifact
                  artifactName: packed
                  path: $(pkgArtifactPath)

            steps:
              - template: /.devops/templates/steps/tools.yml@self
                parameters:
                  dryRun: ${{ parameters.dryRun }}

              - script: |
                  if ! yarn semver "$TARGET_NPM_VERSION" >/dev/null; then
                    echo "##vso[task.logissue type=error]Invalid version specified: $TARGET_NPM_VERSION"
                    exit 1
                  fi
                displayName: 'Check targetNpmVersion is valid semver'
                env:
                  TARGET_NPM_VERSION: ${{ parameters.targetNpmVersion }}

              - script: |
                  npm version "$TARGET_NPM_VERSION"
                workingDirectory: 'packages/react'
                displayName: 'Manually set package version'
                env:
                  TARGET_NPM_VERSION: ${{ parameters.targetNpmVersion }}

              - script: |
                  yarn nx run react:build --production
                displayName: yarn build to FUIR (Create production build)

              - script: yarn workspace @fluentui/react bundle --production
                displayName: yarn bundle FUIR

              - script: |
                  npm pack --pack-destination '$(pkgArtifactPath)'
                displayName: 'Create tarball'
                workingDirectory: 'packages/react'

      - stage: publish
        displayName: Publish
        dependsOn: build
        condition: and(succeeded(), not(${{ parameters.dryRun }}))
        jobs:
          - job: publish
            displayName: Publish npm package
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux
            variables:
              pkgArtifactPath: $(Build.StagingDirectory)/packed
            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
                - input: pipelineArtifact
                  artifactName: packed
                  targetPath: $(pkgArtifactPath)

            steps:
              # Publishing a single package can use the official EsrpRelease task since order doesn't matter
              - task: EsrpRelease@12
                displayName: Publish to npm
                inputs:
                  connectedservicename: $(esrpReleaseAzureSubscription)
                  usemanagedidentity: false
                  keyvaultname: $(esrpReleaseKeyVaultName)
                  authcertname: $(esrpSecretNameAuthCert)
                  signcertname: $(esrpSecretNameSignCert)
                  clientid: $(esrpReleaseClientId)
                  domaintenantid: $(esrpReleaseTenantId)
                  contenttype: npm
                  productstate: $(npmDistTag)
                  folderlocation: $(pkgArtifactPath)
                  waitforreleasecompletion: true
                  owners: $(esrpReleaseUser)
                  approvers: $(esrpReleaseApprovers)
