pr: none
trigger: none

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

# Customize build number to include major version
# Example: v9_20201022.1
name: 'v9_nightly_$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: tags
    value: production,externalfacing

schedules:
  # Triggers the nightly release
  # minute 0, hour 4 in UTC (5am in UTC+1), any day of month, any month, days 1-5 of week (M-F)
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#supported-cron-syntax
  - cron: '0 4 * * 1-5'
    displayName: 'Daily release (M-F at 5am UTC+1)'
    branches:
      include:
        - master

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: nightly
    label: v9 nightly
    beachballConfig: scripts/beachball/src/release-vNext.config.js
    nxScope: -p 'tag:vNext' --exclude 'tag:npm:private,tag:tools,tag:charting'
    # release version name will follow a 0.0.0-nightly-{year}{month}{day}-{hour}{minute} format.
    bumpUnofficialVersionsScript: |
      DATE=$(date +"%Y%m%d-%H%M")
      yarn nx g @fluentui/workspace-plugin:version-bump --all --bumpType nightly --prereleaseTag "nightly-${DATE}"
    dryRun: ${{ parameters.dryRun }}
