pr: none

trigger: none

name: '$(targetNpmVersion) ($(Rev:r))'

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - template: .devops/templates/variables.yml
  - name: skipComponentGovernanceDetection
    value: true
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows # We need windows because compliance task only run on windows.
    stages:
      - stage: main
        jobs:
          - job: Release
            dependsOn: Compliance
            pool:
              name: '1ES-Host-Ubuntu'
              image: '1ES-PT-Ubuntu-20.04'
              os: linux
            workspace:
              clean: all
            steps:
              - script: |
                  if [[ -z "$(targetNpmVersion)" ]]; then
                    echo "##vso[task.logissue type=error]targetNpmVersion is not specified"
                    exit 1
                  fi
                displayName: 'Checking for targetNpmVersion variable'

              - template: .devops/templates/tools.yml@self
                parameters:
                  dryRun: ${{ parameters.dryRun }}

              - script: |
                  if ! yarn semver '$(targetNpmVersion)' >/dev/null; then
                    echo "##vso[task.logissue type=error]Invalid version specified: $(targetNpmVersion)"
                    exit 1
                  fi
                displayName: 'Check targetNpmVersion is valid semver'

              - script: |
                  npm version $(targetNpmVersion)
                workingDirectory: 'packages/react'
                displayName: 'Manually set package version'

              - script: |
                  yarn nx run react:build --production
                displayName: yarn build to FUIR (Create production build)

              - script: yarn workspace @fluentui/react bundle --production
                displayName: yarn bundle FUIR

              - script: |
                  npm pack
                displayName: 'Create tarball'
                workingDirectory: 'packages/react'

              - script: |
                  npm publish packages/react/react-$(targetNpmVersion).tgz --tag hf8 --//registry.npmjs.org/:_authToken=$(npmToken)
                displayName: Publish new version
                condition: not(${{ parameters.dryRun }})
