pr: none
trigger: none

# Customize build number to include major version
# Example: v9_20201022.1
name: 'v9_$(Date:yyyyMMdd)$(Rev:.r)'

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: official
    label: react-components
    beachballConfig: scripts/beachball/src/release-vNext.config.js
    nxScope: -p tag:vNext --exclude 'tag:tools,tag:type:stories,apps/**'
    dryRun: ${{ parameters.dryRun }}
    # TODO fix post-tagging
    # postPushSteps:
    # - script: |
    #     node -r ./scripts/ts-node/src/register scripts/executors/src/tag-react-components.ts --token $(npmToken)
    #   displayName: Tag prelease packages with prerelease tag
    #   continueOnError: true
    #   condition: not(${{ parameters.dryRun }})
