pr: none
trigger: none

# Customize build number to include major version
# Example: tools_20201022.1
name: "tools_${{ iif(parameters.dryRun, 'dryrun_', '') }}$(Date:yyyyMMdd)$(Rev:.r)"

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: official
    label: tools
    beachballConfig: scripts/beachball/src/release-tools.config.js
    nxScope: -p 'tag:tools,!tag:npm:private,!tag:v8' --exclude 'apps/**'
    dryRun: ${{ parameters.dryRun }}
