pr: none
trigger: none

parameters:
  - name: dryRun
    displayName: Dry Run Mode
    type: boolean
    default: true

name: "v9_experimental_${{ iif(parameters.dryRun, 'dryrun_', '') }}$(Date:yyyyMMdd)$(Rev:.r)"

variables:
  - template: /.devops/templates/variables/variables.yml@self
  - name: tags
    value: production,externalfacing

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: /.devops/templates/release.yml@self
  parameters:
    releaseType: experimental
    label: v9 experimental
    beachballConfig: scripts/beachball/src/release-vNext.config.js
    nxScope: -p 'tag:vNext' --exclude 'tag:npm:private,tag:tools,tag:charting,tag:react-headless'
    # Bumps all v9 packages to a x.x.x-experimental.<feature>.<date>-<hash> version.
    # x.x.x is derived from the current version @fluentui/react-components package.json.
    bumpUnofficialVersionsScript: |
      BASE_VERSION=$(node -p "require('./packages/react-components/react-components/package.json').version")
      DATE=$(date +"%Y%m%d")
      HASH=$(git rev-parse --short HEAD)
      NEW_VERSION="${BASE_VERSION}-experimental.$(experimentalFeatureName).${DATE}-${HASH}"

      echo "Target version: ${NEW_VERSION}"

      yarn nx g @fluentui/workspace-plugin:version-bump --all --explicitVersion "${NEW_VERSION}"
    dryRun: ${{ parameters.dryRun }}
