# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - web-components-v3

variables:
  skipComponentGovernanceDetection: true

pool: '1ES-Host-Ubuntu'

jobs:
  # TODO: When web-components-v3 branch is merged with master, this file can be deleted and everything below this comment
  # can be moved to azure-pipelines.vrt-baseline.yml. The corresponding pipeline on ADO can be deleted as well.
  - job: VRToolUpdateBaseline_WebComponents
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - template: .devops/templates/runpublishvrscreenshot.yml
        parameters:
          fluentVersion: webcomponents
          vrTestPackageName: '@fluentui/vr-tests-web-components'
          vrTestPackagePath: 'apps/vr-tests-web-components'

      - bash: node node_modules/vrscreenshotdiff/lib/index.js release --clientType "FluentUI-web-components" --buildId $(Build.BuildId)
        displayName: 'Run Screenshotdiff update baseline'
        env:
          API_URL: $(System.CollectionUri)
          API_TOKEN: $(fabric-public-pipeline-access-PAT)
          API_REPOSITORY: $(Build.Repository.Name)
          API_PROJECT: $(System.TeamProject)
          SCREENSHOT_ARTIFACT_FOLDER: vrscreenshotwebcomponents
          GITHUB_API_TOKEN: $(githubRepoStatusPAT)
          STORAGE_ACCOUNT_FLUENTUI: $(STORAGE-ACCOUNT-FLUENTUI)
          STORAGE_KEY_FLUENTUI: $(STORAGE-KEY-BLOB-FLUENTUI)
          BLOB_CONNECTION_STRING: $(BLOB-CONNECTION-STRING)
          VR_APPROVAL_CLIENT_SECRET: $(VR-APPROVAL-CLIENT-SECRET)
          VR_APPROVAL_HOST: $(VR_APPROVAL_HOST)
