// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.
// @ts-nocheck — generated output; slot/variant state is intentionally loosely typed for PoC.

'use client';

import { makeResetStyles, makeStyles, mergeClasses } from '@griffel/react';
import { tokens } from '@fluentui/react-theme';
import type { SlotClassNames } from '@fluentui/react-utilities';

export const dividerClassNames: SlotClassNames<Record<string, unknown>> = {
  root: 'fui-Divider',
  wrapper: 'fui-Divider__wrapper',
};

const useRootBaseClassName = makeResetStyles({
  alignItems: 'center',
  boxSizing: 'border-box',
  display: 'flex',
  flexDirection: 'row',
  flexGrow: 1,
  position: 'relative',
  fontFamily: tokens.fontFamilyBase,
  fontSize: tokens.fontSizeBase200,
  fontWeight: tokens.fontWeightRegular,
  lineHeight: tokens.lineHeightBase200,
  textAlign: 'center',
  '::after': {
    boxSizing: 'border-box',
    display: 'flex',
    flexGrow: 1,
  },
  '::before': {
    boxSizing: 'border-box',
    display: 'flex',
    flexGrow: 1,
  },
});

const useRootStyles = makeStyles({
  'orientation-horizontal': {
    width: '100%',
    '::after': {
      borderTopStyle: 'solid',
      borderTopWidth: tokens.strokeWidthThin,
      minWidth: '8px',
    },
    '::before': {
      borderTopStyle: 'solid',
      borderTopWidth: tokens.strokeWidthThin,
      minWidth: '8px',
    },
  },
  'orientation-vertical': {
    flexDirection: 'column',
    minHeight: '20px',
    '::after': {
      borderRightStyle: 'solid',
      borderRightWidth: tokens.strokeWidthThin,
      minHeight: '8px',
    },
    '::before': {
      borderRightStyle: 'solid',
      borderRightWidth: tokens.strokeWidthThin,
      minHeight: '8px',
    },
  },
  'alignContent-start': {
    '::after': {
      content: '""',
    },
  },
  'alignContent-center': {
    '::after': {
      content: '""',
    },
    '::before': {
      content: '""',
    },
  },
  'alignContent-end': {
    '::before': {
      content: '""',
    },
  },
  'appearance-default': {
    color: tokens.colorNeutralForeground2,
    '::after': {
      borderColor: tokens.colorNeutralStroke2,
    },
    '::before': {
      borderColor: tokens.colorNeutralStroke2,
    },
  },
  'appearance-brand': {
    color: tokens.colorBrandForeground1,
    '::after': {
      borderColor: tokens.colorBrandStroke1,
    },
    '::before': {
      borderColor: tokens.colorBrandStroke1,
    },
  },
  'appearance-subtle': {
    color: tokens.colorNeutralForeground3,
    '::after': {
      borderColor: tokens.colorNeutralStroke3,
    },
    '::before': {
      borderColor: tokens.colorNeutralStroke3,
    },
  },
  'appearance-strong': {
    color: tokens.colorNeutralForeground1,
    '::after': {
      borderColor: tokens.colorNeutralStroke1,
    },
    '::before': {
      borderColor: tokens.colorNeutralStroke1,
    },
  },
  'orientation-horizontal--alignContent-start': {
    textAlign: 'left',
    '::after': {
      marginLeft: '12px',
    },
    '::before': {
      content: '""',
      marginRight: '12px',
      maxWidth: '8px',
    },
  },
  'orientation-horizontal--alignContent-center': {
    textAlign: 'center',
    '::after': {
      marginLeft: '12px',
    },
    '::before': {
      marginRight: '12px',
    },
  },
  'orientation-horizontal--alignContent-end': {
    textAlign: 'right',
    '::after': {
      content: '""',
      marginLeft: '12px',
      maxWidth: '8px',
    },
    '::before': {
      marginRight: '12px',
    },
  },
  'orientation-vertical--alignContent-start': {
    '::after': {
      marginTop: '12px',
    },
    '::before': {
      content: '""',
      marginBottom: '12px',
      maxHeight: '8px',
    },
  },
  'orientation-vertical--alignContent-center': {
    '::after': {
      marginTop: '12px',
    },
    '::before': {
      marginBottom: '12px',
    },
  },
  'orientation-vertical--alignContent-end': {
    '::after': {
      content: '""',
      marginTop: '12px',
      maxHeight: '8px',
    },
    '::before': {
      marginBottom: '12px',
    },
  },
  'state-hasChildren-false': {
    '::after': {
      marginLeft: 0,
      marginTop: 0,
    },
    '::before': {
      marginBottom: 0,
      marginRight: 0,
    },
  },
  'orientation-horizontal--state-inset': {
    paddingLeft: '12px',
    paddingRight: '12px',
  },
  'orientation-vertical--state-inset': {
    marginTop: '12px',
    marginBottom: '12px',
  },
  'orientation-vertical--state-hasChildren': {
    minHeight: '84px',
  },
});

const useWrapperBaseClassName = makeResetStyles({});

const useWrapperStyles = makeStyles({});

export const useDividerStyles_unstable = (state: Record<string, any>): typeof state => {
  const rootBaseClassName = useRootBaseClassName();
  const rootStyles = useRootStyles();
  const wrapperBaseClassName = useWrapperBaseClassName();
  const wrapperStyles = useWrapperStyles();

  if (state.root) {
    state.root.className = mergeClasses(
      dividerClassNames.root,
      rootBaseClassName,
      state.orientation === 'horizontal' && rootStyles['orientation-horizontal'],
      state.orientation === 'vertical' && rootStyles['orientation-vertical'],
      state.alignContent === 'start' && rootStyles['alignContent-start'],
      state.alignContent === 'center' && rootStyles['alignContent-center'],
      state.alignContent === 'end' && rootStyles['alignContent-end'],
      state.appearance === 'default' && rootStyles['appearance-default'],
      state.appearance === 'brand' && rootStyles['appearance-brand'],
      state.appearance === 'subtle' && rootStyles['appearance-subtle'],
      state.appearance === 'strong' && rootStyles['appearance-strong'],
      state.orientation === 'horizontal' &&
        state.alignContent === 'start' &&
        rootStyles['orientation-horizontal--alignContent-start'],
      state.orientation === 'horizontal' &&
        state.alignContent === 'center' &&
        rootStyles['orientation-horizontal--alignContent-center'],
      state.orientation === 'horizontal' &&
        state.alignContent === 'end' &&
        rootStyles['orientation-horizontal--alignContent-end'],
      state.orientation === 'vertical' &&
        state.alignContent === 'start' &&
        rootStyles['orientation-vertical--alignContent-start'],
      state.orientation === 'vertical' &&
        state.alignContent === 'center' &&
        rootStyles['orientation-vertical--alignContent-center'],
      state.orientation === 'vertical' &&
        state.alignContent === 'end' &&
        rootStyles['orientation-vertical--alignContent-end'],
      !state.hasChildren && rootStyles['state-hasChildren-false'],
      state.orientation === 'horizontal' && Boolean(state.inset) && rootStyles['orientation-horizontal--state-inset'],
      state.orientation === 'vertical' && Boolean(state.inset) && rootStyles['orientation-vertical--state-inset'],
      state.orientation === 'vertical' &&
        Boolean(state.hasChildren) &&
        rootStyles['orientation-vertical--state-hasChildren'],
      state.root.className,
    );
  }

  if (state.wrapper) {
    state.wrapper.className = mergeClasses(dividerClassNames.wrapper, wrapperBaseClassName, state.wrapper.className);
  }

  return state;
};
