// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.

export type ButtonVariants = {
  appearance?: string;
  size?: string;
  shape?: string;
  iconPosition?: string;
  disabled?: boolean;
  iconOnly?: boolean;
  hasIcon?: boolean;
  hasChildren?: boolean;
};

export function getButtonClassNames(
  styles: Record<string, string>,
  variants: ButtonVariants = {},
  slot: string = 'root',
): string {
  const classes = [styles[slot === 'root' ? 'button' : `button__${slot}`]].filter(Boolean);
  if (variants.appearance) {
    classes.push(styles[`appearance-${variants.appearance}`] ?? styles[variants.appearance!]);
  }
  if (variants.size) {
    classes.push(styles[`size-${variants.size}`] ?? styles[variants.size!]);
  }
  if (variants.shape) {
    classes.push(styles[`shape-${variants.shape}`] ?? styles[variants.shape!]);
  }
  if (variants.iconPosition) {
    classes.push(styles[`iconPosition-${variants.iconPosition}`] ?? styles[variants.iconPosition!]);
  }
  return classes.filter(Boolean).join(' ');
}
