// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
import { DictionaryStringTo } from './dictionary-types';
import { WCAG, wcagLinkData } from './wcag';

export const rulesWCAGConfiguration: DictionaryStringTo<WCAG[]> = {
  'area-alt': [wcagLinkData.WCAG1_1_1],
  'image-alt': [wcagLinkData.WCAG1_1_1],
  'image-redundant-alt': [wcagLinkData.WCAGBest_Practice],
  'input-image-alt': [wcagLinkData.WCAG1_1_1],
  'object-alt': [wcagLinkData.WCAG1_1_1],
  'link-name': [wcagLinkData.WCAG1_1_1, wcagLinkData.WCAG2_4_4, wcagLinkData.WCAG4_1_2],
  'audio-caption': [wcagLinkData.WCAG1_2_1],
  'video-caption': [wcagLinkData.WCAG1_2_2],
  'video-description': [wcagLinkData.WCAG1_2_5],
  'aria-required-children': [wcagLinkData.WCAG1_3_1],
  'aria-required-parent': [wcagLinkData.WCAG1_3_1],
  checkboxgroup: [wcagLinkData.WCAGBest_Practice],
  'definition-list': [wcagLinkData.WCAG1_3_1],
  dlitem: [wcagLinkData.WCAG1_3_1],
  'empty-heading': [wcagLinkData.WCAGBest_Practice],
  'layout-table': [wcagLinkData.WCAG1_3_1],
  list: [wcagLinkData.WCAG1_3_1],
  listitem: [wcagLinkData.WCAG1_3_1],
  'p-as-heading': [wcagLinkData.WCAGBest_Practice],
  radiogroup: [wcagLinkData.WCAGBest_Practice],
  'table-duplicate-name': [wcagLinkData.WCAGBest_Practice],
  'table-fake-caption': [wcagLinkData.WCAGBest_Practice],
  'td-has-header': [wcagLinkData.WCAGBest_Practice],
  'td-headers-attr': [wcagLinkData.WCAG1_3_1],
  'th-has-data-cells': [wcagLinkData.WCAG1_3_1],
  'aria-roles': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG4_1_1, wcagLinkData.WCAG4_1_2],
  'aria-valid-attr-value': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG4_1_1, wcagLinkData.WCAG4_1_2],
  'link-in-text-block': [wcagLinkData.WCAGBest_Practice],
  'color-contrast': [wcagLinkData.WCAG1_4_3],
  'meta-viewport-large': [wcagLinkData.WCAGBest_Practice],
  'meta-viewport': [wcagLinkData.WCAG1_4_4],
  accesskeys: [wcagLinkData.WCAG2_1_1],
  'server-side-image-map': [wcagLinkData.WCAG2_1_1],
  'meta-refresh': [wcagLinkData.WCAG2_2_1],
  blink: [wcagLinkData.WCAG2_2_2],
  marquee: [wcagLinkData.WCAG2_2_2],
  bypass: [wcagLinkData.WCAG2_4_1],
  'frame-title': [wcagLinkData.WCAG2_4_1],
  'document-title': [wcagLinkData.WCAG2_4_2],
  tabindex: [wcagLinkData.WCAGBest_Practice],
  'html-has-lang': [wcagLinkData.WCAG3_1_1],
  'html-lang-valid': [wcagLinkData.WCAG3_1_1],
  'valid-lang': [wcagLinkData.WCAG3_1_2],
  label: [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG3_3_2],
  'aria-valid-attr': [wcagLinkData.WCAG4_1_1],
  'duplicate-id': [wcagLinkData.WCAG4_1_1],
  'scope-attr-valid': [wcagLinkData.WCAGBest_Practice],
  'aria-allowed-attr': [wcagLinkData.WCAG4_1_1, wcagLinkData.WCAG4_1_2],
  'aria-required-attr': [wcagLinkData.WCAG4_1_1, wcagLinkData.WCAG4_1_2],
  'aria-hidden-body': [wcagLinkData.WCAG4_1_2],
  'button-name': [wcagLinkData.WCAG4_1_2],
  'frame-title-unique': [wcagLinkData.WCAGBest_Practice],
  'heading-order': [wcagLinkData.WCAGBest_Practice],
  'hidden-content': [wcagLinkData.WCAGBest_Practice],
  'href-no-hash': [wcagLinkData.WCAGBest_Practice],
  'label-title-only': [wcagLinkData.WCAGBest_Practice],
  region: [wcagLinkData.WCAGBest_Practice],
  'skip-link': [wcagLinkData.WCAGBest_Practice],
  'unique-landmark': [wcagLinkData.WCAG2_4_1],
  'landmark-main-is-top-level': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG2_4_1],
  'landmark-one-main': [wcagLinkData.WCAGBest_Practice],
  'aria-dpub-role-fallback': [wcagLinkData.WCAGBest_Practice],
  'focus-order-semantics': [wcagLinkData.WCAGBest_Practice],
  'frame-tested': [wcagLinkData.WCAGBest_Practice],
  'landmark-banner-is-top-level': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG2_4_1],
  'landmark-contentinfo-is-top-level': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG2_4_1],
  'landmark-no-duplicate-banner': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG2_4_1],
  'landmark-no-duplicate-contentinfo': [wcagLinkData.WCAG1_3_1, wcagLinkData.WCAG2_4_1],
  'page-has-heading-one': [wcagLinkData.WCAGBest_Practice],
  'duplicate-id-active': [wcagLinkData.WCAG4_1_1],
  'duplicate-id-aria': [wcagLinkData.WCAG4_1_1],
  'html-xml-lang-mismatch': [wcagLinkData.WCAG3_1_1],
  'get-frame-title': [wcagLinkData.WCAG4_1_2],
  'page-title': [wcagLinkData.WCAG2_4_2],
  'aria-allowed-role': [wcagLinkData.WCAGBest_Practice],
  'autocomplete-valid': [wcagLinkData.WCAGBest_Practice],
  'css-orientation-lock': [wcagLinkData.WCAGBest_Practice]
};
