import componentInfoContext from '../../utils/componentInfoContext';
import { ComponentProp } from '@fluentui/react-docgen';

const useComponentProps = (componentName: string): ComponentProp[] => {
  const info = componentInfoContext.byDisplayName[componentName];

  if (!info) {
    throw new Error(
      `We don't have definitions for "${componentName}". Please ensure those are generated by "gulp-docgen" plugin`,
    );
  }

  return info.props;
};

export default useComponentProps;
