import { CardSize, DraggingAnimationType } from '../../../../index';
import { IStyle } from 'office-ui-fabric-react/lib/Styling';

export interface IAddCardProps {
  /**
   * The id for addCard is autogenerated and if the user passes a id it won't be used
   */
  id: string;

  /**
   * The title for card representation in add card panel
   */
  title: string;

  /**
   * The image url for card representation in add card panel
   */
  imageSrc?: string;

  /**
   * The description for card representation in add card panel
   */
  description?: string;

  /**
   * The callback that is called when a card is clicked
   */
  cardClicked?: (cardId: string) => void;

  /**
   * The callback that is called when a card is dragged, with the necessary card information
   */
  draggingCardCallback: (
    cardId: string,
    title: string,
    cardSize: CardSize,
    initialX: number,
    draggingAnimation?: DraggingAnimationType
  ) => void;

  /**
   * The callback that is passed by add card panel to open the add card panel back
   */
  expandAddCardPanelBack: () => void;

  /**
   * The card size (small | medium tall | medium wide | large)
   */
  cardSize: CardSize;

  /**
   * The dragging animation type for the add card. Used for rendering animation in the dragging card
   */
  draggingAnimation?: DraggingAnimationType;

  /**
   * The aria label for the add card '+' icon
   */
  addCardIconAriaLabel?: string;

  /**
   * The alt text for the image in the add card representation
   */
  addCardImageAltText?: string;
}

export interface IAddCardStyles {
  /**
   * The styles for the root
   */
  root: IStyle;

  /**
   * The styles for the image wrapper
   */
  imageWrapper: IStyle;

  /**
   * Styles for wrapper of header and body text combined
   */
  textContainer: IStyle;

  /**
   * Styles for header of add card representation
   */
  header: IStyle;

  /**
   * Styles for bodyText of add card representation
   */
  bodyText: IStyle;

  /**
   * Styles for the wrapper for add icon of add card
   */
  iconWrapper: IStyle;
}
