// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.

import { css } from '@microsoft/fast-element';
import {
  colorBrandForeground1,
  colorBrandStroke1,
  colorNeutralForeground1,
  colorNeutralForeground2,
  colorNeutralForeground3,
  colorNeutralStroke1,
  colorNeutralStroke2,
  colorNeutralStroke3,
  fontFamilyBase,
  fontSizeBase200,
  fontWeightRegular,
  lineHeightBase200,
  strokeWidthThin,
} from '../theme/design-tokens.js';

export const styles = css`
  /* See companion .styles.css generated from the component style spec. */
  /* Token imports kept for FAST template interpolation parity: colorBrandForeground1, colorBrandStroke1, colorNeutralForeground1, colorNeutralForeground2, colorNeutralForeground3, colorNeutralStroke1, colorNeutralStroke2, colorNeutralStroke3, fontFamilyBase, fontSizeBase200, fontWeightRegular, lineHeightBase200, strokeWidthThin. */
`;
