import { makeStaticStyles, makeStyles, tokens } from '@fluentui/react-components';

export const useGlobalStyles = makeStaticStyles({
  'html, body, #root': {
    minHeight: '100%',
    margin: 0,
  },
  body: {
    backgroundColor: tokens.colorNeutralBackground2,
  },
  '*': {
    boxSizing: 'border-box',
  },
});

export const useAppStyles = makeStyles({
  app: {
    minHeight: '100vh',
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground2,
    fontFamily: tokens.fontFamilyBase,
  },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 4,
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    alignItems: 'center',
    columnGap: tokens.spacingHorizontalL,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalL}`,
    borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    '@media (max-width: 52rem)': {
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      gridTemplateAreas: '"brand actions" "search search"',
      columnGap: tokens.spacingHorizontalS,
      rowGap: tokens.spacingVerticalS,
      paddingInline: tokens.spacingHorizontalS,
    },
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    minWidth: 'max-content',
    '@media (max-width: 52rem)': {
      gridArea: 'brand',
    },
  },
  brandMark: {
    display: 'grid',
    placeItems: 'center',
    width: tokens.spacingHorizontalXXXL,
    height: tokens.spacingHorizontalXXXL,
    borderRadius: tokens.borderRadiusCircular,
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorBrandBackground,
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightBold,
  },
  brandText: {
    fontSize: tokens.fontSizeBase500,
    fontWeight: tokens.fontWeightSemibold,
    '@media (max-width: 40rem)': {
      display: 'none',
    },
  },
  search: {
    width: '100%',
    maxWidth: '100%',
    '@media (max-width: 52rem)': {
      gridArea: 'search',
    },
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
    '@media (max-width: 52rem)': {
      gridArea: 'actions',
      justifySelf: 'end',
    },
  },
  desktopOnly: {
    '@media (max-width: 52rem)': {
      display: 'none',
    },
  },
  mobileOnly: {
    display: 'none',
    '@media (max-width: 52rem)': {
      display: 'inline-flex',
    },
  },
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 3fr) minmax(0, 1fr)',
    alignItems: 'start',
    gap: tokens.spacingHorizontalL,
    padding: tokens.spacingHorizontalL,
    '@media (max-width: 75rem)': {
      gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 3fr)',
    },
    '@media (max-width: 52rem)': {
      display: 'block',
      padding: tokens.spacingHorizontalS,
    },
  },
  communityRail: {
    position: 'sticky',
    top: `calc(${tokens.spacingVerticalXXXL} + ${tokens.spacingVerticalXXL})`,
    display: 'grid',
    rowGap: tokens.spacingVerticalM,
    '@media (max-width: 52rem)': {
      display: 'none',
    },
  },
  sideCard: {
    display: 'grid',
    rowGap: tokens.spacingVerticalM,
    padding: tokens.spacingHorizontalL,
  },
  rightRail: {
    position: 'sticky',
    top: `calc(${tokens.spacingVerticalXXXL} + ${tokens.spacingVerticalXXL})`,
    display: 'grid',
    rowGap: tokens.spacingVerticalL,
    '@media (max-width: 75rem)': {
      display: 'none',
    },
  },
  feed: {
    minWidth: 0,
    display: 'grid',
    rowGap: tokens.spacingVerticalM,
  },
  feedToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalM,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  filterRow: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalM,
  },
  breadcrumbRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacingHorizontalM,
  },
  postCard: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    overflow: 'hidden',
  },
  postCardCompact: {
    '& section': {
      paddingBlock: tokens.spacingVerticalS,
    },
  },
  voteColumn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: tokens.spacingVerticalXXS,
    padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalS}`,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  voteScore: {
    minWidth: tokens.spacingHorizontalXXXL,
    textAlign: 'center',
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
  },
  postContent: {
    minWidth: 0,
    display: 'grid',
    rowGap: tokens.spacingVerticalM,
    padding: tokens.spacingHorizontalL,
  },
  postMeta: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalXS,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  postTitle: {
    margin: 0,
    fontSize: tokens.fontSizeBase500,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase500,
  },
  postBody: {
    margin: 0,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase400,
  },
  postActions: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalXS,
  },
  statePanel: {
    display: 'grid',
    justifyItems: 'center',
    rowGap: tokens.spacingVerticalM,
    padding: `${tokens.spacingVerticalXXXL} ${tokens.spacingHorizontalL}`,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground1,
    textAlign: 'center',
  },
  skeletonCard: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    gap: tokens.spacingHorizontalM,
    padding: tokens.spacingHorizontalL,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  skeletonLines: {
    display: 'grid',
    rowGap: tokens.spacingVerticalS,
  },
  heading: {
    margin: 0,
    fontSize: tokens.fontSizeBase500,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase500,
  },
  subheading: {
    margin: 0,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase400,
  },
  communityButtonContent: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    width: '100%',
  },
  communityName: {
    overflow: 'hidden',
    textAlign: 'start',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  communityList: {
    display: 'grid',
    rowGap: tokens.spacingVerticalXS,
  },
  communitySummary: {
    display: 'grid',
    rowGap: tokens.spacingVerticalXS,
    paddingBlock: tokens.spacingVerticalS,
  },
  commentArea: {
    display: 'grid',
    rowGap: tokens.spacingVerticalM,
    paddingTop: tokens.spacingVerticalM,
    borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
  },
  comment: {
    display: 'grid',
    rowGap: tokens.spacingVerticalS,
    paddingInlineStart: tokens.spacingHorizontalL,
    borderLeft: `${tokens.strokeWidthThick} solid ${tokens.colorNeutralStroke2}`,
  },
  commentCompact: {
    rowGap: tokens.spacingVerticalXS,
    paddingInlineStart: tokens.spacingHorizontalM,
  },
  commentHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  commentBody: {
    margin: 0,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase400,
  },
  replyEditor: {
    display: 'grid',
    rowGap: tokens.spacingVerticalS,
  },
  inlineActions: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
  },
  overlayLayout: {
    display: 'grid',
    rowGap: tokens.spacingVerticalL,
  },
  overlayHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacingHorizontalM,
  },
  form: {
    display: 'grid',
    rowGap: tokens.spacingVerticalL,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: tokens.spacingHorizontalM,
    '@media (max-width: 40rem)': {
      gridTemplateColumns: '1fr',
    },
  },
  formActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
  },
  preferenceGroup: {
    display: 'grid',
    rowGap: tokens.spacingVerticalM,
  },
  preferenceRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: tokens.spacingHorizontalM,
  },
  preferenceDescription: {
    display: 'grid',
    rowGap: tokens.spacingVerticalXXS,
  },
  sliderValue: {
    color: tokens.colorBrandForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  drawerBody: {
    display: 'grid',
    alignContent: 'start',
    rowGap: tokens.spacingVerticalL,
    overflowY: 'auto',
    padding: tokens.spacingHorizontalL,
  },
  drawerHeader: {
    padding: tokens.spacingHorizontalL,
    borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
  },
  drawerFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: tokens.spacingHorizontalS,
    padding: tokens.spacingHorizontalL,
    borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
  },
  notificationItem: {
    display: 'grid',
    rowGap: tokens.spacingVerticalXXS,
    minWidth: 0,
  },
  unreadDot: {
    display: 'inline-block',
    width: tokens.spacingHorizontalS,
    height: tokens.spacingHorizontalS,
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorBrandBackground,
  },
  toastViewport: {
    zIndex: 10,
  },
});

export const useHeadlessStyles = makeStyles({
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.spacingHorizontalXS,
    minHeight: tokens.spacingVerticalXXXL,
    padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalS}`,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorTransparentBackground,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorTransparentStroke}`,
    borderRadius: tokens.borderRadiusMedium,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
    cursor: 'pointer',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
    ':focus-visible': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThick,
    },
    '&[data-disabled]': {
      color: tokens.colorNeutralForegroundDisabled,
      cursor: 'not-allowed',
    },
  },
  primaryButton: {
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorBrandBackground,
    ':hover': {
      backgroundColor: tokens.colorBrandBackgroundHover,
    },
  },
  selectedButton: {
    color: tokens.colorBrandForeground1,
    backgroundColor: tokens.colorBrandBackground2,
    borderTopColor: tokens.colorBrandStroke1,
    borderRightColor: tokens.colorBrandStroke1,
    borderBottomColor: tokens.colorBrandStroke1,
    borderLeftColor: tokens.colorBrandStroke1,
  },
  subtleButton: {
    color: tokens.colorNeutralForeground2,
  },
  iconButton: {
    minWidth: tokens.spacingHorizontalXXXL,
    paddingInline: tokens.spacingHorizontalXS,
    borderRadius: tokens.borderRadiusCircular,
  },
  fullWidthButton: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  checkbox: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    color: tokens.colorNeutralForeground1,
    cursor: 'pointer',
    '&[data-disabled]': {
      color: tokens.colorNeutralForegroundDisabled,
      cursor: 'not-allowed',
    },
    ':focus-within': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
      borderRadius: tokens.borderRadiusSmall,
    },
  },
  checkboxInput: {
    position: 'absolute',
    opacity: 0,
    ':focus-visible': {
      outline: 'none',
    },
  },
  checkboxIndicator: {
    display: 'grid',
    placeItems: 'center',
    width: tokens.spacingHorizontalL,
    height: tokens.spacingHorizontalL,
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusSmall,
    pointerEvents: 'none',
    '[data-checked] &': {
      backgroundColor: tokens.colorBrandBackground,
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
    },
  },
  controlLabel: {
    color: 'inherit',
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
  },
  radioGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalM,
  },
  radio: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    cursor: 'pointer',
    ':focus-within': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
      borderRadius: tokens.borderRadiusSmall,
    },
  },
  radioInput: {
    position: 'absolute',
    opacity: 0,
  },
  radioIndicator: {
    display: 'grid',
    placeItems: 'center',
    width: tokens.spacingHorizontalL,
    height: tokens.spacingHorizontalL,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusCircular,
    pointerEvents: 'none',
    '::after': {
      content: '""',
      width: tokens.spacingHorizontalS,
      height: tokens.spacingHorizontalS,
      borderRadius: tokens.borderRadiusCircular,
      backgroundColor: tokens.colorTransparentBackground,
    },
    ':has(input:checked) &': {
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
    },
    ':has(input:checked) &::after': {
      backgroundColor: tokens.colorBrandBackground,
    },
  },
  switch: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    cursor: 'pointer',
    '&[data-disabled]': {
      color: tokens.colorNeutralForegroundDisabled,
      cursor: 'not-allowed',
    },
    ':focus-within': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
      borderRadius: tokens.borderRadiusCircular,
    },
  },
  switchInput: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    opacity: 0,
    cursor: 'pointer',
  },
  switchIndicator: {
    position: 'relative',
    display: 'inline-block',
    width: `calc(${tokens.spacingHorizontalXXL} + ${tokens.spacingHorizontalL})`,
    height: tokens.spacingVerticalL,
    backgroundColor: tokens.colorNeutralBackground5,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusCircular,
    pointerEvents: 'none',
    '::before': {
      content: '""',
      position: 'absolute',
      insetBlockStart: tokens.spacingVerticalXXS,
      insetInlineStart: tokens.spacingHorizontalXXS,
      width: tokens.spacingHorizontalM,
      height: tokens.spacingHorizontalM,
      borderRadius: tokens.borderRadiusCircular,
      backgroundColor: tokens.colorNeutralForeground3,
      transitionProperty: 'inset-inline-start, background-color',
      transitionDuration: tokens.durationNormal,
    },
    '[data-checked] &': {
      backgroundColor: tokens.colorBrandBackground,
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
    },
    '[data-checked] &::before': {
      insetInlineStart: `calc(100% - ${tokens.spacingHorizontalL})`,
      backgroundColor: tokens.colorNeutralForegroundOnBrand,
    },
  },
  slider: {
    position: 'relative',
    display: 'grid',
    alignItems: 'center',
    width: '100%',
    minHeight: tokens.spacingVerticalXXXL,
    '&[data-disabled]': {
      cursor: 'not-allowed',
    },
  },
  sliderInput: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    opacity: 0,
    cursor: 'pointer',
    ':focus-visible + div': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThick,
    },
  },
  sliderRail: {
    width: '100%',
    height: tokens.spacingVerticalXS,
    backgroundColor: tokens.colorNeutralBackground5,
    borderRadius: tokens.borderRadiusCircular,
  },
  sliderThumb: {
    position: 'absolute',
    width: tokens.spacingHorizontalL,
    height: tokens.spacingHorizontalL,
    backgroundColor: tokens.colorBrandBackground,
    border: `${tokens.strokeWidthThick} solid ${tokens.colorNeutralBackground1}`,
    borderRadius: tokens.borderRadiusCircular,
    boxShadow: tokens.shadow4,
    pointerEvents: 'none',
  },
  input: {
    display: 'flex',
    alignItems: 'center',
    minHeight: tokens.spacingVerticalXXXL,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    ':focus-within': {
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
    },
    '&[data-invalid]': {
      borderTopColor: tokens.colorPaletteRedBorder2,
      borderRightColor: tokens.colorPaletteRedBorder2,
      borderBottomColor: tokens.colorPaletteRedBorder2,
      borderLeftColor: tokens.colorPaletteRedBorder2,
    },
  },
  inputElement: {
    width: '100%',
    minWidth: 0,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorTransparentBackground,
    border: 'none',
    outline: 'none',
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
  },
  textarea: {
    display: 'flex',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    ':focus-within': {
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
    },
    '&[data-invalid]': {
      borderTopColor: tokens.colorPaletteRedBorder2,
      borderRightColor: tokens.colorPaletteRedBorder2,
      borderBottomColor: tokens.colorPaletteRedBorder2,
      borderLeftColor: tokens.colorPaletteRedBorder2,
    },
  },
  textareaElement: {
    width: '100%',
    minHeight: `calc(${tokens.spacingVerticalXXXL} + ${tokens.spacingVerticalXXXL} + ${tokens.spacingVerticalXXXL})`,
    padding: tokens.spacingHorizontalM,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorTransparentBackground,
    border: 'none',
    outline: 'none',
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase400,
  },
  dropdown: {
    position: 'relative',
    display: 'grid',
    width: '100%',
  },
  dropdownButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacingHorizontalM,
    width: '100%',
    minHeight: tokens.spacingVerticalXXXL,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    textAlign: 'start',
    cursor: 'pointer',
    ':focus-visible': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
    },
    '[data-open] &': {
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
    },
  },
  dropdownListbox: {
    zIndex: 8,
    display: 'grid',
    rowGap: tokens.spacingVerticalXXS,
    maxHeight: '45vh',
    overflowY: 'auto',
    padding: tokens.spacingHorizontalXS,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow16,
  },
  dropdownOption: {
    display: 'flex',
    alignItems: 'center',
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    borderRadius: tokens.borderRadiusSmall,
    cursor: 'pointer',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
    '&[data-selected]': {
      color: tokens.colorBrandForeground1,
      backgroundColor: tokens.colorBrandBackground2,
      fontWeight: tokens.fontWeightSemibold,
    },
    '&[data-disabled]': {
      color: tokens.colorNeutralForegroundDisabled,
      cursor: 'not-allowed',
    },
  },
  menuPopover: {
    zIndex: 9,
    minWidth: 'min-content',
    padding: tokens.spacingHorizontalXS,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow16,
  },
  menuList: {
    display: 'grid',
    rowGap: tokens.spacingVerticalXXS,
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    width: '100%',
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorTransparentBackground,
    border: 'none',
    borderRadius: tokens.borderRadiusSmall,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    cursor: 'pointer',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
    ':focus-visible': {
      outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
      outlineOffset: tokens.strokeWidthThin,
    },
    '&[data-disabled]': {
      color: tokens.colorNeutralForegroundDisabled,
      cursor: 'not-allowed',
    },
  },
  dialogSurface: {
    width: '80vw',
    maxWidth: '92vw',
    maxHeight: '88vh',
    overflowY: 'auto',
    padding: tokens.spacingHorizontalXXL,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusXLarge,
    boxShadow: tokens.shadow64,
    '::backdrop': {
      backgroundColor: tokens.colorBackgroundOverlay,
    },
    '@media (max-width: 40rem)': {
      width: '92vw',
      padding: tokens.spacingHorizontalL,
    },
  },
  drawerSurface: {
    position: 'fixed',
    insetBlock: 0,
    insetInlineEnd: 0,
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr) auto',
    width: 'min(88vw, 40%)',
    maxWidth: '92vw',
    height: '100vh',
    margin: 0,
    padding: 0,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground1,
    border: 'none',
    boxShadow: tokens.shadow64,
    '&[data-position="start"]': {
      insetInlineStart: 0,
      insetInlineEnd: 'auto',
      borderRight: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    '&[data-position="end"]': {
      insetInlineStart: 'auto',
      insetInlineEnd: 0,
      borderLeft: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    '::backdrop': {
      backgroundColor: tokens.colorBackgroundOverlay,
    },
    '@media (max-width: 52rem)': {
      width: '88vw',
    },
  },
});
