name: '🚀 Feature proposal'
description: Propose a new feature.
title: '[Feature]: '
labels: ['Type: Feature', 'Needs: Triage :mag:']
projects: ['microsoft/395']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and for taking the time to fill out this feature report!

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: To which area would this be added to
      options:
        - React Components (@fluentui/react-components)
        - React Charting (@fluentui/react-charting)
        - Web Components (@fluentui/web-components)
        - Tooling
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature that you would like added
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here?

  - type: input
    id: feature-discussed-with
    attributes:
      label: Have you discussed this feature with our team
      description: |
        Please use a particular person or team's GitHub handle.
        If you haven't discussed it with anyone leave it blank.
      placeholder: e.g. @microsoft/cxe-prg @githubHandle

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.
          required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is this feature's priority from your product's perspective
      options:
        - High
        - Medium
        - Low
    validations:
      required: false
