'use client';

import { makeStyles } from '@griffel/react';

export const useIntroductionStyles = makeStyles({
  hero: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 'var(--space-8)',
    paddingRight: 0,
    paddingBottom: 'var(--space-8)',
    paddingLeft: 0,
    marginBottom: 'var(--space-10)',
    '@media (max-width: 768px)': {
      paddingTop: 'var(--space-4)',
      paddingRight: 'var(--space-2)',
      paddingBottom: 'var(--space-4)',
      paddingLeft: 'var(--space-2)',
    },
  },
  heroImage: {
    width: '100%',
    height: 'auto',
    maxHeight: '500px',
    objectFit: 'cover',
    objectPosition: 'center',
    borderRadius: 'var(--radius-lg)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopColor: 'var(--border)',
    borderRightColor: 'var(--border)',
    borderBottomColor: 'var(--border)',
    borderLeftColor: 'var(--border)',
  },

  features: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: 'var(--space-6)',
    marginBottom: 'var(--space-10)',
    padding: 0,
    '@media (max-width: 768px)': {
      gridTemplateColumns: '1fr',
    },
  },
  card: {
    padding: 0,
    backgroundColor: 'var(--bg)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: 'var(--stroke-thin)',
    borderRightWidth: 'var(--stroke-thin)',
    borderBottomWidth: 'var(--stroke-thin)',
    borderLeftWidth: 'var(--stroke-thin)',
    borderTopColor: 'var(--border)',
    borderRightColor: 'var(--border)',
    borderBottomColor: 'var(--border)',
    borderLeftColor: 'var(--border)',
    borderRadius: 'var(--radius-lg)',
    transitionProperty: 'all',
    transitionDuration: 'var(--duration-medium)',
    transitionTimingFunction: 'var(--ease-standard)',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    boxShadow: 'var(--shadow-1)',
    overflow: 'hidden',
    ':hover': {
      borderTopColor: 'var(--accent)',
      borderRightColor: 'var(--accent)',
      borderBottomColor: 'var(--accent)',
      borderLeftColor: 'var(--accent)',
      boxShadow: 'var(--shadow-4)',
      transform: 'translateY(-4px)',
    },
  },
  cardImage: {
    width: '100%',
    height: 'auto',
    minHeight: '200px',
    objectFit: 'cover',
    objectPosition: 'center',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: 'var(--border)',
  },
  cardTitle: {
    fontSize: '1.125rem',
    fontWeight: 600,
    color: 'var(--text)',
    margin: 0,
    paddingTop: 'var(--space-4)',
    paddingRight: 'var(--space-6)',
    paddingLeft: 'var(--space-6)',
    paddingBottom: 0,
  },
  cardText: {
    fontSize: '1rem',
    color: 'var(--text-muted)',
    margin: 0,
    paddingTop: 0,
    paddingRight: 'var(--space-6)',
    paddingBottom: 'var(--space-6)',
    paddingLeft: 'var(--space-6)',
    lineHeight: 1.6,
  },

  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: 'var(--space-6)',
    padding: 0,
    backgroundColor: 'transparent',
    borderRadius: 0,
    '@media (max-width: 768px)': {
      gridTemplateColumns: '1fr',
      paddingTop: 'var(--space-4)',
      paddingRight: 'var(--space-4)',
      paddingBottom: 'var(--space-4)',
      paddingLeft: 'var(--space-4)',
    },
  },
  gridCard: {
    padding: 0,
    backgroundColor: 'var(--bg)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: 'var(--stroke-thin)',
    borderRightWidth: 'var(--stroke-thin)',
    borderBottomWidth: 'var(--stroke-thin)',
    borderLeftWidth: 'var(--stroke-thin)',
    borderTopColor: 'var(--border)',
    borderRightColor: 'var(--border)',
    borderBottomColor: 'var(--border)',
    borderLeftColor: 'var(--border)',
    borderRadius: 'var(--radius-lg)',
    transitionProperty: 'all',
    transitionDuration: 'var(--duration-medium)',
    transitionTimingFunction: 'var(--ease-standard)',
    boxShadow: 'var(--shadow-1)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    ':hover': {
      borderTopColor: 'var(--accent)',
      borderRightColor: 'var(--accent)',
      borderBottomColor: 'var(--accent)',
      borderLeftColor: 'var(--accent)',
      boxShadow: 'var(--shadow-3)',
      transform: 'translateY(-2px)',
    },
  },
  gridImage: {
    width: '100%',
    height: '240px',
    objectFit: 'cover',
    objectPosition: 'center',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: 'var(--border)',
  },
  gridTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--text)',
    marginTop: 0,
    marginRight: 0,
    marginBottom: 'var(--space-2)',
    marginLeft: 0,
    paddingTop: 'var(--space-4)',
    paddingRight: 'var(--space-4)',
    paddingLeft: 'var(--space-4)',
    paddingBottom: 0,
  },
  gridText: {
    fontSize: '0.95rem',
    color: 'var(--text-muted)',
    margin: 0,
    paddingTop: 0,
    paddingRight: 'var(--space-4)',
    paddingBottom: 'var(--space-4)',
    paddingLeft: 'var(--space-4)',
    lineHeight: 1.6,
  },
});
