import { ComponentInfo } from './types';

export const fabricComponents: ComponentInfo[] = [
  {
    constructorName: 'FabricDefaultButton',
    componentClassName: 'FabricDefaultButton',
    implementsCreateShorthand: false,
    displayName: 'DefaultButton',
    filename: 'N/A',
    filenameWithoutExt: 'N/A',
    docblock: {
      description: 'V7 Default Button from @fluentui/react',
      tags: [
        {
          description: 'N/A',
          title: 'N/A',
        },
      ],
    },
    apiPath: 'N/A',
    isChild: false,
    isParent: false,
    parentDisplayName: 'N/A',
    props: [
      {
        defaultValue: 'I am a Fabric Button',
        description: 'Text of the button',
        name: 'text',
        required: false,
        tags: [],
        types: [{ name: 'string', keyword: true }],
      },
      {
        defaultValue: '',
        description: 'The detailed description of the button',
        name: 'ariaDescription',
        required: false,
        tags: [],
        types: [{ name: 'string', keyword: true }],
      },
      {
        defaultValue: false,
        description: 'Disabled button',
        name: 'disabled',
        required: false,
        tags: [],
        types: [{ name: 'boolean', keyword: true }],
      },
      {
        defaultValue: false,
        description: 'Checked of button',
        name: 'checked',
        required: false,
        tags: [],
        types: [{ name: 'boolean', keyword: true }],
      },
    ],
    repoPath: 'N/A',
    subcomponentName: 'N/A',
    subcomponents: [],
    type: 'component',
  },
  {
    constructorName: 'PrimaryButton',
    componentClassName: 'FabricButton',
    implementsCreateShorthand: false,
    displayName: 'PrimaryButton',
    filename: 'N/A',
    filenameWithoutExt: 'N/A',
    docblock: {
      description: 'V7 Primary Button from @fluentui/react',
      tags: [
        {
          description: 'N/A',
          title: 'N/A',
        },
      ],
    },
    apiPath: 'N/A',
    isChild: false,
    isParent: false,
    parentDisplayName: 'N/A',
    props: [
      {
        defaultValue: 'I am a Fabric Button',
        description: 'Text of the button',
        name: 'text',
        required: false,
        tags: [],
        types: [{ name: 'string', keyword: true }],
      },
      {
        defaultValue: '',
        description: 'The detailed description of the button',
        name: 'ariaDescription',
        required: false,
        tags: [],
        types: [{ name: 'string', keyword: true }],
      },
      {
        defaultValue: false,
        description: 'Disabled button',
        name: 'disabled',
        required: false,
        tags: [],
        types: [{ name: 'boolean', keyword: true }],
      },
      {
        defaultValue: false,
        description: 'Checked of button',
        name: 'checked',
        required: false,
        tags: [],
        types: [{ name: 'boolean', keyword: true }],
      },
    ],
    repoPath: 'N/A',
    subcomponentName: 'N/A',
    subcomponents: [],
    type: 'component',
  },
  {
    constructorName: 'FabricActionButton',
    componentClassName: 'FabricActionButton',
    implementsCreateShorthand: false,
    displayName: 'ActionButton',
    filename: 'N/A',
    filenameWithoutExt: 'N/A',
    docblock: {
      description: 'V7 Actiob Button from @fluentui/react',
      tags: [
        {
          description: 'N/A',
          title: 'N/A',
        },
      ],
    },
    apiPath: 'N/A',
    isChild: false,
    isParent: false,
    parentDisplayName: 'N/A',
    props: [
      {
        defaultValue: 'I am a Fabric Button',
        description: 'Text of the button',
        name: 'text',
        required: false,
        tags: [],
        types: [{ name: 'string', keyword: true }],
      },
      {
        defaultValue: '',
        description: 'The detailed description of the button',
        name: 'ariaDescription',
        required: false,
        tags: [],
        types: [{ name: 'string', keyword: true }],
      },
      {
        defaultValue: false,
        description: 'Disabled button',
        name: 'disabled',
        required: false,
        tags: [],
        types: [{ name: 'boolean', keyword: true }],
      },
      {
        defaultValue: false,
        description: 'Checked of button',
        name: 'checked',
        required: false,
        tags: [],
        types: [{ name: 'boolean', keyword: true }],
      },
    ],
    repoPath: 'N/A',
    subcomponentName: 'N/A',
    subcomponents: [],
    type: 'component',
  },
];
