  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-0"`,
      src: `url('${baseUrl}fabric-icons-0-a622ebce.woff') format('woff')`
    },
    icons: {
      'PageLink': '\uE302',
      'CommentSolid': '\uE30E',
      'ChangeEntitlements': '\uE310',
      'Installation': '\uE311',
      'WebAppBuilderModule': '\uE313',
      'WebAppBuilderFragment': '\uE314',
      'WebAppBuilderSlot': '\uE315',
      'BullseyeTargetEdit': '\uE319',
      'WebAppBuilderFragmentCreate': '\uE31B',
      'PageData': '\uE31C',
      'PageHeaderEdit': '\uE31D',
      'ProductList': '\uE31E',
      'UnpublishContent': '\uE31F',
      'DependencyAdd': '\uE344',
      'DependencyRemove': '\uE345',
      'EntitlementPolicy': '\uE346',
      'EntitlementRedemption': '\uE347',
      'SchoolDataSyncLogo': '\uE34C',
      'PinSolid12': '\uE352',
      'PinSolidOff12': '\uE353',
      'AddLink': '\uE35E',
      'SharepointAppIcon16': '\uE365',
      'DataflowsLink': '\uE366',
      'TimePicker': '\uE367',
      'UserWarning': '\uE368',
      'ComplianceAudit': '\uE369',
      'StickyNotesOutlineAppIcon': '\uE36A',
      'StickyNotesSolidAppIcon': '\uE36B',
      'Webcam2Off': '\uE36D',
      'eDiscovery': '\uE370',
      'CalendarYear': '\uE371',
      'IgnoreConversation': '\uE372',
      'CommonDataServiceCDS': '\uE377',
      'Forum': '\uE378',
      'SentimentAnalysis': '\uE393',
      'TextRecognition': '\uE394',
      'KeyPhraseExtraction': '\uE395',
      'AltText': '\uE397',
      'NumberedListMirrored': '\uE398',
      'IncreaseIndent': '\uE399',
      'IncreaseIndentMirrored': '\uE39A',
      'DecreaseIndent': '\uE39B',
      'DecreaseIndentMirrored': '\uE39C',
      'IncreaseIndentHanging': '\uE39D',
      'IncreaseIndentHangingMirrored': '\uE39E',
      'ArchiveUndo': '\uE3A1',
      'LeaveUser': '\uE3A8',
      'FabricFolderUpload': '\uE3AC',
      'RedEye12': '\uE3AD',
      'MapPin12': '\uE3AE',
      'Insights': '\uE3AF',
      'TaskList': '\uE3B6',
      'MachineLearning': '\uE3B8',
      'HealthRefresh': '\uE3BD',
      'FontSize2': '\uE3C0',
      'SharedDatabase': '\uE3D9',
      'WebEnvironment': '\uE3DB',
      'FormatPainter': '\uE3DC',
      'IndentFirstLine': '\uE3DD',
      'AddSpaceBefore': '\uE3DE',
      'AddSpaceAfter': '\uE3DF',
      'TextAlignTop': '\uE3E0',
      'TextAlignMiddle': '\uE3E1',
      'TextAlignBottom': '\uE3E2',
      'TextParagraphOption': '\uE3E3',
      'TextRotation': '\uE3E4',
      'TextRotateHorizontal': '\uE3E5',
      'TextRotate90Degrees': '\uE3E6',
      'TextRotate270Degrees': '\uE3E7',
      'AutoFitContents': '\uE3E8',
      'AutoFitWindow': '\uE3E9',
      'FixedColumnWidth': '\uE3EA',
      'RepeatHeaderRows': '\uE3EB',
      'TableHeaderRow': '\uE3EC',
      'TableTotalRow': '\uE3ED',
      'TableBrandedRow': '\uE3EE',
      'TableFirstColumn': '\uE3EF',
      'TableLastColumn': '\uE3F0',
      'TableBrandedColumn': '\uE3F1',
      'AutomateFlow': '\uE3F5',
      'TagGroup': '\uE3F6',
      'PhotoError': '\uE3F7',
      'HexaditeInvestigation': '\uE3F8',
      'HexaditeInvestigationCancel': '\uE3F9',
      'HexaditeInvestigationSemiAuto': '\uE3FA',
      'DriverOff': '\uE3FB',
      'FileOff': '\uE3FC',
      'ServiceOff': '\uE3FD',
      'URLBlock': '\uE3FE',
      'BugSync': '\uE3FF',
      'BugBlock': '\uE400',
      'DeviceRun': '\uE401',
      'DeviceOff': '\uE402',
      'ProcessingCancel': '\uE403',
      'ProcessingRun': '\uE404',
      'ProcessingPause': '\uE405',
      'CalculatorDelta': '\uE406',
      'InputAddress': '\uE41E',
      'ViewInAR': '\uE41F',
      'ImageInAR': '\uE420'
    }
  };

  registerIcons(subset, options);
}
