// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.
// @ts-nocheck — generated output; slot/variant state is intentionally loosely typed for PoC.

'use client';

import { makeResetStyles, makeStyles, mergeClasses } from '@griffel/react';
import { tokens } from '@fluentui/react-theme';
import type { SlotClassNames } from '@fluentui/react-utilities';

export const buttonClassNames: SlotClassNames<Record<string, unknown>> = {
  root: 'fui-Button',
  icon: 'fui-Button__icon',
};

const useRootBaseClassName = makeResetStyles({
  alignItems: 'center',
  boxSizing: 'border-box',
  display: 'inline-flex',
  justifyContent: 'center',
  textDecorationLine: 'none',
  verticalAlign: 'middle',
  margin: 0,
  overflow: 'hidden',
  backgroundColor: tokens.colorNeutralBackground1,
  color: tokens.colorNeutralForeground1,
  border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
  fontFamily: tokens.fontFamilyBase,
  outlineStyle: 'none',
  padding: `5px ${tokens.spacingHorizontalM}`,
  minWidth: '96px',
  borderRadius: tokens.borderRadiusMedium,
  fontSize: tokens.fontSizeBase300,
  fontWeight: tokens.fontWeightSemibold,
  lineHeight: tokens.lineHeightBase300,
  transitionDuration: tokens.durationFaster,
  transitionProperty: 'background, border, color',
  transitionTimingFunction: tokens.curveEasyEase,
  ':focus-visible': {
    borderColor: tokens.colorStrokeFocus2,
    borderRadius: tokens.borderRadiusMedium,
    borderWidth: '1px',
    outline: `${tokens.strokeWidthThick} solid ${tokens.colorTransparentStroke}`,
    boxShadow: `0 0 0 ${tokens.strokeWidthThin} ${tokens.colorStrokeFocus2} inset`,
    zIndex: 1,
  },
  ':hover': {
    backgroundColor: tokens.colorNeutralBackground1Hover,
    borderColor: tokens.colorNeutralStroke1Hover,
    color: tokens.colorNeutralForeground1Hover,
    cursor: 'pointer',
  },
  ':hover:active,:active:focus-visible': {
    backgroundColor: tokens.colorNeutralBackground1Pressed,
    borderColor: tokens.colorNeutralStroke1Pressed,
    color: tokens.colorNeutralForeground1Pressed,
    outlineStyle: 'none',
  },
  '@media (forced-colors: active)': {
    ':hover': {
      backgroundColor: 'HighlightText',
      borderColor: 'Highlight',
      color: 'Highlight',
      forcedColorAdjust: 'none',
    },
  },
  '@media screen and (prefers-reduced-motion: reduce)': {
    transitionDuration: '0.01ms',
  },
});

const useRootStyles = makeStyles({
  'appearance-primary': {
    backgroundColor: tokens.colorBrandBackground,
    borderColor: 'transparent',
    color: tokens.colorNeutralForegroundOnBrand,
    ':hover': {
      backgroundColor: tokens.colorBrandBackgroundHover,
      borderColor: 'transparent',
      color: tokens.colorNeutralForegroundOnBrand,
    },
    ':hover:active,:active:focus-visible': {
      backgroundColor: tokens.colorBrandBackgroundPressed,
      borderColor: 'transparent',
      color: tokens.colorNeutralForegroundOnBrand,
    },
    '@media (forced-colors: active)': {
      backgroundColor: 'Highlight',
      borderColor: 'HighlightText',
      color: 'HighlightText',
      forcedColorAdjust: 'none',
    },
  },
  'appearance-outline': {
    backgroundColor: tokens.colorTransparentBackground,
    ':hover': {
      backgroundColor: tokens.colorTransparentBackgroundHover,
    },
  },
  'appearance-subtle': {
    backgroundColor: tokens.colorSubtleBackground,
    borderColor: 'transparent',
    color: tokens.colorNeutralForeground2,
    ':hover': {
      backgroundColor: tokens.colorSubtleBackgroundHover,
      borderColor: 'transparent',
      color: tokens.colorNeutralForeground2Hover,
    },
  },
  'appearance-transparent': {
    backgroundColor: tokens.colorTransparentBackground,
    borderColor: 'transparent',
    color: tokens.colorNeutralForeground2,
    ':hover': {
      backgroundColor: tokens.colorTransparentBackgroundHover,
      borderColor: 'transparent',
      color: tokens.colorNeutralForeground2BrandHover,
    },
  },
  'size-small': {
    minWidth: '64px',
    padding: `3px ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusMedium,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeightBase200,
  },
  'size-large': {
    minWidth: '96px',
    padding: `8px ${tokens.spacingHorizontalL}`,
    borderRadius: tokens.borderRadiusMedium,
    fontSize: tokens.fontSizeBase400,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase400,
  },
  'shape-circular': {
    borderRadius: tokens.borderRadiusCircular,
  },
  'shape-square': {
    borderRadius: tokens.borderRadiusNone,
  },
  'state-disabled': {
    backgroundColor: tokens.colorNeutralBackgroundDisabled,
    borderColor: tokens.colorNeutralStrokeDisabled,
    color: tokens.colorNeutralForegroundDisabled,
    cursor: 'not-allowed',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackgroundDisabled,
      borderColor: tokens.colorNeutralStrokeDisabled,
      color: tokens.colorNeutralForegroundDisabled,
      cursor: 'not-allowed',
    },
  },
  'appearance-primary--state-disabled': {
    borderColor: 'transparent',
  },
  'appearance-outline--state-disabled': {
    backgroundColor: tokens.colorTransparentBackground,
  },
  'appearance-subtle--state-disabled': {
    backgroundColor: tokens.colorTransparentBackground,
    borderColor: 'transparent',
  },
  'appearance-transparent--state-disabled': {
    backgroundColor: tokens.colorTransparentBackground,
    borderColor: 'transparent',
  },
  'size-small--state-iconOnly': {
    padding: '1px',
    minWidth: '24px',
    maxWidth: '24px',
  },
  'size-small--state-hasIcon': {
    paddingBottom: '1px',
    paddingTop: '1px',
  },
  'size-medium--state-iconOnly': {
    padding: '5px',
    minWidth: '32px',
    maxWidth: '32px',
  },
  'size-large--state-iconOnly': {
    padding: '7px',
    minWidth: '40px',
    maxWidth: '40px',
  },
  'size-large--state-hasIcon': {
    paddingBottom: '7px',
    paddingTop: '7px',
  },
});

const useIconBaseClassName = makeResetStyles({
  alignItems: 'center',
  display: 'inline-flex',
  justifyContent: 'center',
  fontSize: '20px',
  height: '20px',
  width: '20px',
  '--fui-Button__icon--spacing': tokens.spacingHorizontalSNudge,
});

const useIconStyles = makeStyles({
  'appearance-subtle': {
    ':hover': {
      color: tokens.colorNeutralForeground2BrandHover,
    },
  },
  'size-small': {
    fontSize: '20px',
    height: '20px',
    width: '20px',
    '--fui-Button__icon--spacing': tokens.spacingHorizontalXS,
  },
  'size-large': {
    fontSize: '24px',
    height: '24px',
    width: '24px',
    '--fui-Button__icon--spacing': tokens.spacingHorizontalSNudge,
  },
  'state-disabled': {
    color: tokens.colorNeutralForegroundDisabled,
  },
  'iconPosition-before--state-hasChildren': {
    marginRight: 'var(--fui-Button__icon--spacing)',
  },
  'iconPosition-after--state-hasChildren': {
    marginLeft: 'var(--fui-Button__icon--spacing)',
  },
});

export const useButtonStyles_unstable = (state: Record<string, any>): typeof state => {
  const rootBaseClassName = useRootBaseClassName();
  const rootStyles = useRootStyles();
  const iconBaseClassName = useIconBaseClassName();
  const iconStyles = useIconStyles();

  if (state.root) {
    state.root.className = mergeClasses(
      buttonClassNames.root,
      rootBaseClassName,
      state.appearance === 'primary' && rootStyles['appearance-primary'],
      state.appearance === 'outline' && rootStyles['appearance-outline'],
      state.appearance === 'subtle' && rootStyles['appearance-subtle'],
      state.appearance === 'transparent' && rootStyles['appearance-transparent'],
      state.size === 'small' && rootStyles['size-small'],
      state.size === 'large' && rootStyles['size-large'],
      state.shape === 'circular' && rootStyles['shape-circular'],
      state.shape === 'square' && rootStyles['shape-square'],
      Boolean(state.disabled) && rootStyles['state-disabled'],
      state.appearance === 'primary' && Boolean(state.disabled) && rootStyles['appearance-primary--state-disabled'],
      state.appearance === 'outline' && Boolean(state.disabled) && rootStyles['appearance-outline--state-disabled'],
      state.appearance === 'subtle' && Boolean(state.disabled) && rootStyles['appearance-subtle--state-disabled'],
      state.appearance === 'transparent' &&
        Boolean(state.disabled) &&
        rootStyles['appearance-transparent--state-disabled'],
      state.size === 'small' && Boolean(state.iconOnly) && rootStyles['size-small--state-iconOnly'],
      state.size === 'small' && Boolean(state.hasIcon) && rootStyles['size-small--state-hasIcon'],
      state.size === 'medium' && Boolean(state.iconOnly) && rootStyles['size-medium--state-iconOnly'],
      state.size === 'large' && Boolean(state.iconOnly) && rootStyles['size-large--state-iconOnly'],
      state.size === 'large' && Boolean(state.hasIcon) && rootStyles['size-large--state-hasIcon'],
      state.root.className,
    );
  }

  if (state.icon) {
    state.icon.className = mergeClasses(
      buttonClassNames.icon,
      iconBaseClassName,
      state.appearance === 'subtle' && iconStyles['appearance-subtle'],
      state.size === 'small' && iconStyles['size-small'],
      state.size === 'large' && iconStyles['size-large'],
      Boolean(state.disabled) && iconStyles['state-disabled'],
      state.iconPosition === 'before' &&
        Boolean(state.hasChildren) &&
        iconStyles['iconPosition-before--state-hasChildren'],
      state.iconPosition === 'after' &&
        Boolean(state.hasChildren) &&
        iconStyles['iconPosition-after--state-hasChildren'],
      state.icon.className,
    );
  }

  return state;
};
