// eslint-disable-next-line no-restricted-imports
import { tokens } from '@fluentui/tokens';

export const ctrlInputBackgroundRest = `var(${ctrlInputBackgroundRestRaw}, var(${backgroundCtrlNeutralRestRaw}, ${tokens.colorNeutralBackground1}))`;
export const ctrlInputBackgroundHover = `var(${ctrlInputBackgroundHoverRaw}, var(${backgroundCtrlNeutralHoverRaw}, ${tokens.colorNeutralBackground1}))`;
export const ctrlInputBackgroundPressed = `var(${ctrlInputBackgroundPressedRaw}, var(${backgroundCtrlNeutralPressedRaw}, ${tokens.colorNeutralBackground1}))`;
export const ctrlInputBackgroundDisabled = `var(${ctrlInputBackgroundDisabledRaw}, var(${backgroundCtrlNeutralDisabledRaw}, ${tokens.colorNeutralBackgroundTransparent}))`;
export const ctrlInputBackgroundSelected = `var(${ctrlInputBackgroundSelectedRaw}, var(${backgroundCtrlNeutralRestRaw}, ${tokens.colorNeutralBackground1}))`;
export const ctrlInputBackgroundError = `var(${ctrlInputBackgroundErrorRaw}, var(${backgroundCtrlNeutralRestRaw}, ${tokens.colorNeutralBackground1}))`;
export const ctrlInputStrokeRest = `var(${ctrlInputStrokeRestRaw}, var(${strokeCtrlOnoutlineRestRaw}, ${tokens.colorNeutralStroke1}))`;
export const ctrlInputBottomlineStrokewidthRest = `var(${ctrlInputBottomlineStrokewidthRestRaw}, var(${strokewidthDefaultRaw}, ${tokens.strokeWidthThin}))`;
export const ctrlInputStrokewidthRest = `var(${ctrlInputStrokewidthRestRaw}, var(${strokewidthDefaultRaw}, ${tokens.strokeWidthThin}))`;
export const ctrlInputTextselectionBackground = `var(${ctrlInputTextselectionBackgroundRaw}, var(${backgroundCtrlActivebrandRestRaw}, var(${backgroundCtrlBrandRestRaw}, ${brandBackground1RestRaw})))`;
export const ctrlInputTextselectionForeground = `var(${ctrlInputTextselectionForegroundRaw}, var(${foregroundCtrlOnbrandRestRaw}, ${tokens.colorNeutralForeground4}))`;
export const ctrlInputStrokewidthHover = `var(${ctrlInputStrokewidthHoverRaw}, var(${strokewidthDefaultRaw}, ${tokens.strokeWidthThin}))`;
export const ctrlInputStrokewidthPressed = `var(${ctrlInputStrokewidthPressedRaw}, var(${strokewidthDefaultRaw}, ${tokens.strokeWidthThin}))`;
export const ctrlInputStrokewidthSelected = `var(${ctrlInputStrokewidthSelectedRaw}, ${tokens.strokeWidthThin})`;
export const ctrlInputBottomlineStrokewidthHover = `var(${ctrlInputBottomlineStrokewidthHoverRaw}, var(${strokewidthDefaultRaw}, ${tokens.strokeWidthThin}))`;
export const ctrlInputBottomlineStrokewidthPressed = `var(${ctrlInputBottomlineStrokewidthPressedRaw}, var(${ctrlInputBottomlineStrokewidthSelectedRaw}, ${thickRaw}))`;
export const ctrlInputBottomlineStrokewidthSelected = `var(${ctrlInputBottomlineStrokewidthSelectedRaw}, ${thickRaw})`;
export const ctrlInputBottomlineStrokeRest = `var(${ctrlInputBottomlineStrokeRestRaw}, var(${foregroundCtrlNeutralSecondaryRestRaw}, ${tokens.colorNeutralStrokeAccessible}))`;
export const ctrlInputBottomlineStrokeHover = `var(${ctrlInputBottomlineStrokeHoverRaw}, var(${foregroundCtrlNeutralSecondaryRestRaw}, ${tokens.colorNeutralStrokeAccessible}))`;
export const ctrlInputBottomlineStrokePressed = `var(${ctrlInputBottomlineStrokePressedRaw}, var(${foregroundCtrlNeutralSecondaryRestRaw}, ${tokens.colorNeutralStrokeAccessible}))`;
export const ctrlInputBottomlineStrokeDisabled = `var(${ctrlInputBottomlineStrokeDisabledRaw}, var(${nullColorRaw}, ${tokens.strokeNeutralTransparent}))`;
export const ctrlInputBottomlineStrokeSelected = `var(${ctrlInputBottomlineStrokeSelectedRaw}, var(${backgroundCtrlBrandRestRaw}, ${brandStroke1RestRaw}))`;
export const ctrlInputBottomlineStrokeError = `var(${ctrlInputBottomlineStrokeErrorRaw}, var(${nullColorRaw}, ${tokens.strokeNeutralTransparent}))`;
export const ctrlInputStrokeHover = `var(${ctrlInputStrokeHoverRaw}, var(${strokeCtrlOnoutlineHoverRaw}, ${tokens.colorNeutralStroke1}))`;
export const ctrlInputStrokePressed = `var(${ctrlInputStrokePressedRaw}, var(${strokeCtrlOnoutlinePressedRaw}, ${tokens.colorNeutralStroke1}))`;
export const ctrlInputStrokeDisabled = `var(${ctrlInputStrokeDisabledRaw}, var(${strokeCtrlOnoutlineDisabledRaw}, ${tokens.strokeNeutralDisabled}))`;
export const ctrlInputStrokeSelected = `var(${ctrlInputStrokeSelectedRaw}, var(${strokeCtrlOnoutlineRestRaw}, ${tokens.colorNeutralStroke1}))`;
export const ctrlInputStrokeError = `var(${ctrlInputStrokeErrorRaw}, var(${statusDangerStrokeRaw}, ${statusDangerStroke2RestRaw}))`;
