/* !!! DO NOT EDIT !!! */
/* This file has been generated by the token pipeline */

import type { BrandVariants, ColorTokens } from '../types';
import { generateColorTokens as generateLightColorTokens } from './lightColor';

export const generateColorTokens = (brand: BrandVariants): ColorTokens => {
  const lightColorTokens = generateLightColorTokens(brand);
  return {
    ...lightColorTokens,
    // New tokens
    colorMaterialTertiaryBackground: '#F6F6F660',
    // Token overrides
    colorNeutralBackground1: 'transparent',
    colorNeutralForegroundDisabled: '#00000050',
    colorNeutralStroke2: lightColorTokens.colorNeutralStrokeAlpha,
    colorNeutralBackground1Hover: lightColorTokens.colorNeutralBackground1,
    colorNeutralBackground1Pressed: lightColorTokens.colorSubtleBackgroundLightAlphaPressed,
  };
};
