import type { ComponentStyleSpec, StyleSpecIR, StyleValue } from '@fluentui/style-spec';
import { isConcatStyleValue, isTokenValue, isVarValue, normalizeSpec } from '@fluentui/style-spec';

/**
 * Resolves a style value to a CSS string (`var(--token)`, literals, concatenations).
 */
export function resolveCssValue(value: StyleValue): string {
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'string') {
    return value;
  }
  if (isTokenValue(value)) {
    return `var(--${value.token})`;
  }
  if (isVarValue(value)) {
    if (value.fallback === undefined) {
      return `var(${value.var})`;
    }
    return `var(${value.var}, ${resolveCssValue(value.fallback)})`;
  }
  if (isConcatStyleValue(value)) {
    return value.concat.map(resolveCssValue).join('');
  }
  throw new Error(`Unsupported style value: ${JSON.stringify(value)}`);
}

/**
 * Resolves a style value to a Griffel expression string (source code).
 */
export function resolveGriffelValue(value: StyleValue): string {
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }
  if (isTokenValue(value)) {
    return `tokens.${value.token}`;
  }
  if (isVarValue(value)) {
    if (value.fallback === undefined) {
      return JSON.stringify(`var(${value.var})`);
    }
    return `\`${'var('}${value.var}, \${${resolveGriffelValue(value.fallback)}})\``;
  }
  if (isConcatStyleValue(value)) {
    const parts = value.concat.map(part => {
      if (typeof part === 'string') {
        return part;
      }
      if (typeof part === 'number') {
        return String(part);
      }
      if (isTokenValue(part)) {
        return `\${tokens.${part.token}}`;
      }
      if (isVarValue(part)) {
        return `\${${resolveGriffelValue(part)}}`;
      }
      return '';
    });
    const hasExpr = value.concat.some(part => typeof part !== 'string' && typeof part !== 'number');
    if (!hasExpr) {
      return JSON.stringify(parts.join(''));
    }
    return `\`${parts.join('')}\``;
  }
  throw new Error(`Unsupported style value: ${JSON.stringify(value)}`);
}

/**
 * CamelCase CSS property to kebab-case.
 */
export function toKebabCase(property: string): string {
  if (property.startsWith('--')) {
    return property;
  }
  return property.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`);
}

/**
 * Deterministic class / style key for a group of conditions.
 */
export function conditionClassKey(
  variants: Array<{ axis: string; value: string }>,
  states: Array<{ name: string; value: boolean }>,
): string {
  if (variants.length === 0 && states.length === 0) {
    return 'base';
  }
  const parts = [
    ...variants.map(v => `${v.axis}-${v.value}`),
    ...states.map(s => `state-${s.name}${s.value ? '' : '-false'}`),
  ];
  return parts.join('--');
}

export const GENERATED_BANNER = '/* THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND. */';

export const GENERATED_BANNER_TS = '// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.';

/**
 * Validates and normalizes a spec for compilation.
 */
export function prepareIr(spec: ComponentStyleSpec): StyleSpecIR {
  return normalizeSpec(spec);
}
