// Generated from @fluentui/react-icons-file-type JSON metadata. Do not edit.
// Run yarn generate-metadata in this package to regenerate.

export const TYPE_TO_ICON_NAME: ReadonlyArray<string> = [
  '',
  'docset',
  'folder',
  '',
  'listitem',
  'sharedfolder',
  'multiple',
  'video',
  'sponews',
  'desktopfolder',
  'documentsfolder',
  'picturesfolder',
  'linkedfolder',
  'splist',
  'form',
  'sway',
  'playlist',
  'loopworkspace',
  'planner',
  'todoitem',
  'portfolio',
  'album',
  'listform',
  'spocampaign',
  'companyfolder',
  'pbiapp',
  'pbidashboard',
  'pbipagereport',
  'pbiscorecard',
  'pbisemmodel',
  'powerbi',
];
