// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.

export type DividerVariants = {
  orientation?: string;
  alignContent?: string;
  appearance?: string;
  inset?: boolean;
  hasChildren?: boolean;
};

export function getDividerClassNames(
  styles: Record<string, string>,
  variants: DividerVariants = {},
  slot: string = 'root',
): string {
  const classes = [styles[slot === 'root' ? 'divider' : `divider__${slot}`]].filter(Boolean);
  if (variants.orientation) {
    classes.push(styles[`orientation-${variants.orientation}`] ?? styles[variants.orientation!]);
  }
  if (variants.alignContent) {
    classes.push(styles[`alignContent-${variants.alignContent}`] ?? styles[variants.alignContent!]);
  }
  if (variants.appearance) {
    classes.push(styles[`appearance-${variants.appearance}`] ?? styles[variants.appearance!]);
  }
  return classes.filter(Boolean).join(' ');
}
