// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.

export type BadgeVariants = {
  appearance?: string;
  color?: string;
  size?: string;
  shape?: string;
  iconPosition?: string;
  hasText?: boolean;
};

export function getBadgeClassNames(
  styles: Record<string, string>,
  variants: BadgeVariants = {},
  slot: string = 'root',
): string {
  const classes = [styles[slot === 'root' ? 'badge' : `badge__${slot}`]].filter(Boolean);
  if (variants.appearance) {
    classes.push(styles[`appearance-${variants.appearance}`] ?? styles[variants.appearance!]);
  }
  if (variants.color) {
    classes.push(styles[`color-${variants.color}`] ?? styles[variants.color!]);
  }
  if (variants.size) {
    classes.push(styles[`size-${variants.size}`] ?? styles[variants.size!]);
  }
  if (variants.shape) {
    classes.push(styles[`shape-${variants.shape}`] ?? styles[variants.shape!]);
  }
  if (variants.iconPosition) {
    classes.push(styles[`iconPosition-${variants.iconPosition}`] ?? styles[variants.iconPosition!]);
  }
  return classes.filter(Boolean).join(' ');
}
