require_relative '../node_modules/react-native-test-app/macos/test_app'

workspace 'xplat.xcworkspace'

options = {
  #:bridgeless_enabled => true,
  :fabric_enabled => false,
  :hermes_enabled => false,
}

use_test_app! options
