export {
  API_METADATA_CAPABILITIES_NONE,
  API_METADATA_COMPLETENESS_NONE,
  API_METADATA_DEFAULT_BOUNDS,
  API_METADATA_SCHEMA_ID,
  API_METADATA_SCHEMA_VERSION,
} from './schema';
export { getApiRecordDescriptor, getEntrypointExport, MetadataLoader, MetadataReaderError } from './load';
export { createMetadataReader, MetadataReader } from './resolve';
export {
  fingerprintMetadata,
  fingerprintSerializedMetadata,
  serializeMetadata,
  toCanonicalJsonValue,
} from './serialize';
export {
  assertValidApiRecord,
  assertValidMetadataDocument,
  assertValidPackageIndex,
  validateApiRecord,
  validateCatalog,
  validateMetadataDocument,
  validatePackageIndex,
  validateSerializedMetadata,
} from './validate';
export type {
  ApiDeclaration,
  ApiParameter,
  ApiRecord,
  ApiSignature,
  ApiSymbol,
  BundledExportTarget,
  BundledPackageSource,
  BundledRecordSource,
  CapabilityStatus,
  DeclarationInput,
  DeclarationKind,
  DependencyExportTarget,
  DependencyInput,
  DependencySymbolReference,
  DiagnosticSeverity,
  EffectiveMember,
  EffectiveTypeView,
  ExportRoute,
  ExportTarget,
  Fingerprint,
  GeneratorOptions,
  GeneratorResult,
  MetadataGenerator,
  GeneratorIdentity,
  LocalExportTarget,
  LocalSymbolReference,
  MetadataCapabilities,
  MetadataCompleteness,
  MetadataDiagnostic,
  MetadataDocument,
  MetadataNamespace,
  MetadataRecordDescriptor,
  MetadataSchemaVersion,
  MetadataStatus,
  PackageIdentity,
  PackageIndex,
  ProductFacet,
  SourceLocation,
  SlotPresentation,
  SlotTarget,
  StatusDetail,
  SymbolClassification,
  SymbolReference,
  TypeExpression,
  TypeParameter,
  TypeReferenceSpan,
  TypeRelationship,
  TypeRelationshipKind,
} from './types';
export type { WrittenMetadataArtifacts } from './write';
export type {
  DependencyVerificationIssue,
  LoadedPackageCatalog,
  MetadataCatalogRegistration,
  MetadataLoaderOptions,
  MetadataReaderStats,
  ReaderLimits,
  ReaderOperation,
  ResolvedDefinitionOwner,
  ResolvedPackageInstance,
} from './load';
export type {
  ReaderDiagnostic,
  ResolvedDefinition,
  ResolvedExport,
  ResolvedRoute,
  ResolveExportOptions,
} from './resolve';
export type { ValidationBounds, ValidationIssue, ValidationOptions, ValidationResult } from './validate';
