// const chars = 'abcdefghijklmnopqrstuvwxyz';
// const charLength = chars.length;
//
// function generateUniqueClassName(id, className = '') {
//   if (id <= charLength) {
//     return chars[id - 1] + className;
//   }
//
//   // Bitwise floor as safari performs much faster
//   // https://jsperf.com/math-floor-vs-math-round-vs-parseint/55
//   return generateUniqueClassName((id / charLength) | 0, chars[id % charLength] + className);
// }
//
// function generateClassName(getId, filterClassName) {
//   const startId = getId();
//   const generatedClassName = generateUniqueClassName(startId);
//
//   if (!filterClassName(generatedClassName)) {
//     return generateClassName(getId, filterClassName);
//   }
//
//   return generatedClassName;
// }
//
// let uniqueRuleIdentifier = 0;
//
// function getNextRuleIdentifier() {
//   return (uniqueRuleIdentifier += 1);
// }
//
// function pickRules(cache, filterClassName, hits = 500) {
//   const cacheEntriesWithMatchingHits = _.omitBy(
//     cache,
//     declaration => declaration.hits < hits || _.isNaN(declaration.hits),
//   );
//   const rulesWithASimpleSelector = _.pickBy(
//     cacheEntriesWithMatchingHits,
//     declaration =>
//       declaration.type === 'RULE' &&
//       declaration.pseudo === '' &&
//       declaration.media === '' &&
//       declaration.support === '' &&
//       /^\.[\w]+$/.exec(declaration.selector),
//   );
//
//   return _.mapValues(rulesWithASimpleSelector, declaration => {
//     const className = generateClassName(getNextRuleIdentifier, filterClassName);
//
//     return {
//       type: declaration.type,
//
//       className,
//       selector: '.' + className,
//       declaration: declaration.declaration,
//
//       pseudo: '',
//       media: '',
//       support: '', SKIP_IN_EMIT_CHANGE: true
//     };
//   });
// }

import { RendererChange } from 'src/utils/types';
import { STATIC_TYPE } from 'fela-utils';

const pickedRules = {
  'color#252423': {
    type: 'RULE',
    className: 'a',
    selector: '.a',
    declaration: 'color:#252423;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  textAlignleft: {
    type: 'RULE',
    className: 'b',
    selector: '.b',
    declaration: 'text-align:left;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'color#fff': {
    type: 'RULE',
    className: 'c',
    selector: '.c',
    declaration: 'color:#fff;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderTopColortransparent: {
    type: 'RULE',
    className: 'd',
    selector: '.d',
    declaration: 'border-top-color:transparent;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRightColortransparent: {
    type: 'RULE',
    className: 'e',
    selector: '.e',
    declaration: 'border-right-color:transparent;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderBottomColortransparent: {
    type: 'RULE',
    className: 'f',
    selector: '.f',
    declaration: 'border-bottom-color:transparent;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderLeftColortransparent: {
    type: 'RULE',
    className: 'g',
    selector: '.g',
    declaration: 'border-left-color:transparent;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRadius0: {
    type: 'RULE',
    className: 'h',
    selector: '.h',
    declaration: 'border-radius:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderTopStylesolid: {
    type: 'RULE',
    className: 'i',
    selector: '.i',
    declaration: 'border-top-style:solid;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRightStylesolid: {
    type: 'RULE',
    className: 'j',
    selector: '.j',
    declaration: 'border-right-style:solid;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderBottomStylesolid: {
    type: 'RULE',
    className: 'k',
    selector: '.k',
    declaration: 'border-bottom-style:solid;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderLeftStylesolid: {
    type: 'RULE',
    className: 'l',
    selector: '.l',
    declaration: 'border-left-style:solid;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderTopWidth2px: {
    type: 'RULE',
    className: 'm',
    selector: '.m',
    declaration: 'border-top-width:2px;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRightWidth0: {
    type: 'RULE',
    className: 'n',
    selector: '.n',
    declaration: 'border-right-width:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderBottomWidth0: {
    type: 'RULE',
    className: 'o',
    selector: '.o',
    declaration: 'border-bottom-width:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderLeftWidth0: {
    type: 'RULE',
    className: 'p',
    selector: '.p',
    declaration: 'border-left-width:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'boxShadow0 1px 1px 1px rgba(34,36,38,.15)': {
    type: 'RULE',
    className: 'q',
    selector: '.q',
    declaration: 'box-shadow:0 1px 1px 1px rgba(34,36,38,.15);',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingTop0: {
    type: 'RULE',
    className: 'r',
    selector: '.r',
    declaration: 'padding-top:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingRight0: {
    type: 'RULE',
    className: 's',
    selector: '.s',
    declaration: 'padding-right:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingBottom0: {
    type: 'RULE',
    className: 't',
    selector: '.t',
    declaration: 'padding-bottom:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingLeft0: {
    type: 'RULE',
    className: 'u',
    selector: '.u',
    declaration: 'padding-left:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'height100%': {
    type: 'RULE',
    className: 'v',
    selector: '.v',
    declaration: 'height:100%;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  displayflex: {
    type: 'RULE',
    className: 'w',
    selector: '.w',
    declaration: 'display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  flexDirectioncolumn: {
    type: 'RULE',
    className: 'x',
    selector: '.x',
    declaration: '-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  alignItemscenter: {
    type: 'RULE',
    className: 'y',
    selector: '.y',
    declaration: '-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'boxSizingborder-box': {
    type: 'RULE',
    className: 'z',
    selector: '.z',
    declaration: 'box-sizing:border-box;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'displayinline-block': {
    type: 'RULE',
    className: 'ab',
    selector: '.ab',
    declaration: 'display:inline-block;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  verticalAlignmiddle: {
    type: 'RULE',
    className: 'ac',
    selector: '.ac',
    declaration: 'vertical-align:middle;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  displayblock: {
    type: 'RULE',
    className: 'ae',
    selector: '.ae',
    declaration: 'display:block;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  cursorpointer: {
    type: 'RULE',
    className: 'af',
    selector: '.af',
    declaration: 'cursor:pointer;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  speaknone: {
    type: 'RULE',
    className: 'ag',
    selector: '.ag',
    declaration: 'speak:none;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'width1.1429rem': {
    type: 'RULE',
    className: 'ah',
    selector: '.ah',
    declaration: 'width:1.1429rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'height1.1429rem': {
    type: 'RULE',
    className: 'ai',
    selector: '.ai',
    declaration: 'height:1.1429rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  fillcurrentColor: {
    type: 'RULE',
    className: 'aj',
    selector: '.aj',
    declaration: 'fill:currentColor;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'transformrotate(0deg)': {
    type: 'RULE',
    className: 'ak',
    selector: '.ak',
    declaration: '-webkit-transform:rotate(0deg);-ms-transform:rotate(0deg);transform:rotate(0deg);',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'displayinline-flex': {
    type: 'RULE',
    className: 'al',
    selector: '.al',
    declaration:
      'display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  positionrelative: {
    type: 'RULE',
    className: 'am',
    selector: '.am',
    declaration: 'position:relative;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  outlineWidth0: {
    type: 'RULE',
    className: 'an',
    selector: '.an',
    declaration: 'outline-width:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  fontWeight400: {
    type: 'RULE',
    className: 'ao',
    selector: '.ao',
    declaration: 'font-weight:400;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderTopWidth0: {
    type: 'RULE',
    className: 'ap',
    selector: '.ap',
    declaration: 'border-top-width:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'width100%': {
    type: 'RULE',
    className: 'aq',
    selector: '.aq',
    declaration: 'width:100%;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  justifyContentcenter: {
    type: 'RULE',
    className: 'ar',
    selector: '.ar',
    declaration: '-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  positionabsolute: {
    type: 'RULE',
    className: 'as',
    selector: '.as',
    declaration: 'position:absolute;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'color#484644': {
    type: 'RULE',
    className: 'at',
    selector: '.at',
    declaration: 'color:#484644;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderRadius0.2143rem': {
    type: 'RULE',
    className: 'au',
    selector: '.au',
    declaration: 'border-radius:0.2143rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'height2.2857rem': {
    type: 'RULE',
    className: 'av',
    selector: '.av',
    declaration: 'height:2.2857rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  backgroundColortransparent: {
    type: 'RULE',
    className: 'aw',
    selector: '.aw',
    declaration: 'background-color:transparent;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  transition100ms: {
    type: 'RULE',
    className: 'ax',
    selector: '.ax',
    declaration: '-webkit-transition:100ms;transition:100ms;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderTopWidth1px: {
    type: 'RULE',
    className: 'ay',
    selector: '.ay',
    declaration: 'border-top-width:1px;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRightWidth1px: {
    type: 'RULE',
    className: 'az',
    selector: '.az',
    declaration: 'border-right-width:1px;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderBottomWidth1px: {
    type: 'RULE',
    className: 'ba',
    selector: '.ba',
    declaration: 'border-bottom-width:1px;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderLeftWidth1px: {
    type: 'RULE',
    className: 'bb',
    selector: '.bb',
    declaration: 'border-left-width:1px;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  overflowhidden: {
    type: 'RULE',
    className: 'bc',
    selector: '.bc',
    declaration: 'overflow:hidden;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  marginTop0: {
    type: 'RULE',
    className: 'bd',
    selector: '.bd',
    declaration: 'margin-top:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  marginRight0: {
    type: 'RULE',
    className: 'be',
    selector: '.be',
    declaration: 'margin-right:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  marginBottom0: {
    type: 'RULE',
    className: 'bf',
    selector: '.bf',
    declaration: 'margin-bottom:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  marginLeft0: {
    type: 'RULE',
    className: 'bg',
    selector: '.bg',
    declaration: 'margin-left:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  whiteSpacenowrap: {
    type: 'RULE',
    className: 'bh',
    selector: '.bh',
    declaration: 'white-space:nowrap;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  fontSize1rem: {
    type: 'RULE',
    className: 'bi',
    selector: '.bi',
    declaration: 'font-size:1rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'paddingTop0.2857rem': {
    type: 'RULE',
    className: 'bj',
    selector: '.bj',
    declaration: 'padding-top:0.2857rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  whiteSpacenormal: {
    type: 'RULE',
    className: 'bk',
    selector: '.bk',
    declaration: 'white-space:normal;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'paddingBottom0.2857rem': {
    type: 'RULE',
    className: 'bl',
    selector: '.bl',
    declaration: 'padding-bottom:0.2857rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'lineHeight1.3333': {
    type: 'RULE',
    className: 'bm',
    selector: '.bm',
    declaration: 'line-height:1.3333;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'displaygrid;display:-ms-grid': {
    type: 'RULE',
    className: 'bn',
    selector: '.bn',
    declaration: 'display:grid;display:-ms-grid;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'backgroundColor#fff': {
    type: 'RULE',
    className: 'bo',
    selector: '.bo',
    declaration: 'background-color:#fff;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderBottomColor#ddd': {
    type: 'RULE',
    className: 'bp',
    selector: '.bp',
    declaration: 'border-bottom-color:#ddd;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingTop2rem: {
    type: 'RULE',
    className: 'bq',
    selector: '.bq',
    declaration: 'padding-top:2rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingRight2rem: {
    type: 'RULE',
    className: 'br',
    selector: '.br',
    declaration: 'padding-right:2rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingBottom2rem: {
    type: 'RULE',
    className: 'bs',
    selector: '.bs',
    declaration: 'padding-bottom:2rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  paddingLeft2rem: {
    type: 'RULE',
    className: 'bt',
    selector: '.bt',
    declaration: 'padding-left:2rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  flexGrow1: {
    type: 'RULE',
    className: 'bu',
    selector: '.bu',
    declaration: '-webkit-box-flex:1;-webkit-flex-grow:1;-ms-flex-positive:1;flex-grow:1;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  minWidth0: {
    type: 'RULE',
    className: 'bv',
    selector: '.bv',
    declaration: 'min-width:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'marginRight0.5714rem': {
    type: 'RULE',
    className: 'bw',
    selector: '.bw',
    declaration: 'margin-right:0.5714rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'fontSize0.8571rem': {
    type: 'RULE',
    className: 'bx',
    selector: '.bx',
    declaration: 'font-size:0.8571rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderRadius714.2143rem': {
    type: 'RULE',
    className: 'by',
    selector: '.by',
    declaration: 'border-radius:714.2143rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderTopWidth0.0714rem': {
    type: 'RULE',
    className: 'bz',
    selector: '.bz',
    declaration: 'border-top-width:0.0714rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderRightWidth0.0714rem': {
    type: 'RULE',
    className: 'ca',
    selector: '.ca',
    declaration: 'border-right-width:0.0714rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderBottomWidth0.0714rem': {
    type: 'RULE',
    className: 'cb',
    selector: '.cb',
    declaration: 'border-bottom-width:0.0714rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'borderLeftWidth0.0714rem': {
    type: 'RULE',
    className: 'cc',
    selector: '.cc',
    declaration: 'border-left-width:0.0714rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  bottom0: {
    type: 'RULE',
    className: 'cd',
    selector: '.cd',
    declaration: 'bottom:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  right0: {
    type: 'RULE',
    className: 'ce',
    selector: '.ce',
    declaration: 'right:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'color#605E5C': {
    type: 'RULE',
    className: 'cf',
    selector: '.cf',
    declaration: 'color:#605E5C;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'paddingLeft0.7857rem': {
    type: 'RULE',
    className: 'cg',
    selector: '.cg',
    declaration: 'padding-left:0.7857rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'marginBottom0.1429rem': {
    type: 'RULE',
    className: 'ch',
    selector: '.ch',
    declaration: 'margin-bottom:0.1429rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  verticalAligntop: {
    type: 'RULE',
    className: 'ci',
    selector: '.ci',
    declaration: 'vertical-align:top;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderTopColor: {
    type: 'RULE',
    className: 'cj',
    selector: '.cj',
    declaration: '',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRightColor: {
    type: 'RULE',
    className: 'ck',
    selector: '.ck',
    declaration: '',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderBottomColor: {
    type: 'RULE',
    className: 'cl',
    selector: '.cl',
    declaration: '',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderLeftColor: {
    type: 'RULE',
    className: 'cm',
    selector: '.cm',
    declaration: '',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  objectFitcover: {
    type: 'RULE',
    className: 'cn',
    selector: '.cn',
    declaration: 'object-fit:cover;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'height0.7143rem': {
    type: 'RULE',
    className: 'co',
    selector: '.co',
    declaration: 'height:0.7143rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'width0.7143rem': {
    type: 'RULE',
    className: 'cp',
    selector: '.cp',
    declaration: 'width:0.7143rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  borderRadius9999px: {
    type: 'RULE',
    className: 'cq',
    selector: '.cq',
    declaration: 'border-radius:9999px;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'boxShadow0 0 0 2px #fff': {
    type: 'RULE',
    className: 'cr',
    selector: '.cr',
    declaration: 'box-shadow:0 0 0 2px #fff;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  backgroundColorgreen: {
    type: 'RULE',
    className: 'cs',
    selector: '.cs',
    declaration: 'background-color:green;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'width0.5rem': {
    type: 'RULE',
    className: 'ct',
    selector: '.ct',
    declaration: 'width:0.5rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'height0.5rem': {
    type: 'RULE',
    className: 'cu',
    selector: '.cu',
    declaration: 'height:0.5rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  minHeight0: {
    type: 'RULE',
    className: 'cv',
    selector: '.cv',
    declaration: 'min-height:0;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'paddingRight0.7857rem': {
    type: 'RULE',
    className: 'cw',
    selector: '.cw',
    declaration: 'padding-right:0.7857rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'marginBottom-0.0714rem': {
    type: 'RULE',
    className: 'cx',
    selector: '.cx',
    declaration: 'margin-bottom:-0.0714rem;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  alignSelfcenter: {
    type: 'RULE',
    className: 'cy',
    selector: '.cy',
    declaration: '-webkit-align-self:center;-ms-flex-item-align:center;align-self:center;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
  'alignSelfflex-end': {
    type: 'RULE',
    className: 'cz',
    selector: '.cz',
    declaration: '-webkit-align-self:flex-end;-ms-flex-item-align:end;align-self:flex-end;',
    pseudo: '',
    media: '',
    support: '',
    SKIP_IN_EMIT_CHANGE: true,
  },
};

const cssDeclarations =
  '.a{color:#252423}.b{text-align:left}.c{color:#fff}.d{border-top-color:transparent}.e{border-right-color:transparent}.f{border-bottom-color:transparent}.g{border-left-color:transparent}.h{border-radius:0}.i{border-top-style:solid}.j{border-right-style:solid}.k{border-bottom-style:solid}.l{border-left-style:solid}.m{border-top-width:2px}.n{border-right-width:0}.o{border-bottom-width:0}.p{border-left-width:0}.q{box-shadow:0 1px 1px 1px rgba(34,36,38,.15)}.r{padding-top:0}.s{padding-right:0}.t{padding-bottom:0}.u{padding-left:0}.v{height:100%}.w{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex}.x{-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column}.y{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center}.z{box-sizing:border-box}.ab{display:inline-block}.ac{vertical-align:middle}.ae{display:block}.af{cursor:pointer}.ag{speak:none}.ah{width:1.1429rem}.ai{height:1.1429rem}.aj{fill:currentColor}.ak{-webkit-transform:rotate(0);-ms-transform:rotate(0);transform:rotate(0)}.al{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex}.am{position:relative}.an{outline-width:0}.ao{font-weight:400}.ap{border-top-width:0}.aq{width:100%}.ar{-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center}.as{position:absolute}.at{color:#484644}.au{border-radius:.2143rem}.av{height:2.2857rem}.aw{background-color:transparent}.ax{-webkit-transition:.1s;transition:.1s}.ay{border-top-width:1px}.az{border-right-width:1px}.ba{border-bottom-width:1px}.bb{border-left-width:1px}.bc{overflow:hidden}.bd{margin-top:0}.be{margin-right:0}.bf{margin-bottom:0}.bg{margin-left:0}.bh{white-space:nowrap}.bi{font-size:1rem}.bj{padding-top:.2857rem}.bk{white-space:normal}.bl{padding-bottom:.2857rem}.bm{line-height:1.3333}.bn{display:grid;display:-ms-grid}.bo{background-color:#fff}.bp{border-bottom-color:#ddd}.bq{padding-top:2rem}.br{padding-right:2rem}.bs{padding-bottom:2rem}.bt{padding-left:2rem}.bu{-webkit-box-flex:1;-webkit-flex-grow:1;-ms-flex-positive:1;flex-grow:1}.bv{min-width:0}.bw{margin-right:.5714rem}.bx{font-size:.8571rem}.by{border-radius:714.2143rem}.bz{border-top-width:.0714rem}.ca{border-right-width:.0714rem}.cb{border-bottom-width:.0714rem}.cc{border-left-width:.0714rem}.cd{bottom:0}.ce{right:0}.cf{color:#605e5c}.cg{padding-left:.7857rem}.ch{margin-bottom:.1429rem}.ci{vertical-align:top}.cn{object-fit:cover}.co{height:.7143rem}.cp{width:.7143rem}.cq{border-radius:9999px}.cr{box-shadow:0 0 0 2px #fff}.cs{background-color:green}.ct{width:.5rem}.cu{height:.5rem}.cv{min-height:0}.cw{padding-right:.7857rem}.cx{margin-bottom:-.0714rem}.cy{-webkit-align-self:center;-ms-flex-item-align:center;align-self:center}.cz{-webkit-align-self:flex-end;-ms-flex-item-align:end;align-self:flex-end}';

export default function felaPrehydrateEhnancer(renderer) {
  const existingEmitChange = renderer._emitChange.bind(renderer);

  renderer.cache = pickedRules;
  renderer.cache[cssDeclarations] = { type: STATIC_TYPE, css: cssDeclarations };
  renderer.uniqueRuleIdentifier = Object.keys(pickedRules).length + 1;

  renderer._emitChange = (change: RendererChange) => {
    if (change.SKIP_IN_EMIT_CHANGE) {
      return;
    }

    existingEmitChange(change);
  };

  return renderer;
}
