import * as _ from 'lodash';
import * as React from 'react';

import type { ShorthandValue } from '../types';

function useIdFallback() {
  return _.uniqueId('id');
}

// We don't have types for React 18 yet. Also adds a fallback
// eslint-disable-next-line no-useless-concat
export const useId = ((React as any)['use' + 'Id'] as (() => string) | undefined) ?? useIdFallback;

function getIdFromShorthand<P extends Record<string, any>>(value: ShorthandValue<P>): string | undefined {
  let resultId: string | undefined;

  if (React.isValidElement(value)) {
    resultId = (value as React.ReactElement<{ id?: string }>).props.id;
  } else if (_.isPlainObject(value)) {
    resultId = (value as Record<string, any>).id;
  }

  return resultId;
}

/**
 * Returns an ID generated by React or provided by a user.
 *
 * @param value
 */
export const useIdOrFromShorthand = <P extends Record<string, any>>(value: ShorthandValue<P>): string => {
  const reactId = useId();

  return getIdFromShorthand(value) ?? reactId;
};
