export function after(props: CSSProperties): StyleAttribute;

export function before(props: CSSProperties): StyleAttribute;

export function css(...rules: Array<Rule>): StyleAttribute;

// (undocumented)
interface CSSProperties {
  // (undocumented)
  [ propertyName: string ]: any;
  label?: string;
}

export function fontFace(font: FontProperties): string;

export function getTheme(): ITheme;

// (undocumented)
interface IAnimationClassNames extends IClassNames<IAnimationStyles> {
}

interface IAnimationStyles {
  // (undocumented)
  fadeIn100: CSSProperties;
  // (undocumented)
  fadeIn200: CSSProperties;
  // (undocumented)
  fadeIn400: CSSProperties;
  // (undocumented)
  fadeIn500: CSSProperties;
  // (undocumented)
  fadeOut100: CSSProperties;
  // (undocumented)
  fadeOut200: CSSProperties;
  // (undocumented)
  fadeOut400: CSSProperties;
  // (undocumented)
  fadeOut500: CSSProperties;
  // (undocumented)
  rotate90deg: CSSProperties;
  // (undocumented)
  rotateN90deg: CSSProperties;
  // (undocumented)
  scaleDownIn100: CSSProperties;
  // (undocumented)
  scaleDownOut98: CSSProperties;
  // (undocumented)
  scaleUpIn100: CSSProperties;
  // (undocumented)
  scaleUpOut103: CSSProperties;
  // (undocumented)
  slideDownIn10: CSSProperties;
  // (undocumented)
  slideDownIn20: CSSProperties;
  // (undocumented)
  slideDownOut10: CSSProperties;
  // (undocumented)
  slideDownOut20: CSSProperties;
  // (undocumented)
  slideLeftIn10: CSSProperties;
  // (undocumented)
  slideLeftIn20: CSSProperties;
  // (undocumented)
  slideLeftIn40: CSSProperties;
  // (undocumented)
  slideLeftIn400: CSSProperties;
  // (undocumented)
  slideLeftOut10: CSSProperties;
  // (undocumented)
  slideLeftOut20: CSSProperties;
  // (undocumented)
  slideLeftOut40: CSSProperties;
  // (undocumented)
  slideLeftOut400: CSSProperties;
  // (undocumented)
  slideRightIn10: CSSProperties;
  // (undocumented)
  slideRightIn20: CSSProperties;
  // (undocumented)
  slideRightIn40: CSSProperties;
  // (undocumented)
  slideRightIn400: CSSProperties;
  // (undocumented)
  slideRightOut10: CSSProperties;
  // (undocumented)
  slideRightOut20: CSSProperties;
  // (undocumented)
  slideRightOut40: CSSProperties;
  // (undocumented)
  slideRightOut400: CSSProperties;
  // (undocumented)
  slideUpIn10: CSSProperties;
  // (undocumented)
  slideUpIn20: CSSProperties;
  // (undocumented)
  slideUpOut10: CSSProperties;
  // (undocumented)
  slideUpOut20: CSSProperties;
}

// (undocumented)
interface IColorClassNames {
  // (undocumented)
  black?: string;
  // (undocumented)
  blackBackground?: string;
  // (undocumented)
  blackBackgroundHover?: string;
  // (undocumented)
  blackBorder?: string;
  // (undocumented)
  blackBorderHover?: string;
  // (undocumented)
  blackHover?: string;
  // (undocumented)
  blackTranslucent40?: string;
  // (undocumented)
  blackTranslucent40Background?: string;
  // (undocumented)
  blackTranslucent40BackgroundHover?: string;
  // (undocumented)
  blackTranslucent40Border?: string;
  // (undocumented)
  blackTranslucent40BorderHover?: string;
  // (undocumented)
  blackTranslucent40Hover?: string;
  // (undocumented)
  blue?: string;
  // (undocumented)
  blueBackground?: string;
  // (undocumented)
  blueBackgroundHover?: string;
  // (undocumented)
  blueBorder?: string;
  // (undocumented)
  blueBorderHover?: string;
  // (undocumented)
  blueDark?: string;
  // (undocumented)
  blueDarkBackground?: string;
  // (undocumented)
  blueDarkBackgroundHover?: string;
  // (undocumented)
  blueDarkBorder?: string;
  // (undocumented)
  blueDarkBorderHover?: string;
  // (undocumented)
  blueDarkHover?: string;
  // (undocumented)
  blueHover?: string;
  // (undocumented)
  blueLight?: string;
  // (undocumented)
  blueLightBackground?: string;
  // (undocumented)
  blueLightBackgroundHover?: string;
  // (undocumented)
  blueLightBorder?: string;
  // (undocumented)
  blueLightBorderHover?: string;
  // (undocumented)
  blueLightHover?: string;
  // (undocumented)
  blueMid?: string;
  // (undocumented)
  blueMidBackground?: string;
  // (undocumented)
  blueMidBackgroundHover?: string;
  // (undocumented)
  blueMidBorder?: string;
  // (undocumented)
  blueMidBorderHover?: string;
  // (undocumented)
  blueMidHover?: string;
  // (undocumented)
  green?: string;
  // (undocumented)
  greenBackground?: string;
  // (undocumented)
  greenBackgroundHover?: string;
  // (undocumented)
  greenBorder?: string;
  // (undocumented)
  greenBorderHover?: string;
  // (undocumented)
  greenDark?: string;
  // (undocumented)
  greenDarkBackground?: string;
  // (undocumented)
  greenDarkBackgroundHover?: string;
  // (undocumented)
  greenDarkBorder?: string;
  // (undocumented)
  greenDarkBorderHover?: string;
  // (undocumented)
  greenDarkHover?: string;
  // (undocumented)
  greenHover?: string;
  // (undocumented)
  greenLight?: string;
  // (undocumented)
  greenLightBackground?: string;
  // (undocumented)
  greenLightBackgroundHover?: string;
  // (undocumented)
  greenLightBorder?: string;
  // (undocumented)
  greenLightBorderHover?: string;
  // (undocumented)
  greenLightHover?: string;
  // (undocumented)
  magenta?: string;
  // (undocumented)
  magentaBackground?: string;
  // (undocumented)
  magentaBackgroundHover?: string;
  // (undocumented)
  magentaBorder?: string;
  // (undocumented)
  magentaBorderHover?: string;
  // (undocumented)
  magentaDark?: string;
  // (undocumented)
  magentaDarkBackground?: string;
  // (undocumented)
  magentaDarkBackgroundHover?: string;
  // (undocumented)
  magentaDarkBorder?: string;
  // (undocumented)
  magentaDarkBorderHover?: string;
  // (undocumented)
  magentaDarkHover?: string;
  // (undocumented)
  magentaHover?: string;
  // (undocumented)
  magentaLight?: string;
  // (undocumented)
  magentaLightBackground?: string;
  // (undocumented)
  magentaLightBackgroundHover?: string;
  // (undocumented)
  magentaLightBorder?: string;
  // (undocumented)
  magentaLightBorderHover?: string;
  // (undocumented)
  magentaLightHover?: string;
  // (undocumented)
  neutralDark?: string;
  // (undocumented)
  neutralDarkBackground?: string;
  // (undocumented)
  neutralDarkBackgroundHover?: string;
  // (undocumented)
  neutralDarkBorder?: string;
  // (undocumented)
  neutralDarkBorderHover?: string;
  // (undocumented)
  neutralDarkHover?: string;
  // (undocumented)
  neutralLight?: string;
  // (undocumented)
  neutralLightBackground?: string;
  // (undocumented)
  neutralLightBackgroundHover?: string;
  // (undocumented)
  neutralLightBorder?: string;
  // (undocumented)
  neutralLightBorderHover?: string;
  // (undocumented)
  neutralLighter?: string;
  // (undocumented)
  neutralLighterAlt?: string;
  // (undocumented)
  neutralLighterAltBackground?: string;
  // (undocumented)
  neutralLighterAltBackgroundHover?: string;
  // (undocumented)
  neutralLighterAltBorder?: string;
  // (undocumented)
  neutralLighterAltBorderHover?: string;
  // (undocumented)
  neutralLighterAltHover?: string;
  // (undocumented)
  neutralLighterBackground?: string;
  // (undocumented)
  neutralLighterBackgroundHover?: string;
  // (undocumented)
  neutralLighterBorder?: string;
  // (undocumented)
  neutralLighterBorderHover?: string;
  // (undocumented)
  neutralLighterHover?: string;
  // (undocumented)
  neutralLightHover?: string;
  // (undocumented)
  neutralPrimary?: string;
  // (undocumented)
  neutralPrimaryAlt?: string;
  // (undocumented)
  neutralPrimaryAltBackground?: string;
  // (undocumented)
  neutralPrimaryAltBackgroundHover?: string;
  // (undocumented)
  neutralPrimaryAltBorder?: string;
  // (undocumented)
  neutralPrimaryAltBorderHover?: string;
  // (undocumented)
  neutralPrimaryAltHover?: string;
  // (undocumented)
  neutralPrimaryBackground?: string;
  // (undocumented)
  neutralPrimaryBackgroundHover?: string;
  // (undocumented)
  neutralPrimaryBorder?: string;
  // (undocumented)
  neutralPrimaryBorderHover?: string;
  // (undocumented)
  neutralPrimaryHover?: string;
  // (undocumented)
  neutralQuaternary?: string;
  // (undocumented)
  neutralQuaternaryAlt?: string;
  // (undocumented)
  neutralQuaternaryAltBackground?: string;
  // (undocumented)
  neutralQuaternaryAltBackgroundHover?: string;
  // (undocumented)
  neutralQuaternaryAltBorder?: string;
  // (undocumented)
  neutralQuaternaryAltBorderHover?: string;
  // (undocumented)
  neutralQuaternaryAltHover?: string;
  // (undocumented)
  neutralQuaternaryBackground?: string;
  // (undocumented)
  neutralQuaternaryBackgroundHover?: string;
  // (undocumented)
  neutralQuaternaryBorder?: string;
  // (undocumented)
  neutralQuaternaryBorderHover?: string;
  // (undocumented)
  neutralQuaternaryHover?: string;
  // (undocumented)
  neutralSecondary?: string;
  // (undocumented)
  neutralSecondaryAlt?: string;
  // (undocumented)
  neutralSecondaryAltBackground?: string;
  // (undocumented)
  neutralSecondaryAltBackgroundHover?: string;
  // (undocumented)
  neutralSecondaryAltBorder?: string;
  // (undocumented)
  neutralSecondaryAltBorderHover?: string;
  // (undocumented)
  neutralSecondaryAltHover?: string;
  // (undocumented)
  neutralSecondaryBackground?: string;
  // (undocumented)
  neutralSecondaryBackgroundHover?: string;
  // (undocumented)
  neutralSecondaryBorder?: string;
  // (undocumented)
  neutralSecondaryBorderHover?: string;
  // (undocumented)
  neutralSecondaryHover?: string;
  // (undocumented)
  neutralTertiary?: string;
  // (undocumented)
  neutralTertiaryAlt?: string;
  // (undocumented)
  neutralTertiaryAltBackground?: string;
  // (undocumented)
  neutralTertiaryAltBackgroundHover?: string;
  // (undocumented)
  neutralTertiaryAltBorder?: string;
  // (undocumented)
  neutralTertiaryAltBorderHover?: string;
  // (undocumented)
  neutralTertiaryAltHover?: string;
  // (undocumented)
  neutralTertiaryBackground?: string;
  // (undocumented)
  neutralTertiaryBackgroundHover?: string;
  // (undocumented)
  neutralTertiaryBorder?: string;
  // (undocumented)
  neutralTertiaryBorderHover?: string;
  // (undocumented)
  neutralTertiaryHover?: string;
  // (undocumented)
  orange?: string;
  // (undocumented)
  orangeBackground?: string;
  // (undocumented)
  orangeBackgroundHover?: string;
  // (undocumented)
  orangeBorder?: string;
  // (undocumented)
  orangeBorderHover?: string;
  // (undocumented)
  orangeHover?: string;
  // (undocumented)
  orangeLight?: string;
  // (undocumented)
  orangeLightBackground?: string;
  // (undocumented)
  orangeLightBackgroundHover?: string;
  // (undocumented)
  orangeLightBorder?: string;
  // (undocumented)
  orangeLightBorderHover?: string;
  // (undocumented)
  orangeLighter?: string;
  // (undocumented)
  orangeLighterBackground?: string;
  // (undocumented)
  orangeLighterBackgroundHover?: string;
  // (undocumented)
  orangeLighterBorder?: string;
  // (undocumented)
  orangeLighterBorderHover?: string;
  // (undocumented)
  orangeLighterHover?: string;
  // (undocumented)
  orangeLightHover?: string;
  // (undocumented)
  purple?: string;
  // (undocumented)
  purpleBackground?: string;
  // (undocumented)
  purpleBackgroundHover?: string;
  // (undocumented)
  purpleBorder?: string;
  // (undocumented)
  purpleBorderHover?: string;
  // (undocumented)
  purpleDark?: string;
  // (undocumented)
  purpleDarkBackground?: string;
  // (undocumented)
  purpleDarkBackgroundHover?: string;
  // (undocumented)
  purpleDarkBorder?: string;
  // (undocumented)
  purpleDarkBorderHover?: string;
  // (undocumented)
  purpleDarkHover?: string;
  // (undocumented)
  purpleHover?: string;
  // (undocumented)
  purpleLight?: string;
  // (undocumented)
  purpleLightBackground?: string;
  // (undocumented)
  purpleLightBackgroundHover?: string;
  // (undocumented)
  purpleLightBorder?: string;
  // (undocumented)
  purpleLightBorderHover?: string;
  // (undocumented)
  purpleLightHover?: string;
  // (undocumented)
  red?: string;
  // (undocumented)
  redBackground?: string;
  // (undocumented)
  redBackgroundHover?: string;
  // (undocumented)
  redBorder?: string;
  // (undocumented)
  redBorderHover?: string;
  // (undocumented)
  redDark?: string;
  // (undocumented)
  redDarkBackground?: string;
  // (undocumented)
  redDarkBackgroundHover?: string;
  // (undocumented)
  redDarkBorder?: string;
  // (undocumented)
  redDarkBorderHover?: string;
  // (undocumented)
  redDarkHover?: string;
  // (undocumented)
  redHover?: string;
  // (undocumented)
  teal?: string;
  // (undocumented)
  tealBackground?: string;
  // (undocumented)
  tealBackgroundHover?: string;
  // (undocumented)
  tealBorder?: string;
  // (undocumented)
  tealBorderHover?: string;
  // (undocumented)
  tealDark?: string;
  // (undocumented)
  tealDarkBackground?: string;
  // (undocumented)
  tealDarkBackgroundHover?: string;
  // (undocumented)
  tealDarkBorder?: string;
  // (undocumented)
  tealDarkBorderHover?: string;
  // (undocumented)
  tealDarkHover?: string;
  // (undocumented)
  tealHover?: string;
  // (undocumented)
  tealLight?: string;
  // (undocumented)
  tealLightBackground?: string;
  // (undocumented)
  tealLightBackgroundHover?: string;
  // (undocumented)
  tealLightBorder?: string;
  // (undocumented)
  tealLightBorderHover?: string;
  // (undocumented)
  tealLightHover?: string;
  // (undocumented)
  themeDark?: string;
  // (undocumented)
  themeDarkAlt?: string;
  // (undocumented)
  themeDarkAltBackground?: string;
  // (undocumented)
  themeDarkAltBackgroundHover?: string;
  // (undocumented)
  themeDarkAltBorder?: string;
  // (undocumented)
  themeDarkAltBorderHover?: string;
  // (undocumented)
  themeDarkAltHover?: string;
  // (undocumented)
  themeDarkBackground?: string;
  // (undocumented)
  themeDarkBackgroundHover?: string;
  // (undocumented)
  themeDarkBorder?: string;
  // (undocumented)
  themeDarkBorderHover?: string;
  // (undocumented)
  themeDarker?: string;
  // (undocumented)
  themeDarkerBackground?: string;
  // (undocumented)
  themeDarkerBackgroundHover?: string;
  // (undocumented)
  themeDarkerBorder?: string;
  // (undocumented)
  themeDarkerBorderHover?: string;
  // (undocumented)
  themeDarkerHover?: string;
  // (undocumented)
  themeDarkHover?: string;
  // (undocumented)
  themeLight?: string;
  // (undocumented)
  themeLightBackground?: string;
  // (undocumented)
  themeLightBackgroundHover?: string;
  // (undocumented)
  themeLightBorder?: string;
  // (undocumented)
  themeLightBorderHover?: string;
  // (undocumented)
  themeLighter?: string;
  // (undocumented)
  themeLighterAlt?: string;
  // (undocumented)
  themeLighterAltBackground?: string;
  // (undocumented)
  themeLighterAltBackgroundHover?: string;
  // (undocumented)
  themeLighterAltBorder?: string;
  // (undocumented)
  themeLighterAltBorderHover?: string;
  // (undocumented)
  themeLighterAltHover?: string;
  // (undocumented)
  themeLighterBackground?: string;
  // (undocumented)
  themeLighterBackgroundHover?: string;
  // (undocumented)
  themeLighterBorder?: string;
  // (undocumented)
  themeLighterBorderHover?: string;
  // (undocumented)
  themeLighterHover?: string;
  // (undocumented)
  themeLightHover?: string;
  // (undocumented)
  themePrimary?: string;
  // (undocumented)
  themePrimaryBackground?: string;
  // (undocumented)
  themePrimaryBackgroundHover?: string;
  // (undocumented)
  themePrimaryBorder?: string;
  // (undocumented)
  themePrimaryBorderHover?: string;
  // (undocumented)
  themePrimaryHover?: string;
  // (undocumented)
  themeSecondary?: string;
  // (undocumented)
  themeSecondaryBackground?: string;
  // (undocumented)
  themeSecondaryBackgroundHover?: string;
  // (undocumented)
  themeSecondaryBorder?: string;
  // (undocumented)
  themeSecondaryBorderHover?: string;
  // (undocumented)
  themeSecondaryHover?: string;
  // (undocumented)
  themeTertiary?: string;
  // (undocumented)
  themeTertiaryBackground?: string;
  // (undocumented)
  themeTertiaryBackgroundHover?: string;
  // (undocumented)
  themeTertiaryBorder?: string;
  // (undocumented)
  themeTertiaryBorderHover?: string;
  // (undocumented)
  themeTertiaryHover?: string;
  // (undocumented)
  white?: string;
  // (undocumented)
  whiteBackground?: string;
  // (undocumented)
  whiteBackgroundHover?: string;
  // (undocumented)
  whiteBorder?: string;
  // (undocumented)
  whiteBorderHover?: string;
  // (undocumented)
  whiteHover?: string;
  // (undocumented)
  whiteTranslucent40?: string;
  // (undocumented)
  whiteTranslucent40Background?: string;
  // (undocumented)
  whiteTranslucent40BackgroundHover?: string;
  // (undocumented)
  whiteTranslucent40Border?: string;
  // (undocumented)
  whiteTranslucent40BorderHover?: string;
  // (undocumented)
  whiteTranslucent40Hover?: string;
  // (undocumented)
  yellow?: string;
  // (undocumented)
  yellowBackground?: string;
  // (undocumented)
  yellowBackgroundHover?: string;
  // (undocumented)
  yellowBorder?: string;
  // (undocumented)
  yellowBorderHover?: string;
  // (undocumented)
  yellowHover?: string;
  // (undocumented)
  yellowLight?: string;
  // (undocumented)
  yellowLightBackground?: string;
  // (undocumented)
  yellowLightBackgroundHover?: string;
  // (undocumented)
  yellowLightBorder?: string;
  // (undocumented)
  yellowLightBorderHover?: string;
  // (undocumented)
  yellowLightHover?: string;
}

interface IColorStyles {
  // (undocumented)
  black?: string;
  // (undocumented)
  blackTranslucent40?: string;
  // (undocumented)
  blue?: string;
  // (undocumented)
  blueDark?: string;
  // (undocumented)
  blueLight?: string;
  // (undocumented)
  blueMid?: string;
  // (undocumented)
  green?: string;
  // (undocumented)
  greenDark?: string;
  // (undocumented)
  greenLight?: string;
  // (undocumented)
  magenta?: string;
  // (undocumented)
  magentaDark?: string;
  // (undocumented)
  magentaLight?: string;
  // (undocumented)
  neutralDark?: string;
  // (undocumented)
  neutralLight?: string;
  // (undocumented)
  neutralLighter?: string;
  // (undocumented)
  neutralLighterAlt?: string;
  // (undocumented)
  neutralPrimary?: string;
  // (undocumented)
  neutralPrimaryAlt?: string;
  // (undocumented)
  neutralQuaternary?: string;
  // (undocumented)
  neutralQuaternaryAlt?: string;
  // (undocumented)
  neutralSecondary?: string;
  // (undocumented)
  neutralSecondaryAlt?: string;
  // (undocumented)
  neutralTertiary?: string;
  // (undocumented)
  neutralTertiaryAlt?: string;
  // (undocumented)
  orange?: string;
  // (undocumented)
  orangeLight?: string;
  // (undocumented)
  orangeLighter?: string;
  // (undocumented)
  purple?: string;
  // (undocumented)
  purpleDark?: string;
  // (undocumented)
  purpleLight?: string;
  // (undocumented)
  red?: string;
  // (undocumented)
  redDark?: string;
  // (undocumented)
  teal?: string;
  // (undocumented)
  tealDark?: string;
  // (undocumented)
  tealLight?: string;
  // (undocumented)
  themeDark?: string;
  // (undocumented)
  themeDarkAlt?: string;
  // (undocumented)
  themeDarker?: string;
  // (undocumented)
  themeLight?: string;
  // (undocumented)
  themeLighter?: string;
  // (undocumented)
  themeLighterAlt?: string;
  // (undocumented)
  themePrimary?: string;
  // (undocumented)
  themeSecondary?: string;
  // (undocumented)
  themeTertiary?: string;
  // (undocumented)
  white?: string;
  // (undocumented)
  yellow?: string;
  // (undocumented)
  yellowLight?: string;
}

// (undocumented)
interface IFontClassNames extends IClassNames<IFontStyles> {
}

interface IFontStyles {
  // (undocumented)
  icon?: CSSProperties;
  // (undocumented)
  large?: CSSProperties;
  // (undocumented)
  medium?: CSSProperties;
  // (undocumented)
  mediumPlus?: CSSProperties;
  // (undocumented)
  mega?: CSSProperties;
  // (undocumented)
  small?: CSSProperties;
  // (undocumented)
  smallPlus?: CSSProperties;
  // (undocumented)
  superLarge?: CSSProperties;
  // (undocumented)
  tiny?: CSSProperties;
  // (undocumented)
  xLarge?: CSSProperties;
  // (undocumented)
  xSmall?: CSSProperties;
  // (undocumented)
  xxLarge?: CSSProperties;
}

// (undocumented)
interface IIconClassNames extends IClassNames<IIconCodes> {
}

// (undocumented)
interface IIconCodes {
  // (undocumented)
  aadLogo: string;
  // (undocumented)
  accept: string;
  // (undocumented)
  accessLogo: string;
  // (undocumented)
  accounts: string;
  // (undocumented)
  add: string;
  // (undocumented)
  addEvent: string;
  // (undocumented)
  addFavorite: string;
  // (undocumented)
  addFavoriteFill: string;
  // (undocumented)
  addFriend: string;
  // (undocumented)
  addGroup: string;
  // (undocumented)
  addOnlineMeeting: string;
  // (undocumented)
  addPhone: string;
  // (undocumented)
  addTo: string;
  // (undocumented)
  admin: string;
  // (undocumented)
  adminALogo: string;
  // (undocumented)
  adminCLogo: string;
  // (undocumented)
  adminDLogo: string;
  // (undocumented)
  adminELogo: string;
  // (undocumented)
  adminLLogo: string;
  // (undocumented)
  adminMLogo: string;
  // (undocumented)
  adminOLogo: string;
  // (undocumented)
  adminPLogo: string;
  // (undocumented)
  adminSLogo: string;
  // (undocumented)
  adminYLogo: string;
  // (undocumented)
  airplane: string;
  // (undocumented)
  airTickets: string;
  // (undocumented)
  alarmClock: string;
  // (undocumented)
  album: string;
  // (undocumented)
  albumRemove: string;
  // (undocumented)
  alchemyLogo: string;
  // (undocumented)
  alignCenter: string;
  // (undocumented)
  alignLeft: string;
  // (undocumented)
  alignRight: string;
  // (undocumented)
  androidLogo: string;
  // (undocumented)
  annotation: string;
  // (undocumented)
  appForOfficeLogo: string;
  // (undocumented)
  appIconDefault: string;
  // (undocumented)
  arrivals: string;
  // (undocumented)
  arrowDownRight8: string;
  // (undocumented)
  arrowDownRightMirrored8: string;
  // (undocumented)
  arrowUpRight8: string;
  // (undocumented)
  arrowUpRightMirrored8: string;
  // (undocumented)
  articles: string;
  // (undocumented)
  ascending: string;
  // (undocumented)
  assetLibrary: string;
  // (undocumented)
  asterisk: string;
  // (undocumented)
  atpLogo: string;
  // (undocumented)
  attach: string;
  // (undocumented)
  australianRules: string;
  // (undocumented)
  autoEnhanceOff: string;
  // (undocumented)
  autoEnhanceOn: string;
  // (undocumented)
  autoRacing: string;
  // (undocumented)
  awayStatus: string;
  // (undocumented)
  azureLogo: string;
  // (undocumented)
  back: string;
  // (undocumented)
  backToWindow: string;
  // (undocumented)
  badge: string;
  // (undocumented)
  balloons: string;
  // (undocumented)
  barChart4: string;
  // (undocumented)
  barChartHorizontal: string;
  // (undocumented)
  baseball: string;
  // (undocumented)
  bidiLtr: string;
  // (undocumented)
  bidiRtl: string;
  // (undocumented)
  bingLogo: string;
  // (undocumented)
  blockContact: string;
  // (undocumented)
  blocked: string;
  // (undocumented)
  blocked2: string;
  // (undocumented)
  blowingSnow: string;
  // (undocumented)
  boards: string;
  // (undocumented)
  bold: string;
  // (undocumented)
  bookingsLogo: string;
  // (undocumented)
  bookmarks: string;
  // (undocumented)
  bookmarksMirrored: string;
  // (undocumented)
  boxLogo: string;
  // (undocumented)
  branchFork: string;
  // (undocumented)
  breadcrumb: string;
  // (undocumented)
  brightness: string;
  // (undocumented)
  broom: string;
  // (undocumented)
  bufferTimeAfter: string;
  // (undocumented)
  bufferTimeBefore: string;
  // (undocumented)
  bufferTimeBoth: string;
  // (undocumented)
  bulletedList: string;
  // (undocumented)
  bulletedListMirrored: string;
  // (undocumented)
  busSolid: string;
  // (undocumented)
  cafe: string;
  // (undocumented)
  cake: string;
  // (undocumented)
  calculatorAddition: string;
  // (undocumented)
  calculatorSubtract: string;
  // (undocumented)
  calendar: string;
  // (undocumented)
  calendarAgenda: string;
  // (undocumented)
  calendarDay: string;
  // (undocumented)
  calendarMirrored: string;
  // (undocumented)
  calendarReply: string;
  // (undocumented)
  calendarWeek: string;
  // (undocumented)
  calendarWorkWeek: string;
  // (undocumented)
  caloriesAdd: string;
  // (undocumented)
  camera: string;
  // (undocumented)
  cancel: string;
  // (undocumented)
  car: string;
  // (undocumented)
  caretBottomLeftSolid8: string;
  // (undocumented)
  caretBottomRightSolid8: string;
  // (undocumented)
  caretDown8: string;
  // (undocumented)
  caretDownSolid8: string;
  // (undocumented)
  caretHollow: string;
  // (undocumented)
  caretHollowMirrored: string;
  // (undocumented)
  caretLeft8: string;
  // (undocumented)
  caretLeftSolid8: string;
  // (undocumented)
  caretRight8: string;
  // (undocumented)
  caretRightSolid8: string;
  // (undocumented)
  caretSolid: string;
  // (undocumented)
  caretSolidMirrored: string;
  // (undocumented)
  caretTopLeftSolid8: string;
  // (undocumented)
  caretTopRightSolid8: string;
  // (undocumented)
  caretUp8: string;
  // (undocumented)
  caretUpSolid8: string;
  // (undocumented)
  cat: string;
  // (undocumented)
  cellPhone: string;
  // (undocumented)
  certificate: string;
  // (undocumented)
  chart: string;
  // (undocumented)
  chat: string;
  // (undocumented)
  chatInviteFriend: string;
  // (undocumented)
  checkbox: string;
  // (undocumented)
  checkboxComposite: string;
  // (undocumented)
  checkboxIndeterminate: string;
  // (undocumented)
  checkList: string;
  // (undocumented)
  checkMark: string;
  // (undocumented)
  chevronDown: string;
  // (undocumented)
  chevronDownMed: string;
  // (undocumented)
  chevronDownSmall: string;
  // (undocumented)
  chevronLeft: string;
  // (undocumented)
  chevronLeftMed: string;
  // (undocumented)
  chevronLeftSmall: string;
  // (undocumented)
  chevronRight: string;
  // (undocumented)
  chevronRightMed: string;
  // (undocumented)
  chevronRightSmall: string;
  // (undocumented)
  chevronUp: string;
  // (undocumented)
  chevronUpMed: string;
  // (undocumented)
  chevronUpSmall: string;
  // (undocumented)
  chromeBack: string;
  // (undocumented)
  chromeBackMirrored: string;
  // (undocumented)
  chromeClose: string;
  // (undocumented)
  chromeMinimize: string;
  // (undocumented)
  circleFill: string;
  // (undocumented)
  circleHalfFull: string;
  // (undocumented)
  circlePlus: string;
  // (undocumented)
  circleRing: string;
  // (undocumented)
  classNotebookLogo: string;
  // (undocumented)
  classroomLogo: string;
  // (undocumented)
  clear: string;
  // (undocumented)
  clearFilter: string;
  // (undocumented)
  clearFormatting: string;
  // (undocumented)
  clearNight: string;
  // (undocumented)
  clock: string;
  // (undocumented)
  closedCaption: string;
  // (undocumented)
  closePane: string;
  // (undocumented)
  closePaneMirrored: string;
  // (undocumented)
  cloudAdd: string;
  // (undocumented)
  cloudDownload: string;
  // (undocumented)
  cloudUpload: string;
  // (undocumented)
  cloudWeather: string;
  // (undocumented)
  cloudy: string;
  // (undocumented)
  cocktails: string;
  // (undocumented)
  code: string;
  // (undocumented)
  coffee: string;
  // (undocumented)
  collabsDbLogo: string;
  // (undocumented)
  collapseMenu: string;
  // (undocumented)
  collegeFootball: string;
  // (undocumented)
  collegeHoops: string;
  // (undocumented)
  color: string;
  // (undocumented)
  combine: string;
  // (undocumented)
  compassNw: string;
  // (undocumented)
  completed: string;
  // (undocumented)
  completedSolid: string;
  // (undocumented)
  contact: string;
  // (undocumented)
  contactCard: string;
  // (undocumented)
  contactInfo: string;
  // (undocumented)
  container: string;
  // (undocumented)
  contrast: string;
  // (undocumented)
  copy: string;
  // (undocumented)
  cotton: string;
  // (undocumented)
  cricket: string;
  // (undocumented)
  css: string;
  // (undocumented)
  customList: string;
  // (undocumented)
  customListMirrored: string;
  // (undocumented)
  cycling: string;
  // (undocumented)
  dataConnectionLibrary: string;
  // (undocumented)
  dateTime: string;
  // (undocumented)
  dateTime2: string;
  // (undocumented)
  dateTimeMirrored: string;
  // (undocumented)
  decreaseIndentLegacy: string;
  // (undocumented)
  delveAnalytics: string;
  // (undocumented)
  delveAnalyticsLogo: string;
  // (undocumented)
  delveLogo: string;
  // (undocumented)
  descending: string;
  // (undocumented)
  design: string;
  // (undocumented)
  developerTools: string;
  // (undocumented)
  devices3: string;
  // (undocumented)
  devices4: string;
  // (undocumented)
  dialpad: string;
  // (undocumented)
  dictionary: string;
  // (undocumented)
  dietPlanNotebook: string;
  // (undocumented)
  disableUpdates: string;
  // (undocumented)
  dislike: string;
  // (undocumented)
  dockLeft: string;
  // (undocumented)
  dockLeftMirrored: string;
  // (undocumented)
  dockRight: string;
  // (undocumented)
  docLibrary: string;
  // (undocumented)
  docsLogo: string;
  // (undocumented)
  document: string;
  // (undocumented)
  documentation: string;
  // (undocumented)
  documentReply: string;
  // (undocumented)
  documentSearch: string;
  // (undocumented)
  documentSet: string;
  // (undocumented)
  door: string;
  // (undocumented)
  doubleBookmark: string;
  // (undocumented)
  doubleChevronDown: string;
  // (undocumented)
  doubleChevronDown12: string;
  // (undocumented)
  doubleChevronLeft: string;
  // (undocumented)
  doubleChevronLeft12: string;
  // (undocumented)
  doubleChevronLeftMed: string;
  // (undocumented)
  doubleChevronLeftMedMirrored: string;
  // (undocumented)
  doubleChevronRight: string;
  // (undocumented)
  doubleChevronRight12: string;
  // (undocumented)
  doubleChevronUp: string;
  // (undocumented)
  doubleChevronUp12: string;
  // (undocumented)
  down: string;
  // (undocumented)
  download: string;
  // (undocumented)
  drm: string;
  // (undocumented)
  drop: string;
  // (undocumented)
  dropboxLogo: string;
  // (undocumented)
  dropdown: string;
  // (undocumented)
  duststorm: string;
  // (undocumented)
  dynamics365Logo: string;
  // (undocumented)
  dynamicSmbLogo: string;
  // (undocumented)
  eatDrink: string;
  // (undocumented)
  edgeLogo: string;
  // (undocumented)
  edit: string;
  // (undocumented)
  editMail: string;
  // (undocumented)
  editMirrored: string;
  // (undocumented)
  editNote: string;
  // (undocumented)
  editPhoto: string;
  // (undocumented)
  editStyle: string;
  // (undocumented)
  embed: string;
  // (undocumented)
  emi: string;
  // (undocumented)
  emoji: string;
  // (undocumented)
  emoji2: string;
  // (undocumented)
  emojiDisappointed: string;
  // (undocumented)
  emojiNeutral: string;
  // (undocumented)
  emptyRecycleBin: string;
  // (undocumented)
  equalizer: string;
  // (undocumented)
  eraseTool: string;
  // (undocumented)
  error: string;
  // (undocumented)
  errorBadge: string;
  // (undocumented)
  event: string;
  // (undocumented)
  eventInfo: string;
  // (undocumented)
  excelDocument: string;
  // (undocumented)
  excelLogo: string;
  // (undocumented)
  exchangeLogo: string;
  // (undocumented)
  expandMenu: string;
  // (undocumented)
  fabricAssetLibrary: string;
  // (undocumented)
  fabricDataConnectionLibrary: string;
  // (undocumented)
  fabricDocLibrary: string;
  // (undocumented)
  fabricFolder: string;
  // (undocumented)
  fabricFolderFill: string;
  // (undocumented)
  fabricFolderSearch: string;
  // (undocumented)
  fabricFormLibrary: string;
  // (undocumented)
  fabricFormLibraryMirrored: string;
  // (undocumented)
  fabricMovetoFolder: string;
  // (undocumented)
  fabricNewFolder: string;
  // (undocumented)
  fabricOpenFolderHorizontal: string;
  // (undocumented)
  fabricPictureLibrary: string;
  // (undocumented)
  fabricPublicFolder: string;
  // (undocumented)
  fabricReportLibrary: string;
  // (undocumented)
  fabricReportLibraryMirrored: string;
  // (undocumented)
  fabricSyncFolder: string;
  // (undocumented)
  fabricUnsyncFolder: string;
  // (undocumented)
  facebookLogo: string;
  // (undocumented)
  family: string;
  // (undocumented)
  fangBody: string;
  // (undocumented)
  favoriteList: string;
  // (undocumented)
  favoriteStar: string;
  // (undocumented)
  favoriteStarFill: string;
  // (undocumented)
  fax: string;
  // (undocumented)
  ferry: string;
  // (undocumented)
  ferrySolid: string;
  // (undocumented)
  filter: string;
  // (undocumented)
  filters: string;
  // (undocumented)
  financial: string;
  // (undocumented)
  fingerprint: string;
  // (undocumented)
  flag: string;
  // (undocumented)
  flickDown: string;
  // (undocumented)
  flickLeft: string;
  // (undocumented)
  flickRight: string;
  // (undocumented)
  flickUp: string;
  // (undocumented)
  flow: string;
  // (undocumented)
  fog: string;
  // (undocumented)
  folder: string;
  // (undocumented)
  folderFill: string;
  // (undocumented)
  folderHorizontal: string;
  // (undocumented)
  folderOpen: string;
  // (undocumented)
  folderSearch: string;
  // (undocumented)
  font: string;
  // (undocumented)
  fontColor: string;
  // (undocumented)
  fontDecrease: string;
  // (undocumented)
  fontIncrease: string;
  // (undocumented)
  fontSize: string;
  // (undocumented)
  formLibrary: string;
  // (undocumented)
  formLibraryMirrored: string;
  // (undocumented)
  forward: string;
  // (undocumented)
  forwardEvent: string;
  // (undocumented)
  freezing: string;
  // (undocumented)
  frigid: string;
  // (undocumented)
  fullCircleMask: string;
  // (undocumented)
  fullScreen: string;
  // (undocumented)
  generate: string;
  // (undocumented)
  giftbox: string;
  // (undocumented)
  giftCard: string;
  // (undocumented)
  glasses: string;
  // (undocumented)
  glimmer: string;
  // (undocumented)
  globalNavButton: string;
  // (undocumented)
  globe: string;
  // (undocumented)
  globeFavorite: string;
  // (undocumented)
  golf: string;
  // (undocumented)
  googleDriveLogo: string;
  // (undocumented)
  gotoToday: string;
  // (undocumented)
  gripperTool: string;
  // (undocumented)
  group: string;
  // (undocumented)
  groupedAscending: string;
  // (undocumented)
  groupedDescending: string;
  // (undocumented)
  groupedList: string;
  // (undocumented)
  hailDay: string;
  // (undocumented)
  hailNight: string;
  // (undocumented)
  handwriting: string;
  // (undocumented)
  header1: string;
  // (undocumented)
  header2: string;
  // (undocumented)
  header3: string;
  // (undocumented)
  header4: string;
  // (undocumented)
  headset: string;
  // (undocumented)
  health: string;
  // (undocumented)
  heart: string;
  // (undocumented)
  heartFill: string;
  // (undocumented)
  help: string;
  // (undocumented)
  helpMirrored: string;
  // (undocumented)
  hide: string;
  // (undocumented)
  hide2: string;
  // (undocumented)
  history: string;
  // (undocumented)
  home: string;
  // (undocumented)
  homeSolid: string;
  // (undocumented)
  hospital: string;
  // (undocumented)
  hotel: string;
  // (undocumented)
  important: string;
  // (undocumented)
  inboxCheck: string;
  // (undocumented)
  incidentTriangle: string;
  // (undocumented)
  increaseIndentLegacy: string;
  // (undocumented)
  info: string;
  // (undocumented)
  info2: string;
  // (undocumented)
  insertTextBox: string;
  // (undocumented)
  internetSharing: string;
  // (undocumented)
  iOsAppStoreLogo: string;
  // (undocumented)
  issueTracking: string;
  // (undocumented)
  issueTrackingMirrored: string;
  // (undocumented)
  italic: string;
  // (undocumented)
  joinOnlineMeeting: string;
  // (undocumented)
  js: string;
  // (undocumented)
  label: string;
  // (undocumented)
  landscapeOrientation: string;
  // (undocumented)
  laptopSelected: string;
  // (undocumented)
  largeGrid: string;
  // (undocumented)
  library: string;
  // (undocumented)
  lifesaver: string;
  // (undocumented)
  lifesaverLock: string;
  // (undocumented)
  light: string;
  // (undocumented)
  lightbulb: string;
  // (undocumented)
  lightningBolt: string;
  // (undocumented)
  like: string;
  // (undocumented)
  link: string;
  // (undocumented)
  list: string;
  // (undocumented)
  listMirrored: string;
  // (undocumented)
  location: string;
  // (undocumented)
  locationCircle: string;
  // (undocumented)
  locationDot: string;
  // (undocumented)
  locationFill: string;
  // (undocumented)
  lock: string;
  // (undocumented)
  lowerBrightness: string;
  // (undocumented)
  lyncLogo: string;
  // (undocumented)
  mail: string;
  // (undocumented)
  mailAlert: string;
  // (undocumented)
  mailCheck: string;
  // (undocumented)
  mailFill: string;
  // (undocumented)
  mailForward: string;
  // (undocumented)
  mailForwardMirrored: string;
  // (undocumented)
  mailLowImportance: string;
  // (undocumented)
  mailPause: string;
  // (undocumented)
  mailRepeat: string;
  // (undocumented)
  mailReply: string;
  // (undocumented)
  mailReplyAll: string;
  // (undocumented)
  mailReplyAllMirrored: string;
  // (undocumented)
  mailReplyMirrored: string;
  // (undocumented)
  mapDirections: string;
  // (undocumented)
  mapPin: string;
  // (undocumented)
  market: string;
  // (undocumented)
  marketDown: string;
  // (undocumented)
  megaphone: string;
  // (undocumented)
  memo: string;
  // (undocumented)
  merge: string;
  // (undocumented)
  message: string;
  // (undocumented)
  messageFill: string;
  // (undocumented)
  microphone: string;
  // (undocumented)
  microsoftStaffhubLogo: string;
  // (undocumented)
  miniLink: string;
  // (undocumented)
  mobileSelected: string;
  // (undocumented)
  money: string;
  // (undocumented)
  more: string;
  // (undocumented)
  moreSports: string;
  // (undocumented)
  move: string;
  // (undocumented)
  moveToFolder: string;
  // (undocumented)
  msnLogo: string;
  // (undocumented)
  multiSelect: string;
  // (undocumented)
  multiSelectMirrored: string;
  // (undocumented)
  musicInCollection: string;
  // (undocumented)
  musicInCollectionFill: string;
  // (undocumented)
  musicNote: string;
  // (undocumented)
  nav2DMapView: string;
  // (undocumented)
  newFolder: string;
  // (undocumented)
  news: string;
  // (undocumented)
  noteForward: string;
  // (undocumented)
  notePinned: string;
  // (undocumented)
  noteReply: string;
  // (undocumented)
  numberedList: string;
  // (undocumented)
  numberField: string;
  // (undocumented)
  officeAssistantLogo: string;
  // (undocumented)
  officeFormLogo: string;
  // (undocumented)
  officeLogo: string;
  // (undocumented)
  officeStoreLogo: string;
  // (undocumented)
  officeVideoLogo: string;
  // (undocumented)
  offlineOneDriveParachute: string;
  // (undocumented)
  offlineOneDriveParachuteDisabled: string;
  // (undocumented)
  oneDrive: string;
  // (undocumented)
  oneDriveAdd: string;
  // (undocumented)
  oneNoteEduLogo: string;
  // (undocumented)
  oneNoteLogo: string;
  // (undocumented)
  openFile: string;
  // (undocumented)
  openFolderHorizontal: string;
  // (undocumented)
  openInNewWindow: string;
  // (undocumented)
  openPane: string;
  // (undocumented)
  openPaneMirrored: string;
  // (undocumented)
  org: string;
  // (undocumented)
  outlookLogo: string;
  // (undocumented)
  outOfOffice: string;
  // (undocumented)
  page: string;
  // (undocumented)
  pageAdd: string;
  // (undocumented)
  pageCheckedin: string;
  // (undocumented)
  pageCheckedOut: string;
  // (undocumented)
  pageLeft: string;
  // (undocumented)
  pageRight: string;
  // (undocumented)
  pageSolid: string;
  // (undocumented)
  panoIndicator: string;
  // (undocumented)
  paratureLogo: string;
  // (undocumented)
  partlyCloudyDay: string;
  // (undocumented)
  partlyCloudyNight: string;
  // (undocumented)
  partyLeader: string;
  // (undocumented)
  pause: string;
  // (undocumented)
  paymentCard: string;
  // (undocumented)
  pc1: string;
  // (undocumented)
  pdf: string;
  // (undocumented)
  pencilReply: string;
  // (undocumented)
  people: string;
  // (undocumented)
  peopleAdd: string;
  // (undocumented)
  peopleAlert: string;
  // (undocumented)
  peopleBlock: string;
  // (undocumented)
  peoplePause: string;
  // (undocumented)
  peopleRepeat: string;
  // (undocumented)
  permissions: string;
  // (undocumented)
  phone: string;
  // (undocumented)
  photo2: string;
  // (undocumented)
  photo2Add: string;
  // (undocumented)
  photo2Remove: string;
  // (undocumented)
  photoCollection: string;
  // (undocumented)
  picture: string;
  // (undocumented)
  pictureLibrary: string;
  // (undocumented)
  pieDouble: string;
  // (undocumented)
  pill: string;
  // (undocumented)
  pin: string;
  // (undocumented)
  pinned: string;
  // (undocumented)
  pinnedFill: string;
  // (undocumented)
  planner: string;
  // (undocumented)
  play: string;
  // (undocumented)
  playerSettings: string;
  // (undocumented)
  poi: string;
  // (undocumented)
  postUpdate: string;
  // (undocumented)
  powerApps: string;
  // (undocumented)
  powerApps2Logo: string;
  // (undocumented)
  powerAppsLogo: string;
  // (undocumented)
  powerBiLogo: string;
  // (undocumented)
  powerPointDocument: string;
  // (undocumented)
  powerPointLogo: string;
  // (undocumented)
  precipitation: string;
  // (undocumented)
  presenceChickletVideo: string;
  // (undocumented)
  preview: string;
  // (undocumented)
  previewLink: string;
  // (undocumented)
  print: string;
  // (undocumented)
  printfaxPrinterFile: string;
  // (undocumented)
  product: string;
  // (undocumented)
  proFootball: string;
  // (undocumented)
  proHockey: string;
  // (undocumented)
  projectLogo: string;
  // (undocumented)
  protectedDocument: string;
  // (undocumented)
  publicCalendar: string;
  // (undocumented)
  publicContactCard: string;
  // (undocumented)
  publicEmail: string;
  // (undocumented)
  publicFolder: string;
  // (undocumented)
  puzzle: string;
  // (undocumented)
  questionnaire: string;
  // (undocumented)
  questionnaireMirrored: string;
  // (undocumented)
  quickNote: string;
  // (undocumented)
  radioBtnOn: string;
  // (undocumented)
  radioBullet: string;
  // (undocumented)
  rain: string;
  // (undocumented)
  rainShowersDay: string;
  // (undocumented)
  rainShowersNight: string;
  // (undocumented)
  rainSnow: string;
  // (undocumented)
  read: string;
  // (undocumented)
  readingMode: string;
  // (undocumented)
  receiptCheck: string;
  // (undocumented)
  receiptForward: string;
  // (undocumented)
  receiptReply: string;
  // (undocumented)
  recent: string;
  // (undocumented)
  recurringEvent: string;
  // (undocumented)
  recurringTask: string;
  // (undocumented)
  recycleBin: string;
  // (undocumented)
  redEye: string;
  // (undocumented)
  redo: string;
  // (undocumented)
  refresh: string;
  // (undocumented)
  reminderGroup: string;
  // (undocumented)
  remove: string;
  // (undocumented)
  removeEvent: string;
  // (undocumented)
  removeFilter: string;
  // (undocumented)
  removeLink: string;
  // (undocumented)
  removeOccurrence: string;
  // (undocumented)
  rename: string;
  // (undocumented)
  reopenPages: string;
  // (undocumented)
  repair: string;
  // (undocumented)
  reply: string;
  // (undocumented)
  replyAll: string;
  // (undocumented)
  replyAllAlt: string;
  // (undocumented)
  replyAllMirrored: string;
  // (undocumented)
  replyAlt: string;
  // (undocumented)
  replyMirrored: string;
  // (undocumented)
  reportLibrary: string;
  // (undocumented)
  reportLibraryMirrored: string;
  // (undocumented)
  returnToSession: string;
  // (undocumented)
  revToggleKey: string;
  // (undocumented)
  ribbon: string;
  // (undocumented)
  rightDoubleQuote: string;
  // (undocumented)
  ringer: string;
  // (undocumented)
  room: string;
  // (undocumented)
  rotate: string;
  // (undocumented)
  rugby: string;
  // (undocumented)
  running: string;
  // (undocumented)
  sad: string;
  // (undocumented)
  save: string;
  // (undocumented)
  saveAs: string;
  // (undocumented)
  search: string;
  // (undocumented)
  section: string;
  // (undocumented)
  sections: string;
  // (undocumented)
  securityGroup: string;
  // (undocumented)
  send: string;
  // (undocumented)
  sendMirrored: string;
  // (undocumented)
  setAction: string;
  // (undocumented)
  settings: string;
  // (undocumented)
  share: string;
  // (undocumented)
  shareiOs: string;
  // (undocumented)
  sharepointLogo: string;
  // (undocumented)
  shield: string;
  // (undocumented)
  shop: string;
  // (undocumented)
  shoppingCart: string;
  // (undocumented)
  showResults: string;
  // (undocumented)
  showResultsMirrored: string;
  // (undocumented)
  sidePanel: string;
  // (undocumented)
  singleBookmark: string;
  // (undocumented)
  sipMove: string;
  // (undocumented)
  skypeCheck: string;
  // (undocumented)
  skypeCircleCheck: string;
  // (undocumented)
  skypeCircleClock: string;
  // (undocumented)
  skypeCircleMinus: string;
  // (undocumented)
  skypeClock: string;
  // (undocumented)
  skypeLogo: string;
  // (undocumented)
  skypeMessage: string;
  // (undocumented)
  skypeMinus: string;
  // (undocumented)
  sliderThumb: string;
  // (undocumented)
  snow: string;
  // (undocumented)
  snowShowerDay: string;
  // (undocumented)
  snowShowerNight: string;
  // (undocumented)
  soccer: string;
  // (undocumented)
  socialListeningLogo: string;
  // (undocumented)
  sort: string;
  // (undocumented)
  sortDown: string;
  // (undocumented)
  sortLines: string;
  // (undocumented)
  sortUp: string;
  // (undocumented)
  speakers: string;
  // (undocumented)
  speedHigh: string;
  // (undocumented)
  split: string;
  // (undocumented)
  squalls: string;
  // (undocumented)
  stackIndicator: string;
  // (undocumented)
  starburst: string;
  // (undocumented)
  statusErrorFull: string;
  // (undocumented)
  statusTriangle: string;
  // (undocumented)
  stockDown: string;
  // (undocumented)
  stockUp: string;
  // (undocumented)
  stopwatch: string;
  // (undocumented)
  storeLogo: string;
  // (undocumented)
  storeLogoMed: string;
  // (undocumented)
  strikethrough: string;
  // (undocumented)
  subscribe: string;
  // (undocumented)
  subscript: string;
  // (undocumented)
  suitcase: string;
  // (undocumented)
  sunAdd: string;
  // (undocumented)
  sunny: string;
  // (undocumented)
  sunQuestionMark: string;
  // (undocumented)
  superscript: string;
  // (undocumented)
  swayLogo: string;
  // (undocumented)
  switcher: string;
  // (undocumented)
  switcherStartEnd: string;
  // (undocumented)
  sync: string;
  // (undocumented)
  syncFolder: string;
  // (undocumented)
  syncToPc: string;
  // (undocumented)
  system: string;
  // (undocumented)
  tab: string;
  // (undocumented)
  table: string;
  // (undocumented)
  tablet: string;
  // (undocumented)
  tabletSelected: string;
  // (undocumented)
  tag: string;
  // (undocumented)
  taskManager: string;
  // (undocumented)
  taskManagerMirrored: string;
  // (undocumented)
  teamwork: string;
  // (undocumented)
  temporaryUser: string;
  // (undocumented)
  tennis: string;
  // (undocumented)
  textBox: string;
  // (undocumented)
  textField: string;
  // (undocumented)
  thumbnailView: string;
  // (undocumented)
  thumbnailViewMirrored: string;
  // (undocumented)
  thunderstorms: string;
  // (undocumented)
  ticket: string;
  // (undocumented)
  tiles: string;
  // (undocumented)
  tiles2: string;
  // (undocumented)
  timeline: string;
  // (undocumented)
  timer: string;
  // (undocumented)
  toggleBorder: string;
  // (undocumented)
  toggleFilled: string;
  // (undocumented)
  toggleThumb: string;
  // (undocumented)
  touch: string;
  // (undocumented)
  touchPointer: string;
  // (undocumented)
  train: string;
  // (undocumented)
  trainSolid: string;
  // (undocumented)
  transferCall: string;
  // (undocumented)
  trash: string;
  // (undocumented)
  triangleDown12: string;
  // (undocumented)
  triangleLeft12: string;
  // (undocumented)
  triangleRight12: string;
  // (undocumented)
  triangleSolidDown12: string;
  // (undocumented)
  triangleSolidLeft12: string;
  // (undocumented)
  triangleSolidRight12: string;
  // (undocumented)
  triangleSolidUp12: string;
  // (undocumented)
  triangleUp12: string;
  // (undocumented)
  trophy: string;
  // (undocumented)
  turnRight: string;
  // (undocumented)
  tvMonitor: string;
  // (undocumented)
  tvMonitorSelected: string;
  // (undocumented)
  underline: string;
  // (undocumented)
  undo: string;
  // (undocumented)
  unfavorite: string;
  // (undocumented)
  unknownCall: string;
  // (undocumented)
  unlock: string;
  // (undocumented)
  unpin: string;
  // (undocumented)
  unsubscribe: string;
  // (undocumented)
  unsyncFolder: string;
  // (undocumented)
  up: string;
  // (undocumented)
  upload: string;
  // (undocumented)
  video: string;
  // (undocumented)
  videoSolid: string;
  // (undocumented)
  view: string;
  // (undocumented)
  viewAll: string;
  // (undocumented)
  viewAll2: string;
  // (undocumented)
  visioLogo: string;
  // (undocumented)
  voicemailForward: string;
  // (undocumented)
  voicemailReply: string;
  // (undocumented)
  volume0: string;
  // (undocumented)
  volume1: string;
  // (undocumented)
  volume2: string;
  // (undocumented)
  volume3: string;
  // (undocumented)
  volumeDisabled: string;
  // (undocumented)
  waffle: string;
  // (undocumented)
  warning: string;
  // (undocumented)
  website: string;
  // (undocumented)
  weights: string;
  // (undocumented)
  windDirection: string;
  // (undocumented)
  windowsLogo: string;
  // (undocumented)
  wipePhone: string;
  // (undocumented)
  wordDocument: string;
  // (undocumented)
  wordLogo: string;
  // (undocumented)
  work: string;
  // (undocumented)
  workFlow: string;
  // (undocumented)
  worldClock: string;
  // (undocumented)
  yammerLogo: string;
  // (undocumented)
  zoom: string;
  // (undocumented)
  zoomIn: string;
  // (undocumented)
  zoomOut: string;
}

export function insertGlobal(selector: string, style: CSSProperties): void;

// (undocumented)
interface ITheme {
  // (undocumented)
  colors?: IColorStyles;
  // (undocumented)
  fonts?: IFontStyles;
}

export function loadTheme(theme: ITheme): void;

// (undocumented)
interface StyleAttribute {
  // (undocumented)
  [ attributeName: string ]: '';
}

// WARNING: css has incomplete type information
// WARNING: Unsupported export: animationClassNames
// WARNING: Unsupported export: fontClassNames
// WARNING: Unsupported export: iconClassNames
// WARNING: Unsupported export: colorClassNames
// WARNING: Unsupported export: animationStyles
// WARNING: Unsupported export: fontStyles
// WARNING: Unsupported export: colorStyles
// WARNING: Unsupported export: iconCodes
// (No packageDescription for this package)
