/**
 * Issue pattern definitions.
 *
 * Each IssueCategory maps a class of problems to:
 *  - keywords   : terms that trigger this category
 *  - folders    : repo-relative directories to investigate
 *  - fileGlobs  : specific file-name patterns to look for
 *  - notes      : human-readable investigation hints
 */

export interface IssueCategory {
  id: string;
  label: string;
  keywords: string[];
  folders: string[];
  fileGlobs: string[];
  notes: string[];
}

export const ISSUE_CATEGORIES: IssueCategory[] = [
  // ─────────────────────────────────────────────
  // PERFORMANCE
  // ─────────────────────────────────────────────
  {
    id: 'performance',
    label: 'Performance',
    keywords: [
      'slow',
      'lag',
      'laggy',
      'freeze',
      'frozen',
      'hang',
      'hanging',
      'memory leak',
      'memory',
      'performance',
      'fps',
      'jank',
      'janky',
      'render',
      're-render',
      'rerender',
      'expensive',
      'timeout',
      'infinite loop',
      'infinite render',
      'loop',
      'heavy',
      'cpu',
      'bundle size',
      'bundle',
      'large bundle',
      'loading time',
      'initial load',
      'hydration',
      'ttfb',
      'lcp',
      'cls',
      'fid',
    ],
    folders: [
      'packages/react-components/react-utilities/src',
      'packages/react-components/react-shared-contexts/src',
      'apps/perf-test-react-components',
      'apps/perf-test',
    ],
    fileGlobs: ['*.perf.ts', '*.perf.tsx', 'use*.ts', 'use*.tsx', '*.memo.*', 'virtualizer*', 'Virtualizer*'],
    notes: [
      'Check for missing React.memo / useMemo / useCallback wrappers.',
      'Look for components that trigger expensive re-renders on every keystroke or scroll.',
      'Review perf-test benchmarks in apps/perf-test-react-components.',
      'Inspect Griffel style injection — duplicate styles hurt runtime perf.',
      'Check for unintentional context value object recreation causing downstream re-renders.',
      'Large lists should use the Virtualizer component (packages/react-components/react-virtualizer).',
    ],
  },

  // ─────────────────────────────────────────────
  // LAYOUT / ALIGNMENT / SPACING
  // ─────────────────────────────────────────────
  {
    id: 'layout',
    label: 'Layout / Alignment / Spacing',
    keywords: [
      'alignment',
      'align',
      'misalign',
      'offset',
      'overlap',
      'overlapping',
      'spacing',
      'margin',
      'padding',
      'gap',
      'layout',
      'position',
      'positioned',
      'overflow',
      'clip',
      'clipped',
      'truncat',
      'ellipsis',
      'width',
      'height',
      'size',
      'resize',
      'flex',
      'grid',
      'column',
      'row',
      'wrap',
      'indent',
      'shift',
      'jump',
      'jitter',
      'scroll',
      'scrollbar',
      'sticky',
      'z-index',
      'stacking',
      'behind',
      'in front',
      'shrink',
      'stretch',
    ],
    folders: [
      'packages/react-components/react-theme/src/global/tokens',
      'packages/react-components/react-utilities/src/utils',
      'packages/common-styles/src',
    ],
    fileGlobs: ['*.styles.ts', '*.styles.tsx', 'tokens.ts', 'usePositioning*', 'positioning*'],
    notes: [
      'Check *.styles.ts files in the affected component package.',
      'Spacing tokens live in packages/react-components/react-theme/src/global/tokens/spacing*.',
      'Positioning logic (popups, tooltips, dropdowns) is in react-positioning package.',
      'Check whether makeStyles rules are using shorthand properties that override each other.',
      'RTL mirroring is handled by Griffel — check for missing logical CSS properties.',
    ],
  },

  // ─────────────────────────────────────────────
  // VISUAL / STYLING / THEMING
  // ─────────────────────────────────────────────
  {
    id: 'styling',
    label: 'Visual / Styling / Theming',
    keywords: [
      'color',
      'colour',
      'theme',
      'theming',
      'dark mode',
      'dark theme',
      'light mode',
      'high contrast',
      'hc',
      'token',
      'design token',
      'style',
      'styling',
      'css',
      'appearance',
      'font',
      'typography',
      'icon',
      'icon size',
      'border',
      'radius',
      'shadow',
      'elevation',
      'opacity',
      'transparent',
      'background',
      'foreground',
      'stroke',
      'fill',
      'gradient',
      'flicker',
      'flash',
      'blink',
      'wrong color',
      'incorrect color',
      'brand',
      'accent',
    ],
    folders: [
      'packages/react-components/react-theme/src',
      'packages/react-components/react-theme/src/global/tokens',
      'packages/react-components/react-theme/src/alias/tokens',
      'packages/fluent2-theme/src',
      'packages/azure-themes/src',
    ],
    fileGlobs: [
      '*.styles.ts',
      '*.styles.tsx',
      'tokens.ts',
      '*Tokens.ts',
      '*Theme.ts',
      'theme.ts',
      'colorTokens*',
      'typographyTokens*',
      'shadowTokens*',
    ],
    notes: [
      'Design tokens are split into global tokens (absolute values) and alias tokens (semantic).',
      'Global tokens: packages/react-components/react-theme/src/global/tokens/',
      'Alias tokens: packages/react-components/react-theme/src/alias/tokens/',
      'High-contrast overrides are usually inline inside makeStyles using the forcedColors selector.',
      'Check that the correct token is used — alias tokens (colorNeutralForeground1) should be preferred over hard-coded global tokens.',
      'Icon sizing is in packages/react-components/react-icons-compat and the icon components themselves.',
    ],
  },

  // ─────────────────────────────────────────────
  // LOCALIZATION / INTERNATIONALIZATION / RTL
  // ─────────────────────────────────────────────
  {
    id: 'localization',
    label: 'Localization / i18n / RTL',
    keywords: [
      'localization',
      'localisation',
      'i18n',
      'internationalization',
      'internationalisation',
      'translation',
      'translated',
      'locale',
      'language',
      'string',
      'text',
      'label',
      'placeholder',
      'aria-label',
      'aria label',
      'alt text',
      'rtl',
      'ltr',
      'right to left',
      'bidi',
      'bidirectional',
      'arabic',
      'hebrew',
      'persian',
      'mirrored',
      'mirror',
      'flip',
      'direction',
    ],
    folders: ['packages/react-components/react-utilities/src', 'packages/react-components/react-aria/src'],
    fileGlobs: [
      '*.types.ts',
      '*Slots.ts',
      '*defaultProps*',
      'use*ClassNames*',
      '*strings*',
      '*Strings*',
      '*Labels*',
      '*labels*',
      '*i18n*',
    ],
    notes: [
      'Visible text exposed to users should be accessible via component props (e.g. aria-label, label, placeholder).',
      'Check *.types.ts for the prop definition that carries the localized string.',
      'RTL layout: Griffel auto-flips logical CSS properties (marginInlineStart → marginInlineEnd). Verify logical properties are used.',
      'Icon mirroring for RTL: check for the shouldMirrorRtl flag on FluentIcon components.',
      'Date/time formatting respects the locale prop — trace through react-date-time-utilities.',
    ],
  },

  // ─────────────────────────────────────────────
  // ACCESSIBILITY
  // ─────────────────────────────────────────────
  {
    id: 'accessibility',
    label: 'Accessibility (a11y)',
    keywords: [
      'accessibility',
      'accessible',
      'a11y',
      'aria',
      'aria-',
      'role',
      'screen reader',
      'narrator',
      'voiceover',
      'nvda',
      'jaws',
      'focus',
      'focus trap',
      'focus ring',
      'focus visible',
      'keyboard',
      'keyboard navigation',
      'tab order',
      'tab stop',
      'tabindex',
      'roving tabindex',
      'contrast ratio',
      'color contrast',
      'wcag',
      'axe',
      'landmark',
      'live region',
      'announcements',
      'announced',
    ],
    folders: [
      'packages/react-components/react-aria/src',
      'packages/react-components/react-tabster/src',
      'packages/a11y-testing/src',
      'packages/react-components/react-utilities/src/utils',
    ],
    fileGlobs: [
      'use*Focus*',
      'use*Keyboard*',
      'use*Aria*',
      'use*Accessible*',
      '*.accessibility.ts',
      '*.a11y.ts',
      'use*Tabster*',
    ],
    notes: [
      'Focus management is handled by Tabster — check packages/react-components/react-tabster.',
      'ARIA role/state/property assignments are usually in the component render function or useComponentNameStyles hook.',
      'Run axe-core in browser DevTools or Storybook to reproduce the violation.',
      'Keyboard navigation patterns (roving tabindex, arrow keys) are in useArrowNavigationGroup / useFocusableGroup.',
      'packages/a11y-testing contains automated a11y test helpers.',
    ],
  },

  // ─────────────────────────────────────────────
  // INTERACTION / EVENT HANDLING
  // ─────────────────────────────────────────────
  {
    id: 'interaction',
    label: 'Interaction / Event Handling',
    keywords: [
      'click',
      'onclick',
      'on click',
      'double click',
      'right click',
      'context menu',
      'hover',
      'mouse over',
      'mouseover',
      'mouseenter',
      'mouseleave',
      'mouse leave',
      'drag',
      'drop',
      'drag and drop',
      'swipe',
      'touch',
      'pointer',
      'event',
      'handler',
      'callback',
      'trigger',
      'not firing',
      'not called',
      'event not',
      'callback not',
      'selection',
      'select',
      'deselect',
      'toggle',
      'check',
      'uncheck',
      'expand',
      'collapse',
      'open',
      'close',
      'dismiss',
    ],
    folders: ['packages/react-components/react-utilities/src/utils'],
    fileGlobs: [
      'use*Click*',
      'use*Select*',
      'use*Toggle*',
      'use*Open*',
      'use*Dismiss*',
      'use*Interaction*',
      'use*Hover*',
      'use*Press*',
      'use*Trigger*',
      'getDropdownActionFromKey*',
      '*EventListeners*',
    ],
    notes: [
      'Event handlers are typically defined in the useComponentName hook, not the JSX.',
      'Check for event.stopPropagation() calls that might be swallowing events.',
      'Controlled vs uncontrolled state: trace the value/defaultValue/onChange pattern.',
      'Open/close state for overlay components (Dialog, Popover, Menu) flows through usePopupOpenChange.',
    ],
  },

  // ─────────────────────────────────────────────
  // STATE / LOGIC / RENDERING BUGS
  // ─────────────────────────────────────────────
  {
    id: 'state',
    label: 'State / Logic / Rendering Bugs',
    keywords: [
      'state',
      'useState',
      'useEffect',
      'hook',
      'context',
      'provider',
      'props',
      'prop',
      'undefined',
      'null',
      'nan',
      'error',
      'crash',
      'exception',
      'throw',
      'thrown',
      'breaking',
      'broken',
      'not working',
      'does not work',
      "doesn't work",
      'bug',
      'wrong',
      'incorrect',
      'unexpected',
      'mismatch',
      'stale',
      'stale closure',
      'stale state',
      'outdated',
      'not updating',
      'not rendering',
      'blank',
      'empty',
      'nothing shown',
      'invisible',
      'hidden',
      'disappear',
      'flash of',
      'race condition',
      'flicker',
      'inconsistent',
      'condition',
      'conditional',
    ],
    folders: ['packages/react-components/react-utilities/src', 'packages/react-components/react-shared-contexts/src'],
    fileGlobs: ['use*.ts', 'use*.tsx', '*.context.ts', '*.context.tsx', '*Provider*', '*Reducer*', '*.state.ts'],
    notes: [
      'Start from the component hook (useComponentName.ts) — that is where all state logic lives.',
      'Controlled/uncontrolled helpers are in packages/react-components/react-utilities/src/utils/useControllableState.ts.',
      'Context consumers re-render when context value object identity changes — look for inline object literals in Provider value prop.',
      'useEffect cleanup missing → possible stale event listeners or timers.',
    ],
  },

  // ─────────────────────────────────────────────
  // ANIMATION / TRANSITION
  // ─────────────────────────────────────────────
  {
    id: 'animation',
    label: 'Animation / Transition',
    keywords: [
      'animation',
      'animate',
      'transition',
      'motion',
      'ease',
      'duration',
      'delay',
      'keyframe',
      'fade',
      'slide',
      'scale',
      'rotate',
      'transform',
      'spring',
      'entrance',
      'exit',
      'appear',
      'disappear',
      'reduce motion',
      'prefers-reduced-motion',
      'no animation',
      'animation disabled',
    ],
    folders: ['packages/react-components/react-motion/src', 'packages/react-components/react-utilities/src'],
    fileGlobs: ['*Motion*', '*motion*', '*Transition*', '*transition*', '*Animation*', '*animation*', 'tokens.ts'],
    notes: [
      'Animation primitives are in packages/react-components/react-motion.',
      'Duration and easing tokens are in packages/react-components/react-theme/src/global/tokens/motionTokens*.',
      'Respect prefers-reduced-motion — check that animations are disabled under the forcedColors / reducedMotion media query.',
      'Presence component handles enter/exit animations for conditional rendering.',
    ],
  },

  // ─────────────────────────────────────────────
  // RESPONSIVE / MOBILE / VIEWPORT
  // ─────────────────────────────────────────────
  {
    id: 'responsive',
    label: 'Responsive / Mobile / Viewport',
    keywords: [
      'responsive',
      'mobile',
      'tablet',
      'desktop',
      'breakpoint',
      'media query',
      'viewport',
      'screen size',
      'small screen',
      'large screen',
      'touch',
      'touch screen',
      'ios',
      'android',
      'safari',
      'chrome',
      'firefox',
      'edge',
      'browser',
      'cross-browser',
      'zoom',
      'pinch',
    ],
    folders: ['packages/react-components/react-utilities/src', 'packages/common-styles/src'],
    fileGlobs: ['use*Media*', 'use*Viewport*', 'use*BreakPoint*', '*.styles.ts'],
    notes: [
      'Fluent UI v9 does not ship built-in breakpoint utilities — responsive behavior is typically CSS-based.',
      'Check *.styles.ts for @media queries.',
      'Touch interactions: pointer events are preferred over mouse/touch events for cross-device support.',
      'Test in browser DevTools responsive mode and on actual devices.',
    ],
  },

  // ─────────────────────────────────────────────
  // TESTING / STORYBOOK / SNAPSHOT
  // ─────────────────────────────────────────────
  {
    id: 'testing',
    label: 'Testing / Storybook / Snapshot',
    keywords: [
      'test',
      'tests',
      'testing',
      'jest',
      'vitest',
      'playwright',
      'cypress',
      'snapshot',
      'storybook',
      'story',
      'stories',
      'visual regression',
      'vr test',
      'screenshot',
      'unit test',
      'integration test',
      'e2e',
      'flaky',
      'failing test',
      'test failure',
      'ci',
      'pipeline',
      'coverage',
    ],
    folders: [
      'apps/vr-tests-react-components',
      'apps/vr-tests',
      'apps/rit-tests-v9',
      'apps/rit-tests-v8',
      'packages/react-conformance/src',
    ],
    fileGlobs: ['*.test.ts', '*.test.tsx', '*.spec.ts', '*.spec.tsx', '*.stories.tsx', '*.stories.ts', '*.e2e.ts'],
    notes: [
      'Unit tests live next to source files: ComponentName.test.tsx.',
      'Visual regression tests are in apps/vr-tests-react-components.',
      'Storybook stories are in the stories/ folder of each package.',
      'Run conformance tests with jest --testPathPattern=Conformance to catch ARIA/prop contract violations.',
      'Snapshot mismatches: delete the .snap file and re-run to regenerate, then review the diff.',
    ],
  },

  // ─────────────────────────────────────────────
  // BUILD / TYPESCRIPT / IMPORT ERRORS
  // ─────────────────────────────────────────────
  {
    id: 'build',
    label: 'Build / TypeScript / Import Errors',
    keywords: [
      'build',
      'build error',
      'compile',
      'compilation',
      'typescript',
      'type error',
      'type mismatch',
      'cannot find',
      'not exported',
      'import',
      'export',
      'module not found',
      'missing export',
      'missing import',
      'bundle',
      'webpack',
      'rollup',
      'vite',
      'esbuild',
      'tree shaking',
      'circular dependency',
      'peer dependency',
      'version mismatch',
      'package',
      'declaration',
      'types',
      'd.ts',
    ],
    folders: ['packages/react-components/react-utilities/src', 'packages/react-components/react-shared-contexts/src'],
    fileGlobs: [
      'index.ts',
      'index.tsx',
      'package.json',
      'tsconfig*.json',
      'jest.config.js',
      'jest.config.ts',
      '*.d.ts',
      'exports-validation*',
    ],
    notes: [
      'Public API exports are listed in the package index.ts — check that the symbol is exported there.',
      'Type declarations: run yarn build to regenerate dist/index.d.ts.',
      'Circular dependencies: use yarn nx graph to visualize the dependency graph.',
      'peer dependencies mismatch: check the peerDependencies section in the affected package.json.',
      'API extractor reports are in packages/{component}/etc/{component}.api.md.',
    ],
  },

  // ─────────────────────────────────────────────
  // POPOVER / OVERLAY / PORTAL
  // ─────────────────────────────────────────────
  {
    id: 'overlay',
    label: 'Popover / Overlay / Portal / Positioning',
    keywords: [
      'popover',
      'popup',
      'tooltip',
      'dropdown',
      'flyout',
      'overlay',
      'portal',
      'teleport',
      'dialog',
      'modal',
      'sheet',
      'drawer',
      'menu',
      'context menu',
      'combobox',
      'listbox',
      'floating',
      'anchored',
      'placement',
      'offset',
      'flip',
      'overflow boundary',
      'collision',
      'z-index',
      'behind',
      'stacking context',
      'body',
      'document body',
      'mount',
      'unmount',
    ],
    folders: [
      'packages/react-components/react-positioning/src',
      'packages/react-components/react-portal/src',
      'packages/react-components/react-dialog/src',
      'packages/react-components/react-popover/src',
      'packages/react-components/react-tooltip/src',
      'packages/react-components/react-menu/src',
    ],
    fileGlobs: [
      'use*Positioning*',
      'use*PopupOpen*',
      'use*Portal*',
      'use*Overlay*',
      '*positioning*',
      'usePopoverContext*',
      'useDialogContext*',
    ],
    notes: [
      'Positioning (placement, flipping, overflow) is handled by @floating-ui via packages/react-components/react-positioning.',
      'Portal rendering: components use packages/react-components/react-portal to teleport nodes to document.body.',
      'Z-index stacking issues: check the zIndex tokens in react-theme and the FluentProvider stacking context.',
      'Dismissal (Escape key, outside click) flows through useDismiss in react-positioning.',
    ],
  },

  // ─────────────────────────────────────────────
  // FORM / INPUT / VALIDATION
  // ─────────────────────────────────────────────
  {
    id: 'form',
    label: 'Form / Input / Validation',
    keywords: [
      'form',
      'input',
      'textarea',
      'checkbox',
      'radio',
      'select',
      'combobox',
      'autocomplete',
      'search',
      'field',
      'label',
      'validation',
      'validate',
      'error message',
      'required',
      'disabled',
      'readonly',
      'read-only',
      'value',
      'default value',
      'controlled',
      'uncontrolled',
      'submit',
      'reset',
      'clear',
      'placeholder',
      'hint',
      'helper text',
    ],
    folders: [
      'packages/react-components/react-input/src',
      'packages/react-components/react-textarea/src',
      'packages/react-components/react-checkbox/src',
      'packages/react-components/react-radio-group/src',
      'packages/react-components/react-combobox/src',
      'packages/react-components/react-field/src',
      'packages/react-components/react-search/src',
    ],
    fileGlobs: [
      'use*Input*',
      'use*Field*',
      'use*Validation*',
      'use*Checkbox*',
      'use*Radio*',
      '*.types.ts',
      '*.styles.ts',
    ],
    notes: [
      'The Field component wraps inputs and provides label + validation message slot layout.',
      'Controlled state pattern: value + onChange. Uncontrolled: defaultValue.',
      'Validation state (error/warning/success) is a prop on the Field component.',
      'Disabled and readonly states are inherited via React context in some composite components.',
    ],
  },

  // ─────────────────────────────────────────────
  // DATA DISPLAY / TABLE / TREE / LIST
  // ─────────────────────────────────────────────
  {
    id: 'data-display',
    label: 'Data Display / Table / Tree / List',
    keywords: [
      'table',
      'data grid',
      'datagrid',
      'grid',
      'list',
      'tree',
      'tree view',
      'virtual',
      'virtualized',
      'virtualizer',
      'pagination',
      'sort',
      'sorting',
      'filter',
      'filtering',
      'column',
      'row',
      'cell',
      'header',
      'footer',
      'selection',
      'multi select',
      'multi-select',
      'expand',
      'collapse',
      'indent',
      'infinite scroll',
      'load more',
    ],
    folders: [
      'packages/react-components/react-table/src',
      'packages/react-components/react-tree/src',
      'packages/react-components/react-virtualizer/src',
      'packages/react-components/react-list/src',
    ],
    fileGlobs: [
      'use*Table*',
      'use*Tree*',
      'use*Row*',
      'use*Column*',
      'use*Selection*',
      'use*Sort*',
      'use*Virtualizer*',
      '*.types.ts',
    ],
    notes: [
      'DataGrid extends Table with selection, sort, and resize built in.',
      'Virtualization for large datasets: packages/react-components/react-virtualizer.',
      'Tree expand/collapse state is in useTreeItem — check controlled/uncontrolled open state.',
      'Column resizing uses ColumnResizingPlugin in react-table.',
    ],
  },
];

/**
 * Detects which issue categories are relevant given a user-supplied description.
 * Returns categories ordered by match score (descending).
 */
export function detectCategories(description: string): Array<{ category: IssueCategory; score: number }> {
  const lower = description.toLowerCase();
  const words = lower.split(/\s+/);

  const scored = ISSUE_CATEGORIES.map(category => {
    let score = 0;

    for (const keyword of category.keywords) {
      if (lower.includes(keyword)) {
        // Exact substring match
        score += keyword.split(' ').length > 1 ? 3 : 1; // multi-word phrases score higher
      }
    }

    // Boost if a keyword appears multiple times (strong signal)
    for (const keyword of category.keywords) {
      const count = (lower.match(new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) ?? []).length;
      if (count > 1) score += count - 1;
    }

    return { category, score };
  });

  return scored.filter(s => s.score > 0).sort((a, b) => b.score - a.score);
}
