/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReleasePackageGeneratorSchema {
  /**
   * Library name
   */
  project: string;
  /**
   * Phase of npm release life cycle for fluent v9 core package
   */
  phase: 'preview' | 'stable' | 'compat';
}
