import { createTheme, Theme } from '@fluentui/react';
import { BaseColors, CommonSemanticColors, DarkSemanticColors } from './AzureColors';
import { IExtendedSemanticColors } from './IExtendedSemanticColors';
import { FontSizes } from './AzureType';
import * as StyleConstants from './Constants';
import { AzureStyleSettings } from './AzureStyleSettings';

const darkExtendedSemanticColors: Partial<IExtendedSemanticColors> = {
  bodyBackground: DarkSemanticColors.background,
  bodyDivider: CommonSemanticColors.dividers.lineSeparator,
  bodyText: DarkSemanticColors.text.body,
  bodyTextHovered: DarkSemanticColors.text.bodyHovered,
  buttonBackground: DarkSemanticColors.secondaryButton.rest.background,
  buttonBackgroundChecked: DarkSemanticColors.secondaryButton.pressed.background,
  buttonBackgroundCheckedHovered: DarkSemanticColors.secondaryButton.hover.background,
  ButtonBackgroundDanger: DarkSemanticColors.dangerButton.rest.background,
  ButtonBackgroundDangerHovered: DarkSemanticColors.dangerButton.hover.background,
  ButtonBackgroundDangerPressed: DarkSemanticColors.dangerButton.pressed.background,
  ButtonBackgroundDangerText: DarkSemanticColors.dangerButton.rest.text,
  ButtonBackgroundDangerTextHovered: DarkSemanticColors.dangerButton.hover.text,
  buttonBackgroundDisabled: DarkSemanticColors.disabledButton.background,
  buttonBackgroundHovered: DarkSemanticColors.secondaryButton.hover.background,
  buttonBackgroundPressed: DarkSemanticColors.secondaryButton.pressed.background,
  ButtonBackgroundTag: DarkSemanticColors.tagButton.rest.background,
  ButtonBackgroundTagHovered: DarkSemanticColors.tagButton.hover.background,
  ButtonBackgroundTagPressed: DarkSemanticColors.tagButton.pressed.background,
  ButtonBackgroundTagText: DarkSemanticColors.tagButton.rest.text,
  ButtonBackgroundTagTextHovered: DarkSemanticColors.tagButton.hover.text,
  ButtonBorderDanger: DarkSemanticColors.dangerButton.rest.border,
  ButtonBorderDangerHovered: DarkSemanticColors.dangerButton.hover.border,
  ButtonBorderDangerPressed: DarkSemanticColors.dangerButton.pressed.border,
  ButtonBorderDisabled: DarkSemanticColors.disabledButton.background,
  ButtonBorderFocus: DarkSemanticColors.secondaryButton.focus.border,
  ButtonBorderTag: DarkSemanticColors.tagButton.rest.border,
  ButtonBorderTagHovered: DarkSemanticColors.tagButton.hover.border,
  ButtonBorderTagPressed: DarkSemanticColors.tagButton.pressed.border,
  buttonText: DarkSemanticColors.secondaryButton.rest.text,
  buttonTextChecked: DarkSemanticColors.secondaryButton.pressed.text,
  buttonTextCheckedHovered: DarkSemanticColors.secondaryButton.hover.border,
  buttonTextDisabled: DarkSemanticColors.disabledButton.text,
  buttonTextHovered: DarkSemanticColors.secondaryButton.hover.color,
  buttonTextPressed: DarkSemanticColors.secondaryButton.pressed.text,
  checkboxBackgroundChecked: DarkSemanticColors.checkBox.checked.background,
  checkboxBackgroundHovered: DarkSemanticColors.checkBox.checked.hoverBorder,
  checkBoxBorder: DarkSemanticColors.checkBox.rest.border,
  checkboxBorderChecked: DarkSemanticColors.checkBox.checked.border,
  checkboxBorderCheckedHovered: DarkSemanticColors.checkBox.checked.hoverBorder,
  checkBoxCheck: DarkSemanticColors.checkBox.rest.check,
  checkBoxCheckedFocus: DarkSemanticColors.checkBox.rest.focus,
  checkBoxCheckHover: DarkSemanticColors.checkBox.rest.hover,
  checkBoxCheckHoverTest: DarkSemanticColors.checkBox.rest.hoverText,
  checkBoxCheckedDisabledBackground: DarkSemanticColors.checkBox.disabled.background,
  checkBoxDisabled: DarkSemanticColors.checkBox.disabled.border,
  checkBoxIndeterminateBackground: DarkSemanticColors.checkBox.rest.check,
  choiceGroupUncheckedDotHover: DarkSemanticColors.choiceGroup.circle.hover,
  choiceGroupFocusBorder: DarkSemanticColors.choiceGroup.focus,
  commandBarBorder: DarkSemanticColors.commandBar.border,
  dataColor1: DarkSemanticColors.dataColor.dataColor1,
  dataColor2: DarkSemanticColors.dataColor.dataColor2,
  dataColor3: DarkSemanticColors.dataColor.dataColor3,
  dataColor4: DarkSemanticColors.dataColor.dataColor4,
  dataColor5: DarkSemanticColors.dataColor.dataColor5,
  dataColor6: DarkSemanticColors.dataColor.dataColor6,
  dataColor7: DarkSemanticColors.dataColor.dataColor7,
  dataColor8: DarkSemanticColors.dataColor.dataColor8,
  dataColor9: DarkSemanticColors.dataColor.dataColor9,
  dataColor10: DarkSemanticColors.dataColor.dataColor10,
  datePickerDisabledBorder: DarkSemanticColors.datePicker.disabled.border,
  datePickerSelectionBackground: DarkSemanticColors.datePicker.rest.selected,
  datePickerSelectionText: DarkSemanticColors.datePicker.rest.text,
  disabledBackground: CommonSemanticColors.backgrounds.disabled,
  disabledBodyText: DarkSemanticColors.text.disabled,
  dropdownBackground: DarkSemanticColors.dropDown.background.rest,
  dropdownItemHover: DarkSemanticColors.dropDown.text.hovered,
  dropdownTextHovered: DarkSemanticColors.dropDown.text.hovered,
  errorBackground: DarkSemanticColors.controlOutlines.error,
  errorText: DarkSemanticColors.text.error,
  focusBorder: DarkSemanticColors.controlOutlines.accent,
  inputBackground: DarkSemanticColors.background,
  inputBorder: DarkSemanticColors.secondaryButton.rest.border,
  inputBorderHovered: DarkSemanticColors.secondaryButton.hover.border,
  inputBorderPressed: DarkSemanticColors.secondaryButton.pressed.border,
  inputPlaceholderText: DarkSemanticColors.text.placeholder,
  inputText: DarkSemanticColors.text.value,
  link: DarkSemanticColors.text.hyperlink,
  linkHovered: DarkSemanticColors.text.hyperlinkHovered,
  listBackground: DarkSemanticColors.background,
  listHeaderBackgroundPressed: DarkSemanticColors.item.hover,
  listItemBackgroundChecked: DarkSemanticColors.item.select,
  listItemBackgroundCheckedHovered: DarkSemanticColors.item.select,
  listItemBackgroundHovered: DarkSemanticColors.detailsRow.hoveredBackground,
  listItemBackgroundSelected: DarkSemanticColors.item.select,
  listItemBackgroundSelectedHovered: DarkSemanticColors.item.selectHovered,
  listLinkHovered: DarkSemanticColors.detailsRow.hoveredLink,
  listLinkRowHovered: DarkSemanticColors.detailsRow.hoveredRowLink,
  listLinkRowSelected: DarkSemanticColors.detailsRow.selectedLink,
  listLinkRowSelectedHovered: DarkSemanticColors.detailsRow.selectedHoveredLink,
  listText: DarkSemanticColors.text.body,
  menuItemBackgroundHovered: DarkSemanticColors.item.hover,
  menuItemBackgroundPressed: DarkSemanticColors.item.select,
  noDataColor1: DarkSemanticColors.dataColor.noData1,
  noData2Color: DarkSemanticColors.dataColor.noData2,
  primaryButtonBackground: DarkSemanticColors.primaryButton.rest.background,
  primaryButtonBackgroundDisabled: DarkSemanticColors.disabledButton.background,
  primaryButtonBackgroundHovered: DarkSemanticColors.primaryButton.hover.background,
  primaryButtonBackgroundPressed: DarkSemanticColors.primaryButton.pressed.background,
  primaryButtonBorder: DarkSemanticColors.primaryButton.rest.border,
  primaryButtonBorderDisabled: DarkSemanticColors.primaryButton.disabled.border,
  primaryButtonText: DarkSemanticColors.primaryButton.rest.text,
  primaryButtonTextDisabled: DarkSemanticColors.disabledButton.text,
  primaryButtonTextFocused: DarkSemanticColors.primaryButton.focus.text,
  primaryButtonTextHovered: DarkSemanticColors.primaryButton.hover.text,
  primaryButtonTextPressed: DarkSemanticColors.primaryButton.pressed.text,
  primaryCompoundButtonBorder: DarkSemanticColors.primaryButton.rest.background,
  radioButtonPillBorderDisabled: DarkSemanticColors.radioButton.circle.borderDisabled,
  radioButtonPillCheckedHover: DarkSemanticColors.radioButton.pill.checkedHover,
  radioButtonPillUncheckedDisabled: DarkSemanticColors.radioButton.pill.uncheckedDisabled,
  radioButtonPillUncheckedHover: DarkSemanticColors.radioButton.pill.uncheckedHover,
  radioButtonPillDisabled: DarkSemanticColors.radioButton.pill.disabled,
  radioButtonThumbUnchecked: DarkSemanticColors.radioButton.circle.uncheckedRest,
  radioButtonThumbUncheckedDisabled: DarkSemanticColors.radioButton.pill.disabled,
  radioButtonThumbCheckedDisabled: DarkSemanticColors.radioButton.circle.checkedDisabled,
  rowBorder: DarkSemanticColors.detailsRow.border,
  rowFocus: DarkSemanticColors.detailsRow.focus,
  tabHover: DarkSemanticColors.tabs.hover,
  variantBorder: BaseColors.TRANSPARENT,

  // extended
  commandBarButtonAfterColor: DarkSemanticColors.commandBar.button.focus.borderColor,
  commandBarButtonBackgroundHover: DarkSemanticColors.commandBar.button.hover.background,
  commandBarButtonBackgroundSelected: DarkSemanticColors.commandBar.button.selected.background,
  commandBarButtonBackgroundSelectedHover: DarkSemanticColors.commandBar.button.selectedHover.background,
  commandBarButtonIconHover: DarkSemanticColors.commandBar.button.hover.icon,
  commandBarButtonIconSelected: DarkSemanticColors.commandBar.button.selected.icon,
  commandBarButtonText: DarkSemanticColors.commandBar.button.root.color,
  commandBarButtonTextDisabled: DarkSemanticColors.commandBar.button.disabled.color,
  commandBarButtonTextHover: DarkSemanticColors.commandBar.button.hover.color,
  controlAccent: DarkSemanticColors.controlOutlines.accent,
  controlBackground: DarkSemanticColors.controlOutlines.background,
  controlFocus: DarkSemanticColors.controlOutlines.focus,
  controlOutline: DarkSemanticColors.controlOutlines.rest,
  controlOutlineDisabled: DarkSemanticColors.controlOutlines.disabled,
  controlOutlineHovered: DarkSemanticColors.controlOutlines.hover,
  iconButtonFill: DarkSemanticColors.primaryButton.rest.background,
  iconButtonFillHovered: DarkSemanticColors.commandBar.button.hover.icon,
  labelText: DarkSemanticColors.text.label,
  sliderActiveBackground: DarkSemanticColors.slider.activeBackground,
  sliderInActiveHover: DarkSemanticColors.slider.inactiveBackgroundHovered,
  sliderActiveHover: DarkSemanticColors.slider.activeBackgroundHovered,
  sliderActivePressed: DarkSemanticColors.slider.activeBackgroundPressed,
  sliderDisabledActiveBackground: DarkSemanticColors.slider.activeDisabledBackground,
  sliderDisabledInActiveBackground: DarkSemanticColors.slider.inactiveDisabledBackground,
  statusDefaultBackground: DarkSemanticColors.statusBar.background.information,
  statusDefaultBorder: DarkSemanticColors.statusBar.border.default,
  statusDisabledIcon: DarkSemanticColors.statusBar.icon.disabled,
  statusErrorBackground: DarkSemanticColors.statusBar.background.error,
  statusErrorBorder: DarkSemanticColors.statusBar.border.error,
  statusErrorIcon: DarkSemanticColors.statusBar.icon.error,
  statusInformationBackground: DarkSemanticColors.statusBar.background.information,
  statusInformationText: DarkSemanticColors.text.body,
  statusInformationIcon: DarkSemanticColors.statusBar.icon.information,
  statusSuccessBackground: DarkSemanticColors.statusBar.background.success,
  statusSuccessBorder: DarkSemanticColors.statusBar.border.okay,
  statusLink: DarkSemanticColors.statusBar.link.rest,
  statusLinkHover: DarkSemanticColors.statusBar.link.hover,
  statusUpsellBackground: DarkSemanticColors.statusBar.background.upsell,
  statusUpsellIcon: DarkSemanticColors.statusBar.icon.upsell,
  statusSuccessText: DarkSemanticColors.text.body,
  statusSuccessIcon: DarkSemanticColors.statusBar.icon.success,
  statusWarningBackground: DarkSemanticColors.statusBar.background.warning,
  statusWarningBorder: DarkSemanticColors.statusBar.border.warning,
  statusWarningText: DarkSemanticColors.text.body,
  statusWarningIcon: DarkSemanticColors.statusBar.icon.warning,
  teachingBubbleBackground: DarkSemanticColors.teachingBubble.rest.background,
  teachingBubbleBorder: DarkSemanticColors.teachingBubble.rest.border,
  teachingBubblePrimaryButtonHover: DarkSemanticColors.teachingBubble.hover.primaryButtonBackground,
  teachingBubbleSecondaryBackground: DarkSemanticColors.teachingBubble.rest.secondaryBackround,
  teachingBubbleText: DarkSemanticColors.teachingBubble.rest.text,
  textFieldBorderDisabled: DarkSemanticColors.primaryButton.disabled.border,
  calendarBackground: DarkSemanticColors.calendar.background,
  calendarTextRest: DarkSemanticColors.calendar.text.rest,
  calendarTextHover: DarkSemanticColors.calendar.text.hover,
  calendarTextDisabled: DarkSemanticColors.calendar.text.disabled,
  calendarTextOutside: DarkSemanticColors.calendar.text.outside,
  calendarBackgroundBorder: DarkSemanticColors.calendar.button.border,
  calendarBackgroundSelected: DarkSemanticColors.calendar.button.selected,
  calendarBackgroundHover: DarkSemanticColors.calendar.button.hover,

  // temporary work around for high contrast themes
  choiceGroupContainerBorder: '0px',
  callOutBorderStyle: 'solid',
  choiceGroupContainerBorderStyle: 'solid',
  listUnderline: 'none',
  linkBorderStyle: 'dashed',
};

export const AzureThemeDark: Theme = createTheme({
  fonts: {
    medium: {
      fontFamily: StyleConstants.fontFamily,
      fontSize: FontSizes.size13,
    },
    large: {
      fontSize: FontSizes.size14,
    },
  },
  palette: {
    themePrimary: DarkSemanticColors.controlOutlines.accent,
    neutralPrimary: DarkSemanticColors.text.body,
    neutralDark: DarkSemanticColors.text.body,
    neutralLighter: DarkSemanticColors.shimmer.secondary, // shimmer elements
    neutralLight: DarkSemanticColors.shimmer.primary, // shimmer elements
    neutralLighterAlt: DarkSemanticColors.item.hover, // nav highlight
    neutralQuaternaryAlt: DarkSemanticColors.item.select, // expand button on list controls
    neutralSecondary: DarkSemanticColors.text.label, // persona,
    white: DarkSemanticColors.background, // shimmer elements
  },
  semanticColors: darkExtendedSemanticColors,
  isInverted: true,
});

AzureThemeDark.components = AzureStyleSettings(AzureThemeDark);
