import { createTheme, ITheme } from 'office-ui-fabric-react';
import { CommonSemanticColors, LightSemanticColors } from './AzureColors';
import { IExtendedSemanticColors } from './IExtendedSemanticColors';
import { FontSizes } from './AzureType';
import * as StyleConstants from './Constants';

const lightExtendedSemanticColors: Partial<IExtendedSemanticColors> = {
  calText: '#000000',
  bodyBackground: LightSemanticColors.background,
  bodyText: LightSemanticColors.text.body,
  bodyDivider: CommonSemanticColors.dividers.lineSeparator,
  buttonBackground: LightSemanticColors.secondaryButton.rest.background,
  buttonBackgroundChecked: LightSemanticColors.secondaryButton.pressed.background,
  buttonBackgroundCheckedHovered: LightSemanticColors.secondaryButton.hover.background,
  buttonBackgroundDisabled: '#F3F2F1',
  buttonBackgroundHovered: LightSemanticColors.secondaryButton.hover.background,
  buttonBackgroundHoveredDefault: '#F3F2F1',
  buttonBackgroundPressed: '#EDEBE9',
  buttonBorderColor: '#8A8886',
  buttonBorderHovered: '#8A8886',
  buttonText: '#323130',
  buttonTextChecked: LightSemanticColors.secondaryButton.pressed.border,
  buttonTextCheckedHovered: LightSemanticColors.secondaryButton.hover.border,
  buttonTextDisabled: '#A19F9D',
  buttonTextHovered: LightSemanticColors.secondaryButton.hover.border,
  buttonTextPressed: LightSemanticColors.secondaryButton.pressed.border,
  checkboxBorder: '#323130',
  checkboxBorderHover: '',
  checkboxBorderChecked: '',
  checkmarkColorHover: '#605E5C',
  checkboxBorder2: '#323130',
  checkboxBorderDisabled: '#C8C6C4',
  checkboxCheckedDisabled: '#C8C6C4',
  checkboxCheckedMarkDisabled: '#ffffff',
  checkboxIndeterminateBackground: '#ffffff',
  checkMarkFill: '#ffffff',
  controlGroupBorder: '#323130',
  checkBoxselectedBorderHover: '#005A9E;',
  groupChoiceFill: '#0078D4',
  contextMenuBackground: 'transparent',
  disabledBackground: CommonSemanticColors.backgrounds.disabled,
  disabledToggleBackground: 'transparent',
  disabledBodyText: '#A19F9D',
  disabledIconColor: 'rgb(200, 198, 196)',
  dropdownBorder: '#8A8886',
  dropdownBorderHover: '#323130',
  errorBackground: LightSemanticColors.controlOutlines.error,
  errorText: LightSemanticColors.text.error,
  focusBorder: '#0078D4',
  iconButtonColor: '#0078D4',
  iconButtonDisabledColor: '#A19F9D',
  iconHoveredColor: '#106EBE',
  iconPressedColor: '#005A9E',
  inputBackground: LightSemanticColors.background,
  inputText: '#323130', //LightSemanticColors.text.value,
  inputBorder: CommonSemanticColors.textControlOutline.rest,
  inputBorderHovered: CommonSemanticColors.textControlOutline.hover,
  inputPlaceholderText: '#323130', //LightSemanticColors.text.placeholder,
  link: '#0078D4',
  linkHovered: '#004578',
  listBackground: LightSemanticColors.background,
  listHeaderBackgroundPressed: LightSemanticColors.item.hover,
  listItemBackgroundChecked: '#EDEBE9',
  listItemBackgroundCheckedHovered: LightSemanticColors.item.select,
  listItemBackgroundHovered: '#F3F2F1',
  listText: LightSemanticColors.text.body,
  menuItemBackgroundHovered: '#f3f2f1',
  menuItemBackgroundPressed: '#EDEBE9',
  primaryButtonBackground: '#0078d4',
  primaryButtonBackgroundDisabled: '#F3F2F1',
  primaryButtonBackgroundHovered: '#106EBE',
  primaryButtonBackgroundPressed: '#005A9e',
  primaryButtonBorder: '#0078d4',
  primaryButtonText: '#ffffff',
  primaryButtonTextDisabled: '#A19F9D',
  primaryButtonTextHovered: '#ffffff',
  primaryButtonTextPressed: LightSemanticColors.primaryButton.pressed.text,
  textFieldBorder: '#8A8886',
  textFieldBorderHover: '#323130',
  textFieldBorderActiveFocus: '#0078D4',
  textHovered: '#323130',
  thumbDisabled: '#F3F2F1',
  thumbNotCheck: '#605E5C',
  thumbDisabledNotChecked: '#C8C6C4',
  thumbEnabledChecked: '#ffffff',
  variantBorder: CommonSemanticColors.dividers.lineSeparator,
  // extended
  controlAccent: '#0078D4', //LightSemanticColors.controlOutlines.accent,
  controlOutline: '#323130', //LightSemanticColors.controlOutlines.rest,
  controlOutlineDisabled: '#C8C6C4', //LightSemanticColors.controlOutlines.disabled,
  controlOutlineHovered: '#106EBE', //LightSemanticColors.controlOutlines.hover,

  labelText: LightSemanticColors.text.label,
  statusErrorBackground: LightSemanticColors.statusBar.error,
  statusErrorText: LightSemanticColors.text.body,
  statusErrorIcon: CommonSemanticColors.icons.error,
  statusInformationBackground: LightSemanticColors.statusBar.information,
  statusInformationText: LightSemanticColors.text.body,
  statusInformationIcon: CommonSemanticColors.icons.information,
  statusSuccessBackground: LightSemanticColors.statusBar.okay,
  statusSuccessText: LightSemanticColors.text.body,
  statusSuccessIcon: CommonSemanticColors.icons.okay,
  statusWarningBackground: LightSemanticColors.statusBar.warning,
  statusWarningText: LightSemanticColors.text.body,
  statusWarningIcon: CommonSemanticColors.icons.warning,
};
export const AzureThemeLight: ITheme = createTheme({
  fonts: {
    medium: {
      fontFamily: StyleConstants.fontFamily,
      fontSize: FontSizes.size12,
    },
  },
  palette: {
    themePrimary: LightSemanticColors.controlOutlines.accent,
    neutralPrimary: LightSemanticColors.text.body,
    neutralDark: LightSemanticColors.text.body,
    neutralLight: LightSemanticColors.shimmer.secondary, // shimmer elements
    neutralLighter: LightSemanticColors.shimmer.primary, // shimmer elements
    neutralLighterAlt: LightSemanticColors.item.hover, // nav highlight
    neutralQuaternaryAlt: LightSemanticColors.item.select, // expand button on list controls
    neutralSecondary: LightSemanticColors.text.label, // persona
    white: LightSemanticColors.background, // shimmer elements
  },
  semanticColors: lightExtendedSemanticColors,
});
