/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Create React Component within v9 package
 */
export interface ReactComponentGeneratorSchema {
  /**
   * The name of the component.
   */
  name: string;
  /**
   * The name of the project.
   */
  project: string;
}
