/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Create visual-regression package within FluentUI v9 package
 */
export interface VisualRegressionSchema {
  /**
   * The name of the component package
   */
  project: string;
}
