import type { ComponentStyleSpec } from '@fluentui/style-spec';
import { BadgeSpec, ButtonSpec, DividerSpec } from '@fluentui/component-style-specs';
import { compileStyleSpec } from '../index';

const sample: ComponentStyleSpec = {
  name: 'Sample',
  version: 1,
  slots: ['root', 'icon'],
  variants: {
    appearance: { values: ['filled', 'outline'], default: 'filled' },
    size: { values: ['small', 'medium'], default: 'medium' },
  },
  states: { disabled: { type: 'boolean' } },
  rules: [
    { slot: 'root', declarations: { display: 'inline-flex', color: { token: 'colorNeutralForeground1' } } },
    {
      slot: 'root',
      when: { variants: { appearance: 'outline' } },
      declarations: { border: { concat: [{ token: 'strokeWidthThin' }, ' solid ', { token: 'colorNeutralStroke1' }] } },
    },
    { slot: 'root', when: { variants: { size: 'small' } }, declarations: { height: '16px' } },
    { slot: 'root', when: { states: { disabled: true } }, declarations: { opacity: 0.5 } },
    { slot: 'root', when: { pseudo: ':hover' }, declarations: { cursor: 'pointer' } },
    { slot: 'icon', declarations: { display: 'inline-flex' } },
    { slot: 'icon', when: { rootPseudo: ':hover' }, declarations: { color: { token: 'colorBrandForeground1' } } },
  ],
};

const targets = ['griffel', 'web-components', 'css-modules'] as const;

describe('compileStyleSpec', () => {
  for (const target of targets) {
    it(`compiles the sample spec to ${target} deterministically`, () => {
      const first = compileStyleSpec(sample, { target });
      const second = compileStyleSpec(sample, { target });
      expect(second).toEqual(first);
      expect(first.length).toBeGreaterThan(0);
      for (const file of first) {
        expect(file.contents).toContain('GENERATED BY @fluentui/style-spec-compilers');
        expect(file.contents.length).toBeGreaterThan(20);
      }
    });
  }

  it.each([
    ['Badge', BadgeSpec],
    ['Divider', DividerSpec],
    ['Button', ButtonSpec],
  ] as const)('compiles %s to all targets', (_name, spec) => {
    for (const target of targets) {
      const files = compileStyleSpec(spec, { target });
      expect(files.length).toBeGreaterThan(0);
      // double-compile byte equality
      expect(compileStyleSpec(spec, { target })).toEqual(files);
    }
  });

  it('griffel keeps user className last in mergeClasses', () => {
    const [file] = compileStyleSpec(BadgeSpec, { target: 'griffel' });
    expect(file.contents).toMatch(/mergeClasses\([\s\S]*state\.root\.className,\s*\);/);
  });

  it('web-components emits host attribute selectors for non-default variants', () => {
    const [css] = compileStyleSpec(BadgeSpec, { target: 'web-components' });
    expect(css.contents).toContain(":host([appearance='ghost'])");
    expect(css.contents).toContain('::slotted(svg)');
    expect(css.contents).toContain('var(--colorBrandBackground)');
  });

  it('css-modules uses classes for variants and data attrs for states', () => {
    const [css] = compileStyleSpec(ButtonSpec, { target: 'css-modules' });
    expect(css.contents).toContain('.appearance-primary');
    expect(css.contents).toContain('[data-disabled]');
  });
});
