export { IEffects } from './IEffects';
export { IFontStyles } from './IFontStyles';
export { IPalette } from './IPalette';
export { ISemanticColors } from './ISemanticColors';
export { ISemanticTextColors } from './ISemanticTextColors';
export { ISpacing } from './ISpacing';
export { IAnimationStyles, IAnimationVariables } from './IAnimationStyles';
export { IScheme, ISchemeNames } from './IScheme';
import { ITheme as IThemeXX, IPartialTheme as IPartialThemeXX } from './ITheme';
export * from './Theme';
export type ITheme = IThemeXX;
export type IPartialTheme = IPartialThemeXX;
