export type FluentOverrideValue =
  | {
      f2Token: string;
      rawValue?: never;
    }
  | {
      f2Token?: never;
      rawValue: string;
    };

export type FluentOverrides = Record<string, FluentOverrideValue | null>;

export const fluentOverrides: FluentOverrides = {
  backgroundCtrlActiveBrandDisabled: { f2Token: 'colorNeutralBackgroundDisabled' },
  backgroundCtrlActiveBrandHover: { f2Token: 'colorCompoundBrandBackgroundHover' },
  backgroundCtrlActiveBrandPressed: { f2Token: 'colorCompoundBrandBackgroundPressed' },
  backgroundCtrlActiveBrandRest: { f2Token: 'colorCompoundBrandBackground' },
  cornerZero: { f2Token: 'borderRadiusNone' },
  ctrlChoiceBaseBackgroundDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  ctrlChoiceBaseBackgroundHover: { f2Token: 'colorNeutralStrokeAccessibleHover' },
  ctrlChoiceBaseBackgroundPressed: { f2Token: 'colorNeutralStrokeAccessiblePressed' },
  ctrlChoiceBaseBackgroundRest: { f2Token: 'colorNeutralStrokeAccessible' },
  ctrlChoiceBaseStrokeDisabled: { f2Token: 'colorNeutralStrokeDisabled' },
  ctrlChoiceBaseStrokeHover: { f2Token: 'colorNeutralStrokeAccessibleHover' },
  ctrlChoiceBaseStrokePressed: { f2Token: 'colorNeutralStrokeAccessiblePressed' },
  ctrlChoiceBaseStrokeRest: { f2Token: 'colorNeutralStrokeAccessible' },
  ctrlChoiceSwitchCorner: { f2Token: 'borderRadiusCircular' },
  ctrlChoiceSwitchHeight: { rawValue: '20px' },
  ctrlChoiceSwitchWidth: { rawValue: '40px' },
  ctrlChoicePaddingHorizontal: { f2Token: 'spacingHorizontalS' },
  ctrlChoicePaddingVertical: { f2Token: 'spacingVerticalS' },
  ctrlFocusInnerStroke: { f2Token: 'colorStrokeFocus2' },
  ctrlFocusOuterStroke: { f2Token: 'colorTransparentStroke' },
  ctrlLinkForegroundBrandHover: { f2Token: 'colorBrandForegroundLinkHover' },
  ctrlLinkForegroundBrandPressed: { f2Token: 'colorBrandForegroundLinkPressed' },
  ctrlLinkForegroundBrandRest: { f2Token: 'colorBrandForegroundLink' },
  ctrlLinkForegroundNeutralHover: { f2Token: 'colorNeutralForeground2Hover' },
  ctrlLinkForegroundNeutralPressed: { f2Token: 'colorNeutralForeground2Pressed' },
  ctrlLinkForegroundNeutralRest: { f2Token: 'colorNeutralForeground2' },
  ctrlProgressBackgroundEmpty: { f2Token: 'colorNeutralBackground6' },
  ctrlProgressBackgroundFilled: { f2Token: 'colorCompoundBrandBackground' },
  ctrlProgressCorner: { f2Token: 'borderRadiusMedium' },
  ctrlProgressHeightEmpty: { rawValue: '2px' },
  ctrlProgressHeightFilled: { rawValue: '100%' },
  ctrlProgressLgHeightEmpty: { rawValue: '4px' },
  ctrlProgressLgHeightFilled: { rawValue: '100%' },
  foregroundContentNeutralPrimary: { f2Token: 'colorNeutralForeground1' },
  foregroundCtrlNeutralPrimaryDisabled: { f2Token: 'colorNeutralForegroundDisabled' },
  statusDangerBackground: { f2Token: 'colorPaletteRedBackground3' },
  statusDangerTintForeground: { f2Token: 'colorPaletteRedForeground3' },
  statusSuccessBackground: { f2Token: 'colorPaletteGreenBackground3' },
  statusWarningBackground: { f2Token: 'colorPaletteDarkOrangeBackground3' },
  strokeCtrlOnActiveBrandDisabled: { f2Token: 'colorTransparentStrokeDisabled' },
  strokeCtrlOnActiveBrandHover: { f2Token: 'colorTransparentStrokeInteractive' },
  strokeCtrlOnActiveBrandRest: { f2Token: 'colorTransparentStroke' },
  strokeCtrlOnActiveBrandPressed: { f2Token: 'colorTransparentStrokeInteractive' },
  strokeWidthDefault: { f2Token: 'strokeWidthThin' },
  textGlobalBody1FontSize: { f2Token: 'fontSizeBase500' },
  textGlobalBody1LineHeight: { f2Token: 'lineHeightBase500' },
  textGlobalBody2FontSize: { f2Token: 'fontSizeBase400' },
  textGlobalBody2LineHeight: { f2Token: 'lineHeightBase400' },
  textGlobalBody3FontSize: { f2Token: 'fontSizeBase300' },
  textGlobalBody3LineHeight: { f2Token: 'lineHeightBase300' },
  textGlobalCaption1FontSize: { f2Token: 'fontSizeBase200' },
  textGlobalCaption1LineHeight: { f2Token: 'lineHeightBase200' },
  textGlobalCaption2FontSize: { f2Token: 'fontSizeBase100' },
  textGlobalCaption2LineHeight: { f2Token: 'lineHeightBase100' },
  textGlobalDisplay2FontSize: { f2Token: 'fontSizeHero1000' },
  textGlobalDisplay2LineHeight: { f2Token: 'lineHeightHero1000' },
  textGlobalSubtitle1FontSize: { f2Token: 'fontSizeHero700' },
  textGlobalSubtitle1LineHeight: { f2Token: 'lineHeightHero700' },
  textGlobalSubtitle2FontSize: { f2Token: 'fontSizeBase600' },
  textGlobalSubtitle2LineHeight: { f2Token: 'lineHeightBase600' },
  textGlobalTitle1FontSize: { f2Token: 'fontSizeHero900' },
  textGlobalTitle1LineHeight: { f2Token: 'lineHeightHero900' },
  textGlobalTitle2FontSize: { f2Token: 'fontSizeHero800' },
  textGlobalTitle2LineHeight: { f2Token: 'lineHeightHero800' },
  textStyleDefaultRegularFontFamily: { f2Token: 'fontFamilyBase' },
  textStyleDefaultRegularWeight: { f2Token: 'fontWeightRegular' },
};
