import { IDictionaryStringTo } from './dictionary-types';
import { IMas, mas } from './mas';

export const ruleMasConfiguration: IDictionaryStringTo<IMas[]> = {
  'area-alt': [mas.MAS1_1_1],
  'image-alt': [mas.MAS1_1_1],
  'image-redundant-alt': [mas.MASBest_Practice],
  'input-image-alt': [mas.MAS1_1_1],
  'object-alt': [mas.MAS1_1_1],
  'link-name': [mas.MAS1_1_1, mas.MAS2_4_4, mas.MAS4_1_2],
  'audio-caption': [mas.MAS1_2_1],
  'video-caption': [mas.MAS1_2_2],
  'video-description': [mas.MAS1_2_5],
  'aria-required-children': [mas.MAS1_3_1],
  'aria-required-parent': [mas.MAS1_3_1],
  checkboxgroup: [mas.MASBest_Practice],
  'definition-list': [mas.MAS1_3_1],
  dlitem: [mas.MAS1_3_1],
  'empty-heading': [mas.MASBest_Practice],
  'layout-table': [mas.MAS1_3_1],
  list: [mas.MAS1_3_1],
  listitem: [mas.MAS1_3_1],
  'p-as-heading': [mas.MASBest_Practice],
  radiogroup: [mas.MASBest_Practice],
  'table-duplicate-name': [mas.MASBest_Practice],
  'table-fake-caption': [mas.MASBest_Practice],
  'td-has-header': [mas.MASBest_Practice],
  'td-headers-attr': [mas.MAS1_3_1],
  'th-has-data-cells': [mas.MAS1_3_1],
  'aria-roles': [mas.MAS1_3_1, mas.MAS4_1_1, mas.MAS4_1_2],
  'aria-valid-attr-value': [mas.MAS1_3_1, mas.MAS4_1_1, mas.MAS4_1_2],
  'link-in-text-block': [mas.MASBest_Practice],
  'color-contrast': [mas.MAS1_4_3],
  'meta-viewport-large': [mas.MASBest_Practice],
  'meta-viewport': [mas.MAS1_4_4],
  accesskeys: [mas.MAS2_1_1],
  'server-side-image-map': [mas.MAS2_1_1],
  'meta-refresh': [mas.MAS2_2_1],
  blink: [mas.MAS2_2_2],
  marquee: [mas.MAS2_2_2],
  bypass: [mas.MAS2_4_1],
  'frame-title': [mas.MAS2_4_1],
  'document-title': [mas.MAS2_4_2],
  tabindex: [mas.MASBest_Practice],
  'html-has-lang': [mas.MAS3_1_1],
  'html-lang-valid': [mas.MAS3_1_1],
  'valid-lang': [mas.MAS3_1_2],
  label: [mas.MAS1_3_1, mas.MAS3_3_2],
  'aria-valid-attr': [mas.MAS4_1_1],
  'duplicate-id': [mas.MAS4_1_1],
  'scope-attr-valid': [mas.MASBest_Practice],
  'aria-allowed-attr': [mas.MAS4_1_1, mas.MAS4_1_2],
  'aria-required-attr': [mas.MAS4_1_1, mas.MAS4_1_2],
  'aria-hidden-body': [mas.MAS4_1_2],
  'button-name': [mas.MAS4_1_2],
  'frame-title-unique': [mas.MASBest_Practice],
  'heading-order': [mas.MASBest_Practice],
  'hidden-content': [mas.MASBest_Practice],
  'href-no-hash': [mas.MASBest_Practice],
  'label-title-only': [mas.MASBest_Practice],
  region: [mas.MASBest_Practice],
  'skip-link': [mas.MASBest_Practice],
  'unique-landmark': [mas.MAS2_4_1],
  'landmark-main-is-top-level': [mas.MAS1_3_1, mas.MAS2_4_1],
  'landmark-one-main': [mas.MASBest_Practice],
  'aria-dpub-role-fallback': [mas.MASBest_Practice],
  'focus-order-semantics': [mas.MASBest_Practice],
  'frame-tested': [mas.MASBest_Practice],
  'landmark-banner-is-top-level': [mas.MAS1_3_1, mas.MAS2_4_1],
  'landmark-contentinfo-is-top-level': [mas.MAS1_3_1, mas.MAS2_4_1],
  'landmark-no-duplicate-banner': [mas.MAS1_3_1, mas.MAS2_4_1],
  'landmark-no-duplicate-contentinfo': [mas.MAS1_3_1, mas.MAS2_4_1],
  'page-has-heading-one': [mas.MASBest_Practice],
  'duplicate-id-active': [mas.MAS4_1_1],
  'duplicate-id-aria': [mas.MAS4_1_1],
  'html-xml-lang-mismatch': [mas.MAS3_1_1],
  'get-frame-title': [mas.MAS4_1_2],
  'page-title': [mas.MAS2_4_2],
  'aria-allowed-role': [mas.MASBest_Practice],
  'autocomplete-valid': [mas.MASBest_Practice],
  'css-orientation-lock': [mas.MASBest_Practice]
};
