name: Route mentions to Teams

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mention-to-teams:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run
        continue-on-error: true
        uses: JustSlone/actions-mention-to-teams@v0.4.1-beta
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          run-id: ${{ github.run_id }}
