name: FORK TEST VRT
on:
  push:
    branches:
      - master
  pull_request:
  issue_comment:
    types: [created]

# concurrency:
#   # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

env:
  NX_PARALLEL: 4 # ubuntu-latest = 4-core CPU / 16 GB of RAM | macos-14-xlarge (arm) = 6-core CPU / 14 GB of RAM
  NX_PREFER_TS_NODE: true
  NX_VERBOSE_LOGGING: true

jobs:
  update_baseline:
    if: ${{ github.repository_owner == 'hotell' && github.ref == 'refs/heads/master' && github.event_name=='push' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4.3.0
        with:
          main-branch-name: 'master'

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - run: yarn install --frozen-lockfile
      - run: yarn playwright install --with-deps
      # NOTE: we need to build the assertion CLI - will be removed once migrated ot ESM
      - run: yarn nx run visual-regression-assert:build

      - name: Affected Projects
        id: affected_projects_count
        run: |
          yarn --silent nx show projects -t test-vr-cli --affected --verbose false
          affected_count=$(yarn --silent nx show projects -t test-vr-cli --affected --verbose false | wc -l | tr -d ' ')
          echo "value=$affected_count" >> $GITHUB_OUTPUT

      - name: Download Current Baseline
        uses: actions/download-artifact@v4
        with:
          name: vrt_baseline
          # last successful workflow run
          # run-id: ${{ github.event.head_commit.id }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # download to workspace root to set baseline
          path: '.'

      - name: Update Baseline
        run: yarn nx affected -t test-vr-cli -u

      - name: Upload Baseline
        uses: actions/upload-artifact@v4
        with:
          name: vrt_baseline
          retention-days: 90
          if-no-files-found: error
          path: |
            **/__vrt_baseline__/*.png

  approve_vrt_diff:
    if: github.repository_owner == 'hotell' && github.event.issue.pull_request && contains(github.event.comment.body,'/approve-visual-regression-diff')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: read
      issues: read
    steps:
      - name: Update Existing Check Run
        uses: actions/github-script@v7
        with:
          script: |
            const run = require('./.github/scripts/approve-pr-vrt-diff');
            const config = {};
            await run({github,context,core,config});

  visual_regression:
    if: github.repository_owner == 'hotell' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4.3.0
        with:
          main-branch-name: 'master'

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - run: yarn install --frozen-lockfile
      - run: yarn playwright install --with-deps
      # NOTE: we need to build the assertion CLI - will be removed once migrated ot ESM
      - run: yarn nx run visual-regression-assert:build

      - name: Affected Projects
        id: affected_projects_count
        run: |
          yarn --silent nx show projects -t test-vr-cli --affected --verbose false
          affected_count=$(yarn --silent nx show projects -t test-vr-cli --affected --verbose false | wc -l | tr -d ' ')
          echo "value=$affected_count" >> $GITHUB_OUTPUT

      - name: Run VR tests
        run: yarn nx affected -t test-vr-cli

      - name: Create Report
        if: always() && steps.affected_projects_count.outputs.value > 0
        id: report
        run: |
          yarn visual-regression-assert report --outputPath dist/vrt
          cat dist/vrt/vrt-report.md >> $GITHUB_STEP_SUMMARY
          echo "value=true" >> $GITHUB_OUTPUT

      - name: Upload Report
        if: always() && github.event_name == 'pull_request' && steps.report.outputs.value == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: vrt_report
          retention-days: 1
          if-no-files-found: error
          path: |
            dist/vrt/

      - name: Save PR number
        if: always() && github.event_name == 'pull_request' && steps.report.outputs.value == 'true'
        run: echo ${{ github.event.number }} > pr.txt

      - uses: actions/upload-artifact@v4
        if: always() && github.event_name == 'pull_request' && steps.report.outputs.value == 'true'
        with:
          name: pr-number
          retention-days: 1
          if-no-files-found: error
          path: |
            pr.txt
