name: Pull-Request Houskeeping 🧹
on: [pull_request]
permissions:
  contents: read
  pull-requests: write

jobs:
  milestone-assignment:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to milestone
        uses: andrefcdias/add-to-milestone@v1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          use-expression: true
          milestone: '* Project Cycle *'
