name: Pull-Request Houskeeping 🧹
on: [pull_request]

jobs:
  milestone-assignment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Assign to milestone
        uses: andrefcdias/add-to-milestone@v1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          use-expression: true
          milestone: '* Project Cycle *'
