name: Triage Bot
on:
  issues:
    types:
      - opened

jobs:
  triage-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const config = require('./.github/triage-bot.config.json');
            const run = require('./scripts/triage-bot');
            await run({github,context,core,config});
