// THIS FILE IS GENERATED BY @fluentui/style-spec-compilers. DO NOT EDIT BY HAND.
// @ts-nocheck — generated output; slot/variant state is intentionally loosely typed for PoC.

'use client';

import { makeResetStyles, makeStyles, mergeClasses } from '@griffel/react';
import { tokens } from '@fluentui/react-theme';
import type { SlotClassNames } from '@fluentui/react-utilities';

export const badgeClassNames: SlotClassNames<Record<string, unknown>> = {
  root: 'fui-Badge',
  icon: 'fui-Badge__icon',
};

const useRootBaseClassName = makeResetStyles({
  display: 'inline-flex',
  boxSizing: 'border-box',
  alignItems: 'center',
  justifyContent: 'center',
  position: 'relative',
  fontFamily: tokens.fontFamilyBase,
  fontSize: tokens.fontSizeBase200,
  fontWeight: tokens.fontWeightSemibold,
  lineHeight: tokens.lineHeightBase200,
  height: '20px',
  minWidth: '20px',
  padding: `0 calc(${tokens.spacingHorizontalXS} + ${tokens.spacingHorizontalXXS})`,
  borderRadius: tokens.borderRadiusCircular,
  borderColor: tokens.colorTransparentStroke,
  '::after': {
    content: '""',
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    borderStyle: 'solid',
    borderColor: 'inherit',
    borderWidth: tokens.strokeWidthThin,
    borderRadius: 'inherit',
  },
});

const useRootStyles = makeStyles({
  'appearance-ghost': {
    '::after': {
      display: 'none',
    },
  },
  'appearance-outline': {
    borderColor: 'currentColor',
  },
  'size-tiny': {
    width: '6px',
    height: '6px',
    fontSize: '4px',
    lineHeight: '4px',
    minWidth: 'unset',
    padding: 'unset',
    fontFamily: tokens.fontFamilyBase,
    fontWeight: tokens.fontWeightSemibold,
  },
  'size-extra-small': {
    width: '10px',
    height: '10px',
    fontSize: '6px',
    lineHeight: '6px',
    minWidth: 'unset',
    padding: 'unset',
    fontFamily: tokens.fontFamilyBase,
    fontWeight: tokens.fontWeightSemibold,
  },
  'size-small': {
    minWidth: '16px',
    height: '16px',
    padding: `0 calc(${tokens.spacingHorizontalXXS} + ${tokens.spacingHorizontalXXS})`,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase100,
  },
  'size-large': {
    minWidth: '24px',
    height: '24px',
    padding: `0 calc(${tokens.spacingHorizontalXS} + ${tokens.spacingHorizontalXXS})`,
  },
  'size-extra-large': {
    minWidth: '32px',
    height: '32px',
    padding: `0 calc(${tokens.spacingHorizontalSNudge} + ${tokens.spacingHorizontalXXS})`,
  },
  'shape-rounded': {
    borderRadius: tokens.borderRadiusMedium,
  },
  'shape-square': {
    borderRadius: tokens.borderRadiusNone,
  },
  'appearance-filled--color-brand': {
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
  },
  'appearance-filled--color-danger': {
    backgroundColor: tokens.colorPaletteRedBackground3,
    color: tokens.colorNeutralForegroundOnBrand,
  },
  'appearance-filled--color-important': {
    backgroundColor: tokens.colorNeutralForeground1,
    color: tokens.colorNeutralBackground1,
  },
  'appearance-filled--color-informative': {
    backgroundColor: tokens.colorNeutralBackground5,
    color: tokens.colorNeutralForeground3,
  },
  'appearance-filled--color-severe': {
    backgroundColor: tokens.colorPaletteDarkOrangeBackground3,
    color: tokens.colorNeutralForegroundOnBrand,
  },
  'appearance-filled--color-subtle': {
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
  },
  'appearance-filled--color-success': {
    backgroundColor: tokens.colorPaletteGreenBackground3,
    color: tokens.colorNeutralForegroundOnBrand,
  },
  'appearance-filled--color-warning': {
    backgroundColor: tokens.colorPaletteYellowBackground3,
    color: tokens.colorNeutralForeground1Static,
  },
  'appearance-ghost--color-brand': {
    color: tokens.colorBrandForeground1,
  },
  'appearance-ghost--color-danger': {
    color: tokens.colorPaletteRedForeground3,
  },
  'appearance-ghost--color-important': {
    color: tokens.colorNeutralForeground1,
  },
  'appearance-ghost--color-informative': {
    color: tokens.colorNeutralForeground3,
  },
  'appearance-ghost--color-severe': {
    color: tokens.colorPaletteDarkOrangeForeground3,
  },
  'appearance-ghost--color-subtle': {
    color: tokens.colorNeutralForegroundStaticInverted,
  },
  'appearance-ghost--color-success': {
    color: tokens.colorPaletteGreenForeground3,
  },
  'appearance-ghost--color-warning': {
    color: tokens.colorPaletteYellowForeground2,
  },
  'appearance-outline--color-brand': {
    color: tokens.colorBrandForeground1,
  },
  'appearance-outline--color-danger': {
    color: tokens.colorPaletteRedForeground3,
    borderColor: tokens.colorPaletteRedBorder2,
  },
  'appearance-outline--color-important': {
    color: tokens.colorNeutralForeground3,
    borderColor: tokens.colorNeutralStrokeAccessible,
  },
  'appearance-outline--color-informative': {
    color: tokens.colorNeutralForeground3,
    borderColor: tokens.colorNeutralStroke2,
  },
  'appearance-outline--color-severe': {
    color: tokens.colorPaletteDarkOrangeForeground3,
  },
  'appearance-outline--color-subtle': {
    color: tokens.colorNeutralForegroundStaticInverted,
  },
  'appearance-outline--color-success': {
    color: tokens.colorPaletteGreenForeground3,
    borderColor: tokens.colorPaletteGreenBorder2,
  },
  'appearance-outline--color-warning': {
    color: tokens.colorPaletteYellowForeground2,
  },
  'appearance-tint--color-brand': {
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground2,
    borderColor: tokens.colorBrandStroke2,
  },
  'appearance-tint--color-danger': {
    backgroundColor: tokens.colorPaletteRedBackground1,
    color: tokens.colorPaletteRedForeground1,
    borderColor: tokens.colorPaletteRedBorder1,
  },
  'appearance-tint--color-important': {
    backgroundColor: tokens.colorNeutralForeground3,
    color: tokens.colorNeutralBackground1,
    borderColor: tokens.colorTransparentStroke,
  },
  'appearance-tint--color-informative': {
    backgroundColor: tokens.colorNeutralBackground4,
    color: tokens.colorNeutralForeground3,
    borderColor: tokens.colorNeutralStroke2,
  },
  'appearance-tint--color-severe': {
    backgroundColor: tokens.colorPaletteDarkOrangeBackground1,
    color: tokens.colorPaletteDarkOrangeForeground1,
    borderColor: tokens.colorPaletteDarkOrangeBorder1,
  },
  'appearance-tint--color-subtle': {
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground3,
    borderColor: tokens.colorNeutralStroke2,
  },
  'appearance-tint--color-success': {
    backgroundColor: tokens.colorPaletteGreenBackground1,
    color: tokens.colorPaletteGreenForeground1,
    borderColor: tokens.colorPaletteGreenBorder1,
  },
  'appearance-tint--color-warning': {
    backgroundColor: tokens.colorPaletteYellowBackground1,
    color: tokens.colorPaletteYellowForeground1,
    borderColor: tokens.colorPaletteYellowBorder1,
  },
  'size-tiny--shape-rounded': {
    borderRadius: tokens.borderRadiusSmall,
  },
  'size-extra-small--shape-rounded': {
    borderRadius: tokens.borderRadiusSmall,
  },
  'size-small--shape-rounded': {
    borderRadius: tokens.borderRadiusSmall,
  },
});

const useIconBaseClassName = makeResetStyles({
  display: 'flex',
  lineHeight: '1',
  margin: `0 calc(-1 * ${tokens.spacingHorizontalXXS})`,
  fontSize: '12px',
});

const useIconStyles = makeStyles({
  'size-tiny': {
    fontSize: '6px',
  },
  'size-extra-small': {
    fontSize: '10px',
  },
  'size-small': {
    fontSize: '12px',
  },
  'size-large': {
    fontSize: '16px',
  },
  'size-extra-large': {
    fontSize: '20px',
  },
  'iconPosition-before--state-hasText': {
    marginRight: `calc(${tokens.spacingHorizontalXXS} + ${tokens.spacingHorizontalXXS})`,
  },
  'iconPosition-after--state-hasText': {
    marginLeft: `calc(${tokens.spacingHorizontalXXS} + ${tokens.spacingHorizontalXXS})`,
  },
  'size-extra-large--iconPosition-before--state-hasText': {
    marginRight: `calc(${tokens.spacingHorizontalXS} + ${tokens.spacingHorizontalXXS})`,
  },
  'size-extra-large--iconPosition-after--state-hasText': {
    marginLeft: `calc(${tokens.spacingHorizontalXS} + ${tokens.spacingHorizontalXXS})`,
  },
});

export const useBadgeStyles_unstable = (state: Record<string, any>): typeof state => {
  const rootBaseClassName = useRootBaseClassName();
  const rootStyles = useRootStyles();
  const iconBaseClassName = useIconBaseClassName();
  const iconStyles = useIconStyles();

  if (state.root) {
    state.root.className = mergeClasses(
      badgeClassNames.root,
      rootBaseClassName,
      state.appearance === 'ghost' && rootStyles['appearance-ghost'],
      state.appearance === 'outline' && rootStyles['appearance-outline'],
      state.size === 'tiny' && rootStyles['size-tiny'],
      state.size === 'extra-small' && rootStyles['size-extra-small'],
      state.size === 'small' && rootStyles['size-small'],
      state.size === 'large' && rootStyles['size-large'],
      state.size === 'extra-large' && rootStyles['size-extra-large'],
      state.shape === 'rounded' && rootStyles['shape-rounded'],
      state.shape === 'square' && rootStyles['shape-square'],
      state.appearance === 'filled' && state.color === 'brand' && rootStyles['appearance-filled--color-brand'],
      state.appearance === 'filled' && state.color === 'danger' && rootStyles['appearance-filled--color-danger'],
      state.appearance === 'filled' && state.color === 'important' && rootStyles['appearance-filled--color-important'],
      state.appearance === 'filled' &&
        state.color === 'informative' &&
        rootStyles['appearance-filled--color-informative'],
      state.appearance === 'filled' && state.color === 'severe' && rootStyles['appearance-filled--color-severe'],
      state.appearance === 'filled' && state.color === 'subtle' && rootStyles['appearance-filled--color-subtle'],
      state.appearance === 'filled' && state.color === 'success' && rootStyles['appearance-filled--color-success'],
      state.appearance === 'filled' && state.color === 'warning' && rootStyles['appearance-filled--color-warning'],
      state.appearance === 'ghost' && state.color === 'brand' && rootStyles['appearance-ghost--color-brand'],
      state.appearance === 'ghost' && state.color === 'danger' && rootStyles['appearance-ghost--color-danger'],
      state.appearance === 'ghost' && state.color === 'important' && rootStyles['appearance-ghost--color-important'],
      state.appearance === 'ghost' &&
        state.color === 'informative' &&
        rootStyles['appearance-ghost--color-informative'],
      state.appearance === 'ghost' && state.color === 'severe' && rootStyles['appearance-ghost--color-severe'],
      state.appearance === 'ghost' && state.color === 'subtle' && rootStyles['appearance-ghost--color-subtle'],
      state.appearance === 'ghost' && state.color === 'success' && rootStyles['appearance-ghost--color-success'],
      state.appearance === 'ghost' && state.color === 'warning' && rootStyles['appearance-ghost--color-warning'],
      state.appearance === 'outline' && state.color === 'brand' && rootStyles['appearance-outline--color-brand'],
      state.appearance === 'outline' && state.color === 'danger' && rootStyles['appearance-outline--color-danger'],
      state.appearance === 'outline' &&
        state.color === 'important' &&
        rootStyles['appearance-outline--color-important'],
      state.appearance === 'outline' &&
        state.color === 'informative' &&
        rootStyles['appearance-outline--color-informative'],
      state.appearance === 'outline' && state.color === 'severe' && rootStyles['appearance-outline--color-severe'],
      state.appearance === 'outline' && state.color === 'subtle' && rootStyles['appearance-outline--color-subtle'],
      state.appearance === 'outline' && state.color === 'success' && rootStyles['appearance-outline--color-success'],
      state.appearance === 'outline' && state.color === 'warning' && rootStyles['appearance-outline--color-warning'],
      state.appearance === 'tint' && state.color === 'brand' && rootStyles['appearance-tint--color-brand'],
      state.appearance === 'tint' && state.color === 'danger' && rootStyles['appearance-tint--color-danger'],
      state.appearance === 'tint' && state.color === 'important' && rootStyles['appearance-tint--color-important'],
      state.appearance === 'tint' && state.color === 'informative' && rootStyles['appearance-tint--color-informative'],
      state.appearance === 'tint' && state.color === 'severe' && rootStyles['appearance-tint--color-severe'],
      state.appearance === 'tint' && state.color === 'subtle' && rootStyles['appearance-tint--color-subtle'],
      state.appearance === 'tint' && state.color === 'success' && rootStyles['appearance-tint--color-success'],
      state.appearance === 'tint' && state.color === 'warning' && rootStyles['appearance-tint--color-warning'],
      state.size === 'tiny' && state.shape === 'rounded' && rootStyles['size-tiny--shape-rounded'],
      state.size === 'extra-small' && state.shape === 'rounded' && rootStyles['size-extra-small--shape-rounded'],
      state.size === 'small' && state.shape === 'rounded' && rootStyles['size-small--shape-rounded'],
      state.root.className,
    );
  }

  if (state.icon) {
    state.icon.className = mergeClasses(
      badgeClassNames.icon,
      iconBaseClassName,
      state.size === 'tiny' && iconStyles['size-tiny'],
      state.size === 'extra-small' && iconStyles['size-extra-small'],
      state.size === 'small' && iconStyles['size-small'],
      state.size === 'large' && iconStyles['size-large'],
      state.size === 'extra-large' && iconStyles['size-extra-large'],
      state.iconPosition === 'before' && Boolean(state.hasText) && iconStyles['iconPosition-before--state-hasText'],
      state.iconPosition === 'after' && Boolean(state.hasText) && iconStyles['iconPosition-after--state-hasText'],
      state.size === 'extra-large' &&
        state.iconPosition === 'before' &&
        Boolean(state.hasText) &&
        iconStyles['size-extra-large--iconPosition-before--state-hasText'],
      state.size === 'extra-large' &&
        state.iconPosition === 'after' &&
        Boolean(state.hasText) &&
        iconStyles['size-extra-large--iconPosition-after--state-hasText'],
      state.icon.className,
    );
  }

  return state;
};
